### ISSUE TITLE
cargo run --example ggez fails

### ISSUE THREAD

**Issue by debris** [hecrj/iced#1]
error:

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceNotFound("ui.png", [("/Users/marek/projects/iced/target/release/examples/resources", FilesystemError("Path \"ui.png\" is not valid: must be an absolute path with no references to parent directories")), ("/Users/marek/Library/Application Support/ggez.iced", FilesystemError("Path \"ui.png\" is not valid: must be an absolute path with no references to parent directories")), ("/Users/marek/Library/Preferences/ggez.iced", FilesystemError("Path \"ui.png\" is not valid: must be an absolute path with no references to parent directories"))])', src/libcore/result.rs:999:5
`

**Comment by debris** [comment]
I'm not sure what is the best way to fix it is and how ggez attaches resources to the project

**Comment by hecrj** [comment]
`ggez` loads resources based on the executable location.

In order to run the example, you need to create a `resources` symbolic link in `target/debug/examples` pointing to `examples/resources`. In Fish:

```fish
ln -s (pwd)/examples/resources target/debug/examples/.
```
