### ISSUE TITLE
Image widget not updating size when new image is loaded

### ISSUE THREAD

**Issue by Shootertrex** [hecrj/iced#100]
When providing a new path for an image, the image widget will load the picture, but the size will stay the same as the previous image until changing the window size as seen below:

Before
![2019-12-01_15:31:52_1020x791](https://user-images.githubusercontent.com/6365966/69919916-04482e80-1450-11ea-891f-2a38f0d553f9.png)

After
![2019-12-01_15:32:03_1025x792](https://user-images.githubusercontent.com/6365966/69919917-0611f200-1450-11ea-853f-64672d1b66e6.png)

After digging around a bit, it seems to be an issue with the way the image widget is cached. Simply adding `self.path.hash(state)` to the `hash_layout` method like below fixes it.
```
fn hash_layout(&self, state: &mut Hasher) {
    self.path.hash(state);
    self.width.hash(state);
    self.height.hash(state);
}
```

Seems like a trivial fix to me, so if it looks good to you, I can throw up a PR.

**Comment by hecrj** [comment]
@Shootertrex Thanks for the report!

Yes, the fix sounds good! Feel free to open a PR with it!
