### ISSUE TITLE
Glow canvas handles transparency differently from wgpu

### ISSUE THREAD

**Issue by akhilman** [hecrj/iced#1018]
Here is the moon's shadow that becomes transparent such you can see text from window below.
![image](https://user-images.githubusercontent.com/180812/131770929-308388c0-e2eb-4dd0-8173-1ef79205d36f.png)

All I did is changed backend to glow:
```
diff --git a/examples/solar_system/Cargo.toml b/examples/solar_system/Cargo.toml
index 327fe0aa..bd355c9a 100644
--- a/examples/solar_system/Cargo.toml
+++ b/examples/solar_system/Cargo.toml
@@ -6,5 +6,5 @@ edition = "2018"
 publish = false
 
 [dependencies]
-iced = { path = "../..", features = ["canvas", "tokio", "debug"] }
+iced = { path = "../..", features = ["glow", "glow_canvas", "tokio", "debug"] }
 rand = "0.8.3"

```

**Comment by hecrj** [comment]
I cannot reproduce the issue.

Would you care to share some more information about your environment and hardware?

**Comment by akhilman** [comment]
I can reproduce this issue in Fedora 34 workstation inside kvm virtual machine.
