### ISSUE TITLE
The installation section doesn't match up with crates.io

### ISSUE THREAD

**Issue by HeliosPanoptes** [hecrj/iced#11]
https://crates.io/crates/iced suggests that the right Cargo dependency is `iced = "0.0.0"`

Is the most current version uploaded to crates.io?

**Comment by hecrj** [comment]
Yes, it is here: https://crates.io/crates/iced/0.1.0-alpha

It seems that `crates.io` does not show pre-release versions by default. I was also a bit suprised by this because it is not consistent with `docs.rs`.

**Comment by hecrj** [comment]
This was fixed in #64.
