### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by pickfire** [hecrj/iced#117]
Looking at people wanting to support iOS, why not support both android and ios?

I have no idea how this can be done yet, but there is NDK and https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html may help?

**Comment by simlay** [comment]
There’s interest in both platforms. The thing that’s holding android back is winit support for android. Check out https://github.com/rust-windowing/winit/issues/948. Once winit has better android support, the touch events for android will work for iced on both platforms.

**Comment by ReekyMarko** [comment]
This issue is also covered in #302, which talks about mobile support in general, so we could just track this there.

**Comment by adals** [comment]
https://github.com/rust-windowing/winit/pull/1556 merged which closed https://github.com/rust-windowing/winit/issues/948

**Comment by pickfire** [comment]
Should we close this issue?

**Comment by hecrj** [comment]
Yes, let's keep the discussion going in #302.
