### ISSUE TITLE
Constants applicable to all renderers

### ISSUE THREAD

**Issue by AlisCode** [hecrj/iced#12]
Hi !

As you may have noticed, I'm currently writing a `ncurses`-based renderer for iced on my spare time, and am using my own fork of `iced` for that purpose.

The only modification I did was to change some defaults. As it happens, the current constants are assuming pixel unit when pancurses of course works with lines and columns. This makes the current default on some Widgets (e.g. Checkbox, Slider, and Buttons) completely wrong. 

Even if not considering my use case, which I agree is fairly uncommon, I am not sure what these constants were there for in the first place, because they assume some sort of mandatory smaller screen resolution.

What do you think would be the correct way of not enforcing those defaults upon every renderer implementor ?

**Comment by hecrj** [comment]
This is one of the main reasons the current release is `alpha`.

I have shared my thoughts about this in #6. It should be simple to fix, we just need to choose a solution.

Also, I think we can split layouting and events into its own crate. Thus, I am rethinking some of the design a bit and there may be related changes soon.
