### ISSUE TITLE
Why hardcode the URL of ggez to a specific version?

### ISSUE THREAD

**Issue by mlindner** [hecrj/iced#13]
https://github.com/hecrj/iced/blob/e6f9b5a16e0b529c4d4cacd6d07e47577403ae39/Cargo.toml#L28

Why is the specific URL hardcoded instead of using the mainline 0.5.1 release?

**Comment by hecrj** [comment]
It's explained in the examples `README`: https://github.com/hecrj/iced/tree/master/examples#tour

Basically, I fixed issues on HiDPI displays and added a type to efficiently cache text measurements.
