### ISSUE TITLE
Resizing to very small window will crash the svg example 

### ISSUE THREAD

**Issue by piaoger** [hecrj/iced#133]
how to reproduce:

- run the svg example: cargo run --release --example svg --features svg
- resize the window to very small size
- crash!

more information:

- environment: macosx
- error message: 
```
   validateTextureDimensions:1080: failed assertion `MTLTextureDescriptor has width of zero.'
   Abort trap: 6
```

**Comment by hecrj** [comment]
Thanks for the report!

We basically need to avoid trying to draw anything if any of the dimensions is zero. It should be an easy fix. Let me give it a shot.

**Comment by hecrj** [comment]
#134 should fix this!

**Comment by piaoger** [comment]
I tried your change and it's fixed.  👍
