### ISSUE TITLE
Build failed on Fedora 30 (openssl-devel is installed)

### ISSUE THREAD

**Issue by silvioprog** [hecrj/iced#136]
Hi.

I have been trying to build Iced on Fedora 30, but it fails with the attached log below. So, is there any documentation showing the required dependencies (libs) to build the project?

Thank you!

<hr>

Attachment: [log.txt](https://github.com/hecrj/iced/files/4008146/log.txt)

**Comment by hecrj** [comment]
Thanks for the report.

I think this is related to #58 and #119. Do you have `pkg-config` installed? Which version of `fontconfig` do you have (i.e. `pkg-config --modversion fontconfig`)?

In most environments, building `fontconfig` from source is not necessary: https://github.com/servo/libfontconfig/blob/master/build.rs#L14

**Comment by silvioprog** [comment]
Thanks for commenting. This project sounds promising!

After installing the `fontconfig`, I managed to compile all examples and they worked like a charm.

Just for reference, on Fedora 30, the required packages are:

```bash
sudo dnf install openssl-devel libxml2-devel freetype-devel fontconfig-devel
```

Thank you again! :-)
