### ISSUE TITLE
CI for Web does not build iced

### ISSUE THREAD

**Issue by michael-hart** [hecrj/iced#142]
I'm running on Windows 10 and trying to compile to wasm32-unknown-unknown.

I can run the command used in CI and get the same result:
```bash
cargo check --package iced --target wasm32-unknown-unknown
```

However, if I try to compile an example package, there are multiple packages that will not compile. Firstly, async-std uses net2 indirectly, and net2 will not compile to wasm32. I can comment this out as it's not used in the tour example. Secondly, wgpu-native won't compile because it hasn't compile `gfx_backend_vulkan`. The command I'm using is:

```bash
cargo build --example tour --target wasm32-unknown-unknown
```

I understand that having submodules breaking the build isn't ideal, but it has pointed out to me that the CI is passing for web, and yet does not build.

Also, interestingly, compiling the library without specifying an example completes successfully. Maybe that will have an effect?

**Comment by hecrj** [comment]
This is intended. I mentioned the reasoning in #129:

> Given we are still exploring, I don't think we should currently focus on offering a fully compatible cross-platform API when it comes to widgets in master (although PRs fixing this are welcome!). We should be able to batch work on each side and avoid jumping back and forth too much.

**Comment by michael-hart** [comment]
Ah - that makes sense. I wonder if there's somewhere this could be stated to stop people raising the issue I have? I can't think of a good place.

Thanks for your response!

**Comment by hecrj** [comment]
Thanks for the suggestion! I think we can make a note in the examples `README`.

**Comment by michael-hart** [comment]
Possibly also the web README? Users have to read that to find out how to build for web anyway!
