### ISSUE TITLE
Failed to run custom build command for `x11 v2.18.1` (Ubuntu 18.04.3 LTS)

### ISSUE THREAD

**Issue by realcr** [hecrj/iced#157]
Hi, thank you for your work on this project!

I am trying to run one of the examples in the repository, and I get a custom build error:
```bash
$ cargo run --example todos
   Compiling x11 v2.18.1
   Compiling crc32fast v1.2.0
   Compiling sluice v0.4.2
   Compiling idna v0.2.0
   Compiling ryu v1.0.2
   Compiling num-traits v0.2.11
   Compiling num_cpus v1.11.1
   Compiling crossbeam-utils v0.7.0
error: failed to run custom build command for `x11 v2.18.1`

Caused by:
  process didn't exit successfully: `/home/real/temp/iced/target/debug/build/x11-e5150e0e5a5a6cee/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\n" } }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Environment information:

```bash
$ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
Ubuntu 18 is a very mainstream distribution, and I don't have anything special about my system. Therefore I assume many other people might have the same issue. 

Are there any special things I need to install before being able to run the examples on my system? If so, is there a place I can read about it? I couldn't find any information about prior requirements in the main README.

Might be related to:
- https://github.com/hecrj/iced/issues/119
- https://github.com/hecrj/iced/issues/75

**Comment by hecrj** [comment]
You are most likely missing the package [`libx11-dev`](https://packages.ubuntu.com/bionic/libx11-dev).

The packages necessary to build the examples change depending on the OS and distribution used. We should probably gather them in a document at some point. My best advice is to follow the compiler errors for now.
