### ISSUE TITLE
File drag and drop support

### ISSUE THREAD

**Issue by sumibi-yakitori** [hecrj/iced#158]
The application I am trying to create requires drag and drop of files.
I'm glad if you add `winit::event::WindowEvent::DroppedFile` to `iced_winit`.

https://docs.rs/iced_winit/0.1.0-alpha.1/src/iced_winit/application.rs.html#250

**Comment by hecrj** [comment]
Thanks for the suggestion. It seems fairly straighforward to add. I'll take a look!

Just curious, what are you trying to build?

**Comment by sumibi-yakitori** [comment]
Thanks for this beautiful UI framework.

I'm trying to develop a small tool for processing and managing image assets using Rust.
It's useful to support drag-and-drop on iced, as the images location is scattered around.
