### ISSUE TITLE
Drag,drop,hovered events are not generated in events example

### ISSUE THREAD

**Issue by cossonleo** [hecrj/iced#167]
rev: 8957883a88ce98de3d37cdb1e658db5c6777ff1f

env: fedora/gnome 3.34.2/wayland

bug: Drag,drop,hovered events are not generated in events example

**Comment by hecrj** [comment]
Do you mean the `FileHovered`, `FileDropped` and `FilesHoveredLeft` events?

It could be a `winit` issue. Are the events generated in this example? https://github.com/rust-windowing/winit/blob/master/examples/window.rs

**Comment by cossonleo** [comment]
Thx

**Comment by LeSnake04** [comment]
Looks like it still isnt fixed. Can you please reopen and close the issue when support is added?

**Comment by LeSnake04** [comment]
Workaround: Force Xwayland by adding     
```rust 
std::env::set_var("WINIT_UNIX_BACKEND", "x11");
```
before `Gui::run()`
