### ISSUE TITLE
There is a problem with UI rendering

### ISSUE THREAD

**Issue by cossonleo** [hecrj/iced#172]
On win10 intel gpu
rev:  69f20f981af4d4a25ac30a2d7eca437b483edcce 

There is a problem with UI rendering, seems text rending

![图片](https://user-images.githubusercontent.com/20379044/73250338-a8044f80-41f1-11ea-8ef5-962a0fc17ace.png)

**Comment by hecrj** [comment]
Most likely a driver issue. Could you try a [`wgpu`] example and see if any graphical glitches happen? Also, ensure your graphics drivers are up-to-date.

[`wgpu`]: https://github.com/gfx-rs/wgpu-rs

**Comment by cossonleo** [comment]
wgpu's examples run correct. And iced's todos still run abnormal on other win10. So it seems isn't wgpu or driver's problem. it seems is iced problem.
![myFile](https://user-images.githubusercontent.com/20379044/73348472-6e504900-42c4-11ea-98b9-ae63873530e3.gif)

**Comment by hecrj** [comment]
> And iced's todos still run abnormal on other win10.

Are they both using Intel integrated graphics?

**Comment by ikazos** [comment]
I'm also having similar glitches (with `tour` and `todos`). Here's some info about my machine/environment:

*   My OS: Windows 10 Home 64-bit (10.0, Build 17763)
*   My graphics card: NVIDIA GeForce GTX 1650
*   `rustc --version`: rustc 1.41.0 (5e1a79984 2020-01-27)

`tour`: text blinks upon mouse movement / keyboard strokes, scales randomly. Here are some screenshots.

![capture1](https://user-images.githubusercontent.com/42946872/73588541-74971e80-4498-11ea-9731-4bd622758fc2.PNG)
![capture2](https://user-images.githubusercontent.com/42946872/73588542-74971e80-4498-11ea-884f-d92850dd9e10.PNG)
![capture3](https://user-images.githubusercontent.com/42946872/73588543-74971e80-4498-11ea-867b-8fdcc657e393.PNG)

`wgpu_glyph` (I have opened [a PR](https://github.com/hecrj/wgpu_glyph/pull/31) that fixes a small problem): runs fine, no blinking. Here are screenshots for `hello`, `depth`, `clipping`, listed in order.

![capture4](https://user-images.githubusercontent.com/42946872/73588573-cfc91100-4498-11ea-8a44-5afdab9f77ae.PNG)
![capture5](https://user-images.githubusercontent.com/42946872/73588574-cfc91100-4498-11ea-9722-489310781db8.PNG)
![capture6](https://user-images.githubusercontent.com/42946872/73588575-cfc91100-4498-11ea-97de-ad50a7db82ba.PNG)

**Comment by hecrj** [comment]
@ikazos Do you have an integrated GPU in your setup? The current renderer will default to using an integrated GPU if available to save power. If this is the case, the patch mentioned in #148 should fix the issue for you while we sort things out.

**Comment by ikazos** [comment]
@hecrj I followed [this patch](https://github.com/hecrj/iced/issues/148#issuecomment-573455242) in #148 as you mentioned and the examples work. Thanks!

**Comment by cossonleo** [comment]
@hecrj It is still not fine with winit 0.21

**Comment by cossonleo** [comment]
it use vulkan backend as default on my win10,.Due to driver's problem, the examples render not correct. But it use dx12 so that examples work fine when I set application setting.antialiasing true.
