### ISSUE TITLE
Capture Key Events

### ISSUE THREAD

**Issue by cryptoquick** [hecrj/iced#173]
Is there a good way to, say, capture the Command-Q key event to quit the app on MacOS?

We tried to implement this pulling in some of the core iced code into our application, but the approach was less than ideal.

**Comment by hecrj** [comment]
In native platforms, you should be able to use the `Subscription` returned by `iced_native::subscription::events` to listen to shell events directly.

The [`events`]  example showcases this.

[`events`]: https://github.com/hecrj/iced/blob/master/examples/events/src/main.rs#L53

**Comment by cryptoquick** [comment]
I'll take a look and see if I can get this to work. You added it to a milestone, so do you think there's additional work needed to be done to make this easier?

**Comment by hecrj** [comment]
Yes. As I said, there should eventually be some built-in cross-platform subscriptions like `keyboard::on_press`, `keyboard::on_release`, `window::on_resize`, etc.

**Comment by cryptoquick** [comment]
Wow, that'd be really great! For now I'll try to use the approach you mentioned earlier.

**Comment by abreis** [comment]
Note though, that for Cmd-Q on macOS, the events subscription doesn't intercept the key combination and the app is still forcefully terminated. 

#170 is probably the solution for this, as well as to have a way to gracefully quit the `Application` as proposed in https://github.com/hecrj/iced/issues/170#issuecomment-578807687.

**Comment by hecrj** [comment]
@abreis Correct. I introduced this change in #195.

**Comment by cryptoquick** [comment]
@hecrj Yeah, I had tested this on the other PR, this issue can be closed.
