### ISSUE TITLE
A MS paint clone as example

### ISSUE THREAD

**Issue by kindlychung** [hecrj/iced#18]
Would be a fun way to show how to do things with iced. :)

**Comment by hecrj** [comment]
Yes, this would be a great example to showcase icons, tooltips, modals, a drawable canvas, etc.

We could implement this on top of `ggez` or `coffee` (which already has [a mesh example that allows you to draw lines](https://gfycat.com/academicglossykingfisher)) with custom widgets somewhat easily.

However, I want to start working on a general purpose low-level renderer (#8) that users can use out of the box. Ideally, we should be able to build an example like this with it. There is still a long way to go until we get there, though!
