### ISSUE TITLE
Purpose of `text_input::State::is_pasting`

### ISSUE THREAD

**Issue by Finnerale** [hecrj/iced#184]
While trying to understand the architecture of Iced I started implementing selecting text for the native `TextInput`.
When I wanted to implement copying to the clipboard I got irritated about what the purpose of [`is_pasting`](https://github.com/hecrj/iced/blob/95880ca74bddb6a23774621ef766b91956d40a61/native/src/widget/text_input.rs#L503) is as it seems to get cleared right after being set.
Does it have some purpose or can it be ignored / removed?

**Comment by hecrj** [comment]
Currently, it's used to ignore any received characters while a user keeps pasting text (for instance, if a user keeps `Ctrl + V` pressed for a while). However, I think we should just cancel the pasting completely in that case.

That said, text selection is tricky and may involve changing the `State` considerably. For instance, the scrolling offset of a `TextInput` is currently determined from the cursor position alone. However, most toolkits implement a stateful offset that only changes when the cursor is close to the edges of the clipping area. Text selection will force us to implement this and unify it somehow.

Additionally, if we are going to add text selection complexity it may be good idea to have in mind a multi-line text input or `TextArea` and implement a general solution instead.

**Comment by hecrj** [comment]
Oh, I forgot it is also used to cache the clipboard contents. Accessing the clipboard can be quite slow.

I took a look at your branch and looks very promising! :tada:

**Comment by hecrj** [comment]
Closing as #202 landed.
