### ISSUE TITLE
Example stopwatch crash

### ISSUE THREAD

**Issue by johnriderr** [hecrj/iced#188]
If move window, when the stopwatch turned on, application crushes.

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'`

**Comment by hecrj** [comment]
I can't reproduce the issue.

Could you provide the whole backtrace? You can get one by setting the env variable: `RUST_BACKTRACE=1`.

If it's a graphics issue, it may be related to #87.

**Comment by johnriderr** [comment]
`Running `C:\rust projects\iced\target\debug\stopwatch.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\macros\mod.rs:15:40
stack backtrace:
   0: core::fmt::write
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   1: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   2: std::sys_common::backtrace::_print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   3: std::sys_common::backtrace::print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   4: std::panicking::default_hook::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   5: std::panicking::default_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   6: std::panicking::rust_panic_with_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
   7: std::panicking::begin_panic_handler
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
   8: core::panicking::panic_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:84
   9: core::panicking::panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:51
  10: core::option::Option<winit::event::Event<stopwatch::Message>>::unwrap<winit::event::Event<stopwatch::Message>>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\macros\mod.rs:15
  11: winit::platform_impl::platform::event_loop::runner::BufferedEvent<stopwatch::Message>::from_event<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:62
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<stopwatch::Message>::buffer_event<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:260
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<stopwatch::Message>::send_event<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:144
  14: winit::platform_impl::platform::event_loop::ThreadMsgTargetSubclassInput<stopwatch::Message>::send_event<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:116
  15: winit::platform_impl::platform::event_loop::thread_event_target_callback<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:1934
  16: DefSubclassProc
  17: DefSubclassProc
  18: AddClipboardFormatListener
  19: CallWindowProcW
  20: CallWindowProcW
  21: IsRectEmpty
  22: KiUserCallbackDispatcher
  23: GetSystemMetrics
  24: IsThemeActive
  25: OpenThemeData
  26: OpenThemeData
  27: GetSystemMetrics
  28: winit::platform_impl::platform::event_loop::public_window_callback<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:826
  29: DefSubclassProc
  30: DefSubclassProc
  31: AddClipboardFormatListener
  32: CallWindowProcW
  33: CallWindowProcW
  34: glDebugEntry
  35: AddClipboardFormatListener
  36: CallWindowProcW
  37: CallWindowProcW
  38: IsRectEmpty
  39: KiUserCallbackDispatcher
  40: GetSystemMetrics
  41: IsThemeActive
  42: OpenThemeData
  43: OpenThemeData
  44: GetSystemMetrics
  45: AddClipboardFormatListener
  46: CallWindowProcW
  47: CallWindowProcW
  48: Ordinal234
  49: DefSubclassProc
  50: DefSubclassProc
  51: winit::platform_impl::platform::event_loop::public_window_callback<stopwatch::Message>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:653
  52: DefSubclassProc
  53: DefSubclassProc
  54: AddClipboardFormatListener
  55: CallWindowProcW
  56: CallWindowProcW
  57: glDebugEntry
  58: AddClipboardFormatListener
  59: CallWindowProcW
  60: DispatchMessageW
  61: DispatchMessageW
  62: winit::platform_impl::platform::event_loop::EventLoop<stopwatch::Message>::run_return<stopwatch::Message,closure-0>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:235
  63: winit::platform_impl::platform::event_loop::EventLoop<stopwatch::Message>::run<stopwatch::Message,closure-0>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:192
  64: winit::event_loop::EventLoop<stopwatch::Message>::run<stopwatch::Message,closure-0>
             at C:\Users\gamer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\event_loop.rs:148
  65: iced_winit::application::Application::run<iced::application::Instance<stopwatch::Stopwatch>>
             at C:\rust projects\iced\winit\src\application.rs:200
  66: iced::application::Application::run<stopwatch::Stopwatch>
             at C:\rust projects\iced\src\application.rs:177
  67: std::rt::lang_start::{{closure}}<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  68: std::rt::lang_start_internal::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  69: std::panicking::try::do_call<closure-0,i32>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  70: panic_unwind::__rust_maybe_catch_panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  71: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  72: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  73: std::rt::lang_start_internal
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  74: std::rt::lang_start<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  75: main
  76: BaseThreadInitThunk
  77: RtlGetAppContainerNamedObjectPath
  78: RtlGetAppContainerNamedObjectPath
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\rust projects\iced\target\debug\stopwatch.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)`

**Comment by hecrj** [comment]
@johnriderr Thank you. This is a `winit` issue. I have opened a PR with a fix: https://github.com/rust-windowing/winit/pull/1468
