### ISSUE TITLE
Set up a chat server

### ISSUE THREAD

**Issue by hecrj** [hecrj/iced#19]
I think a channel for low-effort and low-latency communication may be a good idea to coordinate development between contributors, answer quick questions, and build a community around the library.

While it may be a bit early to do this now, I think we can start discussing our options so we are ready if/when the time comes. Here are the ones I know of:

- __[Discord]__, this is widely used in the Rust ecosystem. The official Rust Programming Language and the Rust Community servers are on Discord.
- __[Gitter]__, a very common alternative. I use it for [`coffee`], [`wgpu`] and [`gfx`].
- __[Matrix]__. I know [`winit`] uses it, but I am not very familiar with it.
- __[Zulip]__. I haven't used it, not sure how much it favours low-effort messages.
- __[Rocket.Chat]__. I just heard of it recently. It looks very interesting.

[Discord]: https://discordapp.com/
[Gitter]: https://gitter.im/
[Matrix]: https://matrix.org/
[Zulip]: https://zulipchat.com/
[Rocket.Chat]: https://rocket.chat/
[`coffee`]: https://github.com/hecrj/coffee
[`wgpu`]: https://github.com/gfx-rs/wgpu-rs
[`gfx`]: https://github.com/gfx-rs/gfx
[`winit`]: https://github.com/rust-windowing/winit

I personally think Discord is the option with less friction while still getting a pretty flexible server and functional clients. However, I understand there may be other concerns when choosing a chat server.

Feel free to share your thoughts, experiences, and favorite choices here!

**Comment by clarkmoody** [comment]
If you've already got Gitter communities going for `coffee` and other GUI-related repos, I would go with that.

**Comment by hecrj** [comment]
The truth is the Gitter channel for `coffee` is rarely active. I have also seen some folks criticize the Gitter client, which is quite bloated and buggy.

I would say the Rust Community Discord is where I have had most of the conversations about `coffee` and `iced`. Some people have also approached me directly on Discord too. This is also where I direct people in the "Contributing" section of the `README` as of now.

**Comment by olanod** [comment]
Keybase? "Free encrypted slack" is nice and has several clients for different platforms including official cli client ❤️ check it out even if it's not the chosen one 😉

**Comment by ronCYA** [comment]
Now that text input and scrolling are in, joint discussion will be handy for completing the TodoMVC example! @hecrj Would you be able to gain an opinion on Zulip?

I give it a +1 as it's focused around channel sub-topics: [Zuplip-topics](https://zulipchat.com/static/images/why-zulip/zulip-topics.png) The idea is that we have channels like #feature-development and #usage-help which have specific sub-topics like TodoMVC or WASM. Drop your message in and even if no one discusses it immediately, you don't have to keep a mental track of the topic you raised 100 messages ago like in a normal channel. Later if someone wants to discuss that topic without reading through unrelated messages, all the history of discussion on that topic is right there.

It also offers its premium tier to open source projects for free :D

**Comment by hecrj** [comment]
@ronCYA I have been playing with it and I like the idea! I do sometimes feel on Discord that interesting topics drown and are hard to bring back up.

Zulip is also the server used for the `xi-editor` and `druid` (https://xi.zulipchat.com/). I have been taking a look and it seems great to coordinate work.

For now, I have created a draft organization for Iced here: https://iced.zulipchat.com/ I'd appreciate some advice, as you seem to be already familiar with it!
