### ISSUE TITLE
How can I can use dx11 or dx12 backend?

### ISSUE THREAD

**Issue by cossonleo** [hecrj/iced#207]
@hecrj Thanks for your work
It is vulkan backend when I run wgpu-rs's example describe.
Is Iced alaways use vulkan?
If not, how can I check the backend of iced.
If it is not default dx11 or dx12 on windows, How Can I switch to dx11 or dx12?

**Comment by hecrj** [comment]
`wgpu` should choose the best option depending on the OS. If I remember correctly, it should choose DirectX 12 on Windows if available before Vulkan.

I've been meaning to add this information to the debug overlay. I will try to open a PR today!

**Comment by cossonleo** [comment]
@hecrj  When I assign Application's setting.antialiasing true, it use dx12 and example will run fine.
But default, wgpu will use PowerPreference default, and it will use vulkan backend on my win10 laptop, but win10's driver does not fully support vulkan. #172

**Comment by hecrj** [comment]
Glad to help!

Just for the record, this is caused by `wgpu` choosing your integrated GPU by default. Once you enable anti-aliasing, the `PowerPreference` changes to `HighPerformance` and `wgpu` chooses your dedicated GPU instead.
