### ISSUE TITLE
Panic running examples on Ubuntu 18.04

### ISSUE THREAD

**Issue by Charles-Schleich** [hecrj/iced#212]
Error message.
```shell
charles@charles-TE:~/rust/iced/examples/progress_bar (master)
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `/home/charles/rust/iced/target/debug/progress_bar`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
``` 
```shell
charles@charles-TE:~/rust/iced/examples/progress_bar (master)
$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Am i attempting to run this incorrectly ?
I have done a clean build. are there any libraries I need to support this ? 
or some command line arguments to target a specific renderer ?

Works fine on my windows target, just my ubuntu target that is failing.

**Comment by Charles-Schleich** [comment]
Do i need Vulkan installed on Ubuntu to run this ?
Even if i don't have a discrete GPU ?

**Comment by hecrj** [comment]
Yes, you need a graphics driver that supports Vulkan.

There is no built-in OpenGL / software renderer yet.
