### ISSUE TITLE
Problems with Scrollable

### ISSUE THREAD

**Issue by MGlolenstine** [hecrj/iced#216]
I'm having some problems getting Scrollable to work.
I even copied the [part of the example](https://github.com/hecrj/iced/blob/master/examples/styling/src/main.rs#L95), but even that one is throwing errors.
![image](https://user-images.githubusercontent.com/9406770/76441596-f5aed300-63bf-11ea-81a4-ba42378d3c70.png)
Now I'm unsure how to proceed or how to give it the `Message` type it requires.

Thanks for the help!

**Comment by MGlolenstine** [comment]
Figured it out, apparently, it didn't require 2 arguments, but only one, so I solved it by using `Scrollable<Message>` where `Message` is my message class.

**Comment by hecrj** [comment]
Correct. `iced::Scrollable` is a type alias of `iced_native::Scrollable` but with an associated `iced_wgpu::Renderer`.

See [the documentation](https://iced-docs.now.sh/iced/widget/scrollable/type.Scrollable.html).
