### ISSUE TITLE
Send message on Label click

### ISSUE THREAD

**Issue by MGlolenstine** [hecrj/iced#217]
Is there a way to send a message when the Label is clicked?

I'm trying to make a dynamically generated list of labels and when one of them is clicked, I want to send it's `index` to the update function.

**Comment by hecrj** [comment]
What do you mean by "the Label"?

I think you should be able to use the `Button` widget. Most of the examples use it.

**Comment by MGlolenstine** [comment]
With `the Label` I meant the `Text` widget.
I'm sorry, but coming from the GTK+, I'm still mixing them up... :)

I could use the Button, but I want it to look like a `ListView` and not a `Menu`, if you know what I mean.

**Comment by hecrj** [comment]
No worries! Just wanted to know if you were using a custom widget.

You should be able to leverage [`Button::style`](https://iced-docs.now.sh/iced_native/widget/button/struct.Button.html#method.style) with your own custom [`StyleSheet`](https://iced-docs.now.sh/iced/widget/button/trait.StyleSheet.html) to remove the default background color. The [`styling`](https://github.com/hecrj/iced/blob/master/examples/styling/src/main.rs) example can serve you as a guide.

**Comment by MGlolenstine** [comment]
Oooh, I didn't know that it was that easy to style widgets.

Thanks for the help!
