### ISSUE TITLE
Collapsible

### ISSUE THREAD

**Issue by raidwas** [hecrj/iced#231]
I skimmed through the code but couldn't find something in the direction of a collapsible.
I think a collapsible is a valuable widget in order to save space (horizontal or vertical, but most often horizontal) and could be used as a building block for tree like widgets.

Similar to tables a obvious question that comes to my mind is: what is the width of a collapsed collapsible? Is it the width of its content, or a minimal width required to draw the collapsed collapsible?
As was the decision for [tables](https://github.com/hecrj/iced/pull/189#pullrequestreview-359267713) I would opt for a fixed size for now.

Similar to [this](https://api.flutter.dev/flutter/material/ExpansionPanel-class.html) (flutter).

Since iced currently has no animations the collapsible would obviously have no animation.

If someone would point me into the right direction I would also try and give this a shot :)

**Comment by hecrj** [comment]
Instead of a custom widget, I believe this could be built directly as `view` logic using a combination of different widgets.

```rust
struct Collapsible {
    title: String,
    button: button::State,
    is_expanded: bool,
}

impl Collapsible {
    pub fn new(title: String) -> Self { /* ... */ }

    pub fn toggle(&mut self) { /* ... */ }

    pub fn view<'a>(
        &'a mut self,
        on_toggle: Message,
        view_body: impl Fn() -> Element<'a, Message> + 'a
    ) -> Element<'a, Message> {
        let header =
            Button::new(&mut self.button, Text::new(&self.title))
                .on_press(on_toggle);

        if self.is_expanded {
            Column::new().push(header).push(view_body()).into()
        } else {
            header.into()
        }
    }
}
```

Any reason why something like this would not work? Widgets are meant to be basic primitives providing interactions that cannot be achieved using composition of other existing widgets.

**Comment by raidwas** [comment]
> should we call these "components"?
I think i prefer "container" (as it contains other widgets or containers, which it layouts according to some rules).
Similar I would say that a column is a container that can contain other containers and layouts them below each other.

And yes, I think that might work. I will try it out and maybe build a small example (if it works)

**Comment by raidwas** [comment]
[WIP](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=aa6fbf435cd0d28969f8b2617e0a43a6)

Most notable difference with your example given is that it does not take a closure but the Element directly. I couldn't get it to work with the closure as the closure required a mutable reference to self resulting in some weird lifetime issues.

Another difference is, that the message type of the header and the body don't have to be the same and therefore are inserted into an enum which contains either one.

**Comment by raidwas** [comment]
Streamlined it a bit: [WIP](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4af92d0c56d46193654574b27198e3b2)

Removed one of the generic parameters of `collapsible::Message`, replacing it with a simple `Toggle` variant. The generic parameter was only needed in my example because I thought I needed it in order to get the index of the list (I was wrong)

**Comment by hecrj** [comment]
Thanks for sharing! These are cool!

> I couldn't get it to work with the closure as the closure required a mutable reference to self resulting in some weird lifetime issues.

The closure was meant to avoid creating the collapsible contents unnecessarily (a lazy view of sorts). You should be able to get around the lifetime issue with a `FnOnce`: https://gist.github.com/rust-play/90175d29986fdf46a04aaaefc137645d

> Would you like to have something like this inside the library? As seen its possible to build it with everything it already provides, but it might be usefull to have some predefined components that can easily be used.

I'd prefer to keep a narrow scope and focus on building reusable primitives for the time being.

That said, I have put quite a bit of effort into allowing users to create and share custom widgets, subscriptions, and components like this one. I'd love to see users create their own crates to share their ideas on top of `iced`. 

Thus, I think there is a lot of potential when it comes to extending the library for particular use cases. Not everything needs to be a part of the main library to be useful to others!

**Comment by raidwas** [comment]
> The closure was meant to avoid creating the collapsible contents unnecessarily (a lazy view of sorts). You should be able to get around the lifetime issue with a `FnOnce`: https://gist.github.com/rust-play/90175d29986fdf46a04aaaefc137645d
That worked, thanks :)

> That said, I have put quite a bit of effort into allowing users to create and share custom widgets, subscriptions, and components like this one. I'd love to see users create their own crates to share their ideas on top of `iced`.
> 
> I think there is a lot of potential when it comes to extending the library for particular use cases. Not everything needs to be a part of the main library to be useful to others!

In that case I think this question can be marked as closed :)

**Comment by wgxh-cc** [comment]
Imagine that you hide a large content which takes time to render, and when displaying it, users may see a delay between two views.

How to solve this?
