### ISSUE TITLE
winit event should not be moved

### ISSUE THREAD

**Issue by aentity** [hecrj/iced#238]
`iced_winit::conversion::window_event` requires event to be moved, but winit event is no longer clone.
Can you relax condition, and take by reference?

**Comment by hecrj** [comment]
I think this is reasonable. #239 should fix the issue.

What are you doing with the `winit` event after converting it to an `iced` one?

**Comment by aentity** [comment]
I can't do anything currently; but I had to change entire event processing loop (which did not take owned event). It means iced must be last one to process event; but perhaps if i handle event then I don't want to send to iced, e.g., camera pans, for example.

Also if everyone who uses events took owned, it won't work :)

**Comment by aentity** [comment]
wonderful, thanks so much!

**Comment by aentity** [comment]
Yes i've tested this and svg path and works and is great ergonomic improvement, thank you!
