### ISSUE TITLE
Dynamic Window Title

### ISSUE THREAD

**Issue by U007D** [hecrj/iced#244]
I integrated `coffee` into my application, and now I am giving `iced` a test drive as well.  Nice work!

I noticed a small difference between the frameworks: `iced` has the window title set by a a `title()` method defined in the `Application` trait (`coffee` has this in the `WindowsSettings` type that is passed into `run()`).

The [`iced::Application::title()` documentation](https://docs.rs/iced/0.1.0-beta/iced/trait.Application.html#required-methods) says:
> This title can be dynamic! The runtime will automatically update the title of your application when necessary.

but it's not clear to me how I could update the title dynamically or even just set it to a value depending on conditions at `run()` time.  Could you provide a quick example?

**Comment by hecrj** [comment]
It works like `view`, you simply return the `title` for the current state of your application. The [`tour`](https://github.com/hecrj/iced/blob/5b2c71a708f907f2b3c73bcdf56fbca5cd80adde/examples/tour) example does it here:

https://github.com/hecrj/iced/blob/5b2c71a708f907f2b3c73bcdf56fbca5cd80adde/examples/tour/src/main.rs#L34-L36

**Comment by U007D** [comment]
In my case I want to pass state in from my builder at construction time.  I don't know how to inject, say a value my builder has parsed from the command line into the `Application` instance state, since `Application::run()` appears to create its own `Application` instance.  Perhaps I don't have the right mental model?

**Comment by U007D** [comment]
Perhaps an example would help.  With `coffee` my builder injected initial state through `run()`:
```rust
    // Builder impl ...
    fn build(self) -> Result<Self::WindowImpl> {
        Ok(Window {
            size: self
                .size
                .unwrap_or_else(|| sd_to_rect_size(&ScreenDimension::Quarter)),
            size_state: self
                .window_size_state
                .unwrap_or_else(|| WindowSizeState::IntermediateResizable),
            title: self
                .title
                .unwrap_or_else(|| app_name().unwrap_or_else(|| String::from(msg::UNTITLED))),
        })
    }
```

But in `iced`, the `title` field is not available in `WindowState`.  How should I inject initial conditions?

**Comment by hecrj** [comment]
This is planned, but not possible currently. See #118 for more details.

**Comment by U007D** [comment]
Ah, good to know, thank you.

**Comment by hecrj** [comment]
Could you share some details about your particular use case? I gather the title of the application depends on some argument provided to the executable?

I will try to get this sorted in the next day or so.

**Comment by U007D** [comment]
In my case, I am providing information provided by the user on the command line (the start co-ordinates & zoom factor of a Mandelbrot zoom) in the title bar as information.

In general I would like to be able to pass custom state into `run()`, have that fed to `Application::new()`, and my `new()` impl would parse the object and populate the `Application` fields of my impl.  This would allow me to set the initial conditions but maintain the run time isolation of the current model (ie. no globals).

**Comment by hecrj** [comment]
> I am providing information given to me by the user via the command line (the start co-ordinates & zoom factor of a Mandelbrot zoom) in the title bar as information.

Any specific reason why you can't ask for this information using widgets?

> In general, I would like to be able to pass custom state into run(), have that fed to Application::new()

Yes, this is what I plan to implement with a `Flags` associated type.

**Comment by U007D** [comment]
> Any specific reason why you can't ask for this information using widgets?

In this case, I do not plan to interrogate the user once the experience has been invoked.  But in general, as part of a larger solution, I may need to inject initial state like keys, tokens, etc. programatically which would allow an `iced`-based solution UX to be pre-populated with all the right answers for the user, for example.

**Comment by hecrj** [comment]
I just opened #246, which should allow you to provide any kind of initial state to `Application::new`. Let me know what you think.

**Comment by U007D** [comment]
Yep, that looks perfect, thank you for the quick turnaround! :bowing_man:

**Comment by U007D** [comment]
I *may* have spoken too soon! :)  In test driving the new API, I'm finding it does not compose very well.

I am loosely coupling `iced` to my application.  I would instantiate the application using the Builder pattern to ensure the configuration options from my domain API never constitute an invalid or unsupported combination of features in the dependency.

I would like to encapsulate `iced::Settings` into my struct  along with additional fields that my `Application::new()` constructor will understand and utilize, but `iced::Settings<Flag>` wants to encapsulate *my* settings.  This is causing a headache with the borrow checker, because, for example the `Flag` field needs to be used both to initialize the `iced::window::Settings`, as well as for my own fields.  Extracting my non-`Copy` fields from the `iced::Settings` beforehand invalidates it.  So there is a lot of `Clone`ing, `Option::replace()`ing and otherwise superfluous `Copy` derives to work around these issues.

FYI, it would have been nicer for `iced::Settings` to have been oblivious to `Application::Flags` (since, by definition, that field is opaque to `iced`).  If I wanted to augment what was passed in, I would simply set my `Flags` associated type to my encapsulating type, and I would do the work within `Application::new()` to destructure everything and provide a proper `iced::Settings` (on pain of compile failure).  As it stands, there's a wrestling match where `iced::Settings` insists of encapsulating my private type, and (for reasons stated above) it would be far preferable to my type to encapsulate `iced::Settings`.

**Comment by hecrj** [comment]
`iced::Settings` isn't really meant to be composable. It's mostly an explicit struct for providing arguments to `Application::run`.

I believe you should store your settings in your own preferred data structure and only map it to `iced::Settings` when calling `Application::run`.
