### ISSUE TITLE
Why is Layout::new() and Layout::with_offset not exposed publicly

### ISSUE THREAD

**Issue by jordanbray** [hecrj/iced#264]
I am trying to implement a container type (which will allow different styles of layouts), but it is not possible to do this in an external crate, because `Layout::new()` is not exposed.  Is there a reason for this?

**Comment by hecrj** [comment]
`Layout::new` is only used internally in `UserInterface`.

Currently, if you are implementing a custom widget, you should return the appropriate `layout::Node` in `Widget::layout`. You will get back the according `Layout` in `on_event` and `draw`.
