### ISSUE TITLE
Is it currently possible to create a (semi-)transparent window on native platforms?

### ISSUE THREAD

**Issue by oliver-moeller** [hecrj/iced#272]
I am currently working on a fullscreen overlay on Windows.
There are a few things I am still trying to figure out. That includes:
- most importantly: making a window transparent and / or semi-transparent while keeping it's widgets visible (maybe through iced_native or iced_winit?)
- starting a window in fullscreen mode
- getting the window handle (that is specifically the hwnd in Windows)

If anybody could lend a hand, thank you very much!

**Comment by hecrj** [comment]
> making a window transparent and / or semi-transparent while keeping it's widgets visible

This is not possible yet, but I believe it should be a matter of adding a `transparent` setting to `window::Settings` ([`winit` supports this](https://docs.rs/winit/0.22.0/winit/window/struct.WindowBuilder.html#method.with_transparent)) and then clearing the frame with a transparent background color when the option is enabled.

> starting a window in fullscreen mode

Returning `Mode::Fullscreen` in `Application::mode` should do the trick. However, we need to rethink this design. The mode can currently fall out of sync with the actual window state.

>  getting the window handle

What would be the use case for this?

---------

You could achieve all of this by building your event loop on top of `winit` directly. The [`integration` example](https://github.com/hecrj/iced/tree/master/examples/integration) showcases how to do this.

**Comment by oliver-moeller** [comment]
I am unsure whether Linux and Mac would achieve anything by it, but under Windows it would allow access to a lot of features in the winapi, which are not currently implemented in iced (e.g. transparency).

**Comment by myfreeweb** [comment]
Please reopen the issue, this feature is generally useful and is not implemented.

So actually, wgpu doesn't support window transparency yet: https://github.com/gfx-rs/wgpu/issues/687

But I guess that's not an issue with the GL backend.

> should be a matter of adding a transparent setting to window::Settings

I'll try implementing that.

**Comment by maroider** [comment]
The assumption made about `with_transparent` being unnecessary in 0fdc4e0 does not hold true for me (on Windows 10). Transparency refuses to work for me until I add `.with_transparent(true)` [here](https://github.com/hecrj/iced/blob/a0cc7e4e43f16de4c19607f913b7f587c61aa5ef/winit/src/settings.rs#L67-L73).

**Comment by atsuzaki** [comment]
> The assumption made about `with_transparent` being unnecessary in [0fdc4e0](https://github.com/hecrj/iced/commit/0fdc4e06502efdc345a00bfe1806c116971ffed5) does not hold true for me (on Windows 10). Transparency refuses to work for me until I add `.with_transparent(true)` [here](https://github.com/hecrj/iced/blob/a0cc7e4e43f16de4c19607f913b7f587c61aa5ef/winit/src/settings.rs#L67-L73).

Can confirm it refuses to work on MacOS without `.with_transparent(true)` as well.

> should be a matter of adding a transparent setting to window::Settings
I can open a PR to add this, but I'm not too sure since wgpu still doesn't support it. Maybe I could just add a note for people to switch to GL if they need transparency? cc: @hecrj

**Comment by hecrj** [comment]
@atsuzaki Sounds good. No need to worry about `wgpu` for now. Once it's supported, it shouldn't affect the public API.
