### ISSUE TITLE
Next button on demo does not work

### ISSUE THREAD

**Issue by TitusEntertainment** [hecrj/iced#273]
![image](https://user-images.githubusercontent.com/16852656/78705570-f75fae00-790d-11ea-81cc-5659ec7cb7a2.png)

pressing the next button does not work on Firefox Developer Edition Linux (manjaroo)

**Comment by hecrj** [comment]
Do you have any browser plugins that may be changing the DOM? Try disabling them.

**Comment by TitusEntertainment** [comment]
Weird. I didn't change a thing and now it worked after a reboot :thinking:

**Comment by leo60228** [comment]
Never mind, it was Dark Reader.
