### ISSUE TITLE
Question: Reuse parts of iced for another GUI framework prototype

### ISSUE THREAD

**Issue by Phaiax** [hecrj/iced#274]
Hi hecrj

I had some thoughts about how a GUI framefork would look like for me and wanted to prototype it. (Basically a bit like WPF, with a Designer to create a widget tree and otherwise very old school. Not aiming for top performance or minimal memory footprint.)

Can I take parts of iced to make this prototype? 

Thanks,
Daniel

**Comment by hecrj** [comment]
Hi @Phaiax, 

It's hard to say without more details. You need to keep in mind that iced is based on The Elm Architecture, and this affects most of its API.

If your idea of a toolkit doesn't fit the Elm paradigm to some extent, then you will most likely have a hard time making `iced_native` fit your use cases.

If your idea fits The Elm Architecture, then I think the [`integration` example] can be a good starting point to build further abstractions (i.e. your own library on top of iced, your `Application` trait, etc.).

**Comment by Phaiax** [comment]
Sorry, i misformualted the question
I wanted to know if i can so to say "steal" parts your source code and not ask if it is possible.

But I tried a bit yesterday and the architecture is too different I now believe.
And better to start from something simple.

Thanks,
Daniel

**Comment by hecrj** [comment]
@Phaiax All the code is under [the MIT License](https://github.com/hecrj/iced/blob/master/LICENSE).
