### ISSUE TITLE
Memory leak on mac

### ISSUE THREAD

**Issue by pbspbsingh** [hecrj/iced#275]
Noticed a lot of memory leak while running any example app on my macbook. 
Attaching `Leaks` screenshots for `todo` example: 
<img width="1287" alt="Screen Shot 2020-04-07 at 6 17 07 PM" src="https://user-images.githubusercontent.com/7175265/78734043-06d5fb80-78fc-11ea-8948-8ebe6f696286.png">

**Comment by hecrj** [comment]
Hey, thanks for testing!

I am not an expert on this, but I don't think the codebase has many instances where memory leaks can happen (no `unsafe`, no `std::mem::forget`, no cycles of shared references).

I believe [`wgpu`](https://github.com/gfx-rs/wgpu-rs) may have fixed memory leaks in [the latest release](https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md). It may be interesting to run the tests with the updated `iced_wgpu` version in #269.

**Comment by hecrj** [comment]
I just investigated a bit and `wgpu` does not seem to be leaking any memory. Instead, I believe I ended up finding a memory leak in `winit` when cloning a proxy (which iced does quite a bit).

I have reported the issue: https://github.com/rust-windowing/winit/issues/1525

**Comment by pbspbsingh** [comment]
Thanks for investigating and submitting the PR to `winit` 🙏🏽

**Comment by hecrj** [comment]
Closing as the fix was merged and landed in the `0.22.2` release of `winit`.
