### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Cyperwu** [hecrj/iced#276]
The example in current README.md does not comply to the code of the Counter example, please update.

**Comment by hecrj** [comment]
I don't believe it needs any updating. Could you elaborate?

The overview in the `README` is meant to be a quick introduction to the architecture and ideas the library is built on.

The [documentation of the `Application` trait] goes into a lot more detail and provides a full example.

**Comment by Cyperwu** [comment]
@hecrj The sample code in the `README` is brief, but it's not complete.

In fact, the counter example uses `Sandbox` trait to give a quick and simple demo, and which is also recommended in the docs.

But in the `README`, you didn't `impl` `Application` or `Sandbox`, which may lead to some level of confusion.

Also, on line 114 of the `README`, the `view` method returns `Column` instead of `Element`. It may imply that this piece of code belongs to a part of a bigger application, but not an `Hello World` that can be easily run through.

Maybe using the hello world code sample in the `Sandbox` documentation would be better?

**Comment by hecrj** [comment]
> The sample code in the README is brief, but it's not complete.

It's not meant to be complete. It's an overview; an introduction that focuses on the different concepts of The Elm Architecture.

> you didn't impl Application or Sandbox, which may lead to some level of confusion.

These traits are not the only way to use the library.

> Also, on line 114 of the README, the view method returns Column instead of Element. It may imply that this piece of code belongs to a part of a bigger application, but not an Hello World that can be easily run through.

It does say overview instead of full example, though...

> Maybe using the hello world code sample in the Sandbox documentation would be better?

The counter example works well to introduce the concepts because it is interactive and very simple.

**Comment by Cyperwu** [comment]
Alright then, I understand your concept. Thanks for your time!
