### ISSUE TITLE
iced_native::input::mouse::Event::CursorLeft not emitted when the cursor leaves the window

### ISSUE THREAD

**Issue by Plecra** [hecrj/iced#287]
- Platform: Windows
- `iced_native` version: 0.2.0

When the cursor leaves the window, buttons will continue to display their drop shadow, instead of reacting to the cursor leaving.

![image](https://user-images.githubusercontent.com/60934058/79047379-1c099d80-7c0e-11ea-8bde-acd5a9c6cf4c.png)

**Comment by hecrj** [comment]
You are right. Thanks for reporting!

I have implemented a fix in #289.
