### ISSUE TITLE
New `Flags` associated type should also be on Sandbox

### ISSUE THREAD

**Issue by U007D** [hecrj/iced#291]
IIUC, given the difference between `Sandbox` and `Application` is asynchrony, should the new custom initialization associated type `Flags` be on `Sandbox` as well?

The recommendation to start with `Sandbox` and move to `Application` when asynchrony is needed is difficult when the ability to initialize with user settings requires `Application`.

**Comment by hecrj** [comment]
`Sandbox` is meant to be a trait to get you started with the library really quickly. I'd prefer to keep it simple.

But I agree we should probably mention the differences with respect to flags support in the documentation.
