### ISSUE TITLE
Resizing `PaneGrid` panes by dragging splits without modifier keys

### ISSUE THREAD

**Issue by dlzawap** [hecrj/iced#297]
Resizing of `Pane grid` doesn't work on Ubuntu 19.10.
![Peek 2020-04-14 21-35](https://user-images.githubusercontent.com/54396152/79266477-e8da3f00-7e97-11ea-8ed8-b8ebafd5d3dc.gif)

Some additional information:
cargo 1.42.0 (86334295e 2020-01-31)
rustc 1.42.0 (b8cedc004 2020-03-09)

AMD Ryzen 3700x
Nvidia RTX 2060

**Comment by hecrj** [comment]
Resizing currently works by holding `Ctrl + Right click` to snap the closest split to the mouse position.

I am aware this is not completely intuitive and we should allow resizing panes by dragging the splits directly.

**Comment by TomPridham** [comment]
does PageGrid need to be implemented for web or is it not necessary?

**Comment by hecrj** [comment]
@TomPridham Yes, it does! `PaneGrid` is only available in native platforms currently.

Overall, [`iced_web` needs a lot of improvements](https://iced.zulipchat.com/#narrow/stream/213445-help/topic/web.3A.20scrollable.20stylesheet).

**Comment by hecrj** [comment]
This was fixed by #397!
