### ISSUE TITLE
Image Zoom & Pan

### ISSUE THREAD

**Issue by tarkah** [hecrj/iced#306]
I've searched here and Zulip and couldn't find any relevant discussion.

Are there plans to implement a widget to allow zooming in on an Image (past the dimensions of the parent element / application window) and panning?

**Comment by hecrj** [comment]
I think a widget for this would be great.

It shouldn't be too hard:
- Listen to mouse events on `Widget::on_event`. Zoom with the scroll wheel, pan by dragging.
- Draw using a scaled `Image` inside a `Clip` primitive with the correct offset.

**Comment by tarkah** [comment]
Yes, that'd be perfect! Hmm, I may try taking a look this week to see if this is something I could figure out.

**Comment by tarkah** [comment]
@hecrj How would you go about "scaling" the `Image`? I created a widget called `ImagePane` that takes a `State` and an `Image`. I'm comfortable with tracking an offset / scale factor in the `State` when an event occurs, but I'm not familiar enough with the API to know where and how to apply that scale factor to change the dimensions of the `Image`. Thanks!

**Comment by tarkah** [comment]
Even if I try to manually scale the image before passing it to `ImagePane`, I can't seem to set `Length::Units` greater than the actual dimensions for the image.

**Comment by tarkah** [comment]
Another issue I can't seem to work around... I have panning working great when the inner image is aligned to the top left corner. If I try to align the image to the center, I can't set a negative offset to the `Clip` primitive to pan to the left side of the image, since the alignment pushes it negative of the `ImagePane`'s (0,0) bounds.

I'll go ahead an open the PR so you can get your eyes on this to make it easier to see what I am referencing.

**Comment by hecrj** [comment]
I wouldn't use the `Image` widget internally. You should be able to directly produce an `Image` _primitive_ with any bounds instead.

> I can't set a negative offset to the Clip primitive

I see. We should probably change the `Clip` offset to support negative values too. I'll try to explore this.

**Comment by tarkah** [comment]
Ahh, that's what I was missing. Thanks!
