### ISSUE TITLE
Copying and pasting?

### ISSUE THREAD

**Issue by TJRoh01** [hecrj/iced#310]
I can not seem to find anything regarding implementing copying and pasting on native apps. I would really appreciate if someone could point me to an example or documentation for that.

Thanks!

**Comment by hecrj** [comment]
I just commented in a similar issue: https://github.com/hecrj/iced/issues/295#issuecomment-617297365

I am closing this in favour of that one.

**Comment by TJRoh01** [comment]
> I just commented in a similar issue: [#295 (comment)](https://github.com/hecrj/iced/issues/295#issuecomment-617297365)
> 
> I am closing this in favour of that one.

NP! Thank you for your anwser.
