### ISSUE TITLE
High memory usage on Windows

### ISSUE THREAD

**Issue by fwcd** [hecrj/iced#328]
First of all, thanks for making this amazing crate! Having a modern GUI library is definitely a great step forward towards building desktop applications in Rust.

I've noticed though that the default renderer on Windows allocates very large amounts of memory (sometimes even causing the app to crash), specifically when clicking and dragging with the mouse:

![demo](https://user-images.githubusercontent.com/30873659/80775193-3aa0eb80-8b5f-11ea-9a38-4c32b6d1d1ee.gif)

Any ideas on this?

**Comment by hecrj** [comment]
Do the [`wgpu-rs` examples](https://github.com/gfx-rs/wgpu-rs) display the same issue for you? Are your (integrated) graphics drivers up-to-date? Does it happen only when selecting text?

[`gfx-memory` recently fixed some issues](https://github.com/gfx-rs/gfx-extras/blob/master/CHANGELOG.md). You could try running `cargo update`.

In any case, I don't believe we have code that could cause the renderer to leak or allocate memory like that.

**Comment by fwcd** [comment]
Yeah, I am running the latest graphics drivers and have the newest library versions too.

I did some quick profiling of the app in Visual Studio (while selecting text, just as in the GIF above) and found that it spends most of its time in the event loop, drawing:

![grafik](https://user-images.githubusercontent.com/30873659/80808936-ec243900-8bc0-11ea-9e31-9bdaae51c82e.png)

![grafik](https://user-images.githubusercontent.com/30873659/80808995-137b0600-8bc1-11ea-9177-a17b9df90ebc.png)

Maybe the app enqueues too many events and thereby overloads the queue since the loop cannot keep up?

**Comment by hecrj** [comment]
> Maybe the app enqueues too many events and thereby overloads the queue since the loop cannot keep up?

I think this is unlikely. The queue is drained before drawing every time and we are not seeing increased latency. Does the memory usage decrease once you stop moving the mouse?

It would help me if you could answer my other questions:

- Do the [`wgpu-rs` examples](https://github.com/gfx-rs/wgpu-rs) display the same issue for you?
- Does it happen only when selecting text?

And additionally:

- What is your GPU? Does it support Vulkan?

**Comment by fwcd** [comment]
None of the examples (neither here, nor in `wgpu`) produced the issue, so I tried upgrading from `iced 0.1.x` (the most recent release) to the latest `master` of `iced` and that solved the problem. Maybe it was indeed one of the recent `gfx-extras` fixes.

Thank you!

**Comment by sum-elier** [comment]
I am having the same problem with the TODO example. I am on Windows 10 Pro build 1909. My GPU is Asus Strix GTX 970.

**Comment by sum-elier** [comment]
@fwcd Can you please reopen the issue since I am experiencing the same problem using the latest Iced version 😟

**Comment by hecrj** [comment]
@sum-elier

- Do the wgpu-rs examples display the same issue for you?
- Does it happen only when selecting text?

**Comment by fwcd** [comment]
@sum-elier I'm sorry, I don't see the issue in your demo. This memory usage looks pretty normal to me.

**Comment by sum-elier** [comment]
@fwcd I am sorry, you are right. I was looking at the cpu usage though. I guess that is normal then?

**Comment by sum-elier** [comment]
> 
> 
> @sum-elier
> 
>     * Do the wgpu-rs examples display the same issue for you?
> 
>     * Does it happen only when selecting text?

As @fwcd pointed out, my memory usage is alright. I was confused and was looking at the cpu usage. Tried the demos from wgpu-rs (cube and hello-triangle) and they seem to consume around 31% of cpu so I guess what I saw here is normal

**Comment by hecrj** [comment]
@sum-elier Are you running in `release` mode?

We currently redraw at every loop iteration, even if not necessary (see #241). CPU usage should decrease once we tackle that.

**Comment by sum-elier** [comment]
@hecrj Yes, `run --package todos --bin todos --release`
