### ISSUE TITLE
add widget trait to easily see what needs to be implemented?

### ISSUE THREAD

**Issue by clawoflight** [hecrj/iced#330]
It would be nice to add a widget trait for discoverability.
It took me a while to figure out what exactly needs implementing in order to create composable widgets - the Application trait was very useful, I would like something similar.

**Comment by hecrj** [comment]
There is [a `Widget` trait in `iced_native`][1].

[1]: https://docs.rs/iced_native/0.2.2/iced_native/widget/trait.Widget.html

**Comment by clawoflight** [comment]
Thank you! It's a bit hard to find the stuff in iced_native when I spend most of my time with the docs of iced.

**Comment by hecrj** [comment]
Agreed. Custom widgets are currently a feature for advanced users, so they are a bit hidden.

I hope to tackle some of these topics eventually in an `iced` tutorial/guide/book/blog.

**Comment by clawoflight** [comment]
Sounds good! I hope I'll find out when you get around to it :)
