### ISSUE TITLE
Application fails with libX11 not found

### ISSUE THREAD

**Issue by matthiasbeyer** [hecrj/iced#333]
Hi,

I just wrote a small thing and it fails with

```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })', <::std::macros::panic macros>:2:4
```

I confirmed that the "todos" example fails with the exact same error message.

What confuses me: I do not run wayland on this machine. I run X11 with i3, nothing special there.

Maybe relevant: I do run NixOS, which might be responsible for the failure to find libX11.so, but I'd doubt it because other libraries are normally found.

**Comment by matthiasbeyer** [comment]
Fixed it: I had to put `libX11`, `libXcursor`, `libXrandr` and `libXi` into my shell environment!

**Comment by hecrj** [comment]
Thanks for the report! We'll keep it in mind for #256.

**Comment by matthiasbeyer** [comment]
Thanks. I still have the issue that on my device, vulkan does not seem to work, so iced is not for me I guess, but glad I could contribute something nonetheless!
