### ISSUE TITLE
Variable layout lag and artifacts during resize on integrated graphics

### ISSUE THREAD

**Issue by aevyrie** [hecrj/iced#339]
Building an iced app on a device with an nVidia GPU, results in a strange lag during resize, which I do not see on another device with an AMD GPU. Not sure if GPU is root cause, but seems like an important distinction.

What I'm seeing is some of the widgets updating layout faster than others, and more prominently, it seems like text layout is lagging behind the rest of the widgets.

Here is a screenshot during resize:
![image](https://user-images.githubusercontent.com/2632925/81602451-7fa7f780-9381-11ea-88a9-8cbdebfd3899.png)

This may be some text layout related bug, I often get large text artifacts during resize like this:
![image](https://user-images.githubusercontent.com/2632925/81602830-268c9380-9382-11ea-8f48-356e39b729a6.png)

Again, these issues only seem to happen on the device with the nVidia GPU. After the screen resize is complete, the layout seems to catch up, and everything looks normal.

**Comment by joshirio** [comment]
I have similar artifacts, especially as shown in your 2nd screenshot on an integrated intel GPU

**Comment by aevyrie** [comment]
This appears to be related to antialiasing. With antialiasing enabled the artifacts are gone.

**Comment by aevyrie** [comment]
Interestingly, enabling AA seems to force the renderer to use the discrete GPU (task manager shows GPU switch), the issue seems to lie with the renderer using the integrated graphics. The difference between the two systems probably has to do with the nVidia software that controls whether applications are rendered by discrete/integrated.

**Comment by hecrj** [comment]
These artifacts are most likely a graphics driver issue (see #172). Are they up-to-date?

**Comment by aevyrie** [comment]
Updating the drivers did not fix this. I tried updating the intel and nvidia drivers through the device manager, and restarted.

Strangely though, I've noticed that otherwise, performance is actually _better_ in some respects in this glitchy state. The top and left edges of controls are _comletely_ stationary, none of the [jelly effect](https://raphlinus.github.io/rust/gui/2019/06/21/smooth-resize-test.html) I normally see during window resize. Maybe there is something to be learned from this bug?

**Comment by aevyrie** [comment]
Welp, for some reason there was an update available today for the intel graphics, and that seemed to fix the issue.

It's really odd that performance is so good on integrated graphics though, it runs better than it does on a more powerful discrete GPU - no lag or jelly. 😕

**Comment by hecrj** [comment]
@aevyrie Vsync may be involved in what you are experimenting.

**Comment by aevyrie** [comment]
@hecrj That's a good idea. I haven't noticed any tearing when running on integrated though. I'll try and force vsync off for the application in the driver.

**Comment by aevyrie** [comment]
@hecrj any ideas how to troubleshoot this further? I haven't had any luck in the driver settings forcing vsync off. It happens on both systems I have access to, with nvidia and amd cards. The only way I've found to fix it is when using the integrated intel gpu. Maybe it's happening in winit or wgpu? What I've read seems to suggest it's to do with the gui and gpu aren't synced.

**Comment by hecrj** [comment]
@aevyrie I am not exactly sure what is the problem you are having.

Are you talking about smooth window resizing? Do the [`wgpu' examples](https://github.com/gfx-rs/wgpu-rs/tree/v0.5) have the same issue?

**Comment by aevyrie** [comment]
The problem is smooth resizing only working on the integrated gpu. On the dedicated gpus, there is some gui layout lag during resize that gives a "jelly" effect. I can give the wgpu examples a try.

**Comment by aevyrie** [comment]
@hecrj It looks like this is present to some degree in the `wgpu` examples. It's difficult to say though because it's so hard to quantify.
