### ISSUE TITLE
Examples panic at runtime

### ISSUE THREAD

**Issue by DominosCinnaStix** [hecrj/iced#341]
Running the example `styling` results in the follow

The back trace can be found here https://pastebin.com/63ESmAMy.

OS: Windows 10 Pro version 1909 (build 18363.815) 64 bit
Graphics: Intel(R) HD Graphics, driver version: 9.17.10.4459

**Comment by hecrj** [comment]
Do the [`wgpu` examples][1]  work for you?

As far as I know, the DirectX 11 backend for `wgpu` still has some rough edges. You should try to use DirectX 12 if possible.

[1]: https://github.com/gfx-rs/wgpu-rs/tree/v0.5

**Comment by DominosCinnaStix** [comment]
So I've tested all of the examples and they all worked except the `hello-compute` example.

**Comment by DominosCinnaStix** [comment]
After modifying [the line for selecting a backend](https://github.com/hecrj/iced/blob/df157ef616bd655e91eb71b0547bb83df90eb649/wgpu/src/window/backend.rs#L27) to `wgpu::BackendBit::DX12` the examples successfully run using the PCs virtual GPU!

I forgot to have mentioned in the original post that the PC I'm running it on does not have a dedicated GPU.

**Comment by hecrj** [comment]
We should change that line to use [`wgpu::BackendBit::PRIMARY`](https://docs.rs/wgpu/0.5.0/wgpu/struct.BackendBit.html#associatedconstant.PRIMARY), as DX11 and OpenGL are not well supported yet.

**Comment by DominosCinnaStix** [comment]
Sure! Should the PR target both the master and v0.1 branch?

**Comment by hecrj** [comment]
Just `master`. We can cherry-pick later.
