### ISSUE TITLE
Canvas examples on MacOS don't work

### ISSUE THREAD

**Issue by andrewmh20** [hecrj/iced#342]
0.1.1 seems to have broken the Canvas widget on Mac OS. When trying to run the clock, solar_system, bezier_tool examples on MacOS 10.14.6 get a blank, white, screen where I believe the Canvas is supposed to be. Running game_of_life presents a gray screen, and all the surrounding menu components but does not show any of the white "cell" pieces.

Manually switching to the 0.1 branch and testing the ones that exist there seems to work fine.

**Comment by andrewmh20** [comment]
Realizing it’s possible I confused which code was which release/under development.
Is the current code in branch 0.1 the 0.1.1 release? 
In that case, this is only a bug in the unreleased code on master, which can be expected-though still worth noting.

**Comment by hecrj** [comment]
I can't seem to reproduce the issue on macOS 10.15.3. The examples work as intended, even after a `cargo update`.

> Is the current code in branch 0.1 the 0.1.1 release?

Yes, that's correct.

> In that case, this is only a bug in the unreleased code on master

We upgraded `wgpu` in `master` (see #269), which I believe could be the cause of the issue. Unfortunately, it's going to be hard for me to debug it without being able to reproduce it.

- Do all the [`wgpu` examples](https://github.com/gfx-rs/wgpu-rs/tree/v0.5/examples) work for you?
- Do the `iced` examples work at https://github.com/hecrj/iced/commit/b44f14e1863d251cc960a6252c8d0110f3062215?

**Comment by andrewmh20** [comment]
> Do all the wgpu examples work for you?
Yes they do seem to work
> Do the iced examples work at b44f14e?
No, they fail in the same way.

**Comment by andrewmh20** [comment]
Okay I did some searching, 99e020c seems to break it

**Comment by hecrj** [comment]
What happens if you disable `antialiasing`?

https://github.com/hecrj/iced/blob/7565d294afd668cc95d85f15662d0704962c9614/examples/clock/src/main.rs#L9

**Comment by andrewmh20** [comment]
That does it! With antialiasing off the clock works.

**Comment by hecrj** [comment]
Ok! Does the [`msaa-line` example](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/msaa-line) work for you? You can press left and right to change the MSAA factor.

**Comment by andrewmh20** [comment]
Ahhh nope. It loads and I get a panic when I press left or right. Don't think I realized there was more to it than just getting the image to show up when I tested above.

Here's a backtrace:

`thread 'main' panicked at 'Attachment sample_count must be supported by physical device limits', <::std::macros::panic macros>:2:4
stack backtrace:
   0: std::io::Write::write_fmt
   1: core::ptr::drop_in_place
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::begin_panic
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/panicking.rs:397
   7: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass
             at ./<::std::macros::panic macros>:2
   8: wgpu::backend::direct::<impl wgpu::Context for wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::encoder_end_render_pass
             at src/backend/direct.rs:870
   9: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at src/lib.rs:1534
  10: core::ptr::drop_in_place
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libcore/ptr/mod.rs:177
  11: <msaa_line::Example as msaa_line::framework::Example>::render
             at examples/msaa-line/main.rs:265
  12: msaa_line::framework::run_async::{{closure}}::{{closure}}
             at examples/msaa-line/../framework.rs:147
  13: <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/liballoc/boxed.rs:1024
  14: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/macos/app_state.rs:71
  15: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/macos/app_state.rs:172
  16: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/macos/app_state.rs:330
  17: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/macos/observer.rs:135
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <() as objc::message::MessageArguments>::invoke
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  29: objc::message::platform::send_unverified
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  30: objc::message::send_message
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  31: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at ./<::objc::macros::msg_send macros>:15
  32: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/platform_impl/macos/event_loop.rs:89
  33: winit::event_loop::EventLoop<T>::run
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.1/src/event_loop.rs:149
  34: msaa_line::framework::run_async::{{closure}}
             at examples/msaa-line/../framework.rs:104
  35: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/future.rs:44
  36: futures_executor::local_pool::block_on::{{closure}}
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  37: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  38: std::thread::local::LocalKey<T>::try_with
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/thread/local.rs:262
  39: std::thread::local::LocalKey<T>::with
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/thread/local.rs:239
  40: futures_executor::local_pool::run_executor
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  41: futures_executor::local_pool::block_on
             at /Users/tzvi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  42: msaa_line::framework::run
             at examples/msaa-line/../framework.rs:169
  43: msaa_line::main
             at examples/msaa-line/main.rs:272
  44: std::rt::lang_start::{{closure}}
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/rt.rs:67
  45: std::panicking::try::do_call
  46: std::sys_common::thread_info::THREAD_INFO::__getit
  47: std::sys_common::util::report_overflow
  48: std::rt::lang_start
             at /private/tmp/rust-20200509-87658-187po7x/rustc-1.43.1-src/src/libstd/rt.rs:67
  49: msaa_line::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

**Comment by andrewmh20** [comment]
Seems to be the same as this issue: https://github.com/gfx-rs/wgpu-rs/issues/91

**Comment by hecrj** [comment]
The `msaa-line` example starts with a `sample_count` of `4`, which is the same amount we are using in `iced_wgpu` when `antialiasing` is enabled.

If it works for you until you press left or right, then `iced` should work too.

**Comment by andrewmh20** [comment]
Hmm yeah I see msaa-line starts at 4, but then whether I go to 2 or 8 it panics.
`Press left/right arrow keys to change sample_count.
sample_count: 4
sample_count: 8
thread 'main' panicked at 'Attachment sample_count must be supported by physical device limits', <::std::macros::panic macros>:2:4
`

**Comment by hecrj** [comment]
Yes, that's more or less expected.

When you run `game_of_life`, do you see the background of the buttons?

![image](https://user-images.githubusercontent.com/518289/81781093-e3ecc780-94f7-11ea-8bd9-95034f56a6fa.png)

**Comment by andrewmh20** [comment]
I do not.
<img width="1024" alt="Screen Shot 2020-05-13 at 3 01 16 AM" src="https://user-images.githubusercontent.com/1943441/81781549-488f2e80-94c6-11ea-82d2-3cd20739e818.png">

(and for the record, turning of antialiasing here also solves the problem)

**Comment by hecrj** [comment]
This is probably a bug in [the blit `msaa` pipeline](https://github.com/hecrj/iced/blob/7565d294afd668cc95d85f15662d0704962c9614/wgpu/src/triangle/msaa.rs).

I double checked the shaders and the logic, and I am not sure what could exactly be causing it. It works on my MacBook and my desktop with Linux and Windows.

**Comment by andrewmh20** [comment]
Oh I thought you were referring to the little white squares.

Today is pretty much the first time I've looked at Rust, and the first time I've looked at this (awesome looking) library, so its likely this is either very wrong, or obvious: but I dug around a bit more to at least try to find _where_, and it seems like maybe it's related to the way these lines work? https://github.com/hecrj/iced/blob/d807ef367e0257ba54f8cf38708a7a61e28a4acb/wgpu/src/triangle.rs#L290-L358 

When antialiasing is on, `self.blit` is not `None` so `attachment` and `Some(resolve_target)` are given to `begin_render_pass`, whereas things work if instead `target` and `None` are passed, as if antialiasing was off and `self.blit==None`

**Comment by hecrj** [comment]
Yes, that is expected.

When MSAA is enabled, in order to not overwrite the contents of the next frame, we need to resolve to a texture and blit it. I believe the blit part of the process somehow doesn't work in your system.

**Comment by parasyte** [comment]
FWIW, I have had similar reports with macOS 10.14.16 causing black screen in `pixels`, but I have been unable to track down the cause:

* https://github.com/parasyte/pixels/issues/72
* https://github.com/parasyte/pixels/issues/76

**Comment by declanvk** [comment]
I'm still getting the issues with the canvas when compiling from master (038f75e) when antialiasing is turned on. I confirmed that turning off shows the grid and other stuff.

<img width="1280" alt="Screen Shot 2020-06-24 at 10 30 31 PM" src="https://user-images.githubusercontent.com/7276122/85660408-7097b300-b66a-11ea-8eb9-9019992c922c.png">

**Comment by JarrettBillingsley** [comment]
Posting here because this *seems* like the same issue I'm having, but mine's even worse somehow.

When `antialiasing` is `true`, the `clock` and `solar_system` examples crash with this on the console:

```
-[MTLIOAccelRenderCommandEncoder bindEmulationArguments]:139: failed assertion `No render pipeline state bound'
Abort trap: 6
```

the OS crash log shows this backtrace: https://gist.github.com/JarrettBillingsley/7f67fbb15f62fe3dda087283aedb1e7b

Setting `antialiasing` to `false` avoids the crash. 

I'm on a 2015 mac OS 10.15.5 with intel HD graphics 6000.

**Comment by hecrj** [comment]
@JarrettBillingsley It doesn't seem like the same issue.

- Do the examples in [`wgpu-rs`](https://github.com/gfx-rs/wgpu-rs/tree/master/examples) work for you? Specially the [`msaa-line`](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/msaa-line) one.
- If you enable the `glow` and `glow_canvas` features, does the problem still occur?

**Comment by JarrettBillingsley** [comment]
(responded on Zulip)
