### ISSUE TITLE
Won't build on Windows with x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by john01dav** [hecrj/iced#346]
When on Windows 10 and building to x86_64-pc-windows-gnu, compiling a program with iced gives this error:
![image](https://user-images.githubusercontent.com/3982497/82150140-a05acc00-981d-11ea-9ced-5075a8538c24.png)
Obviously, as this is building on Windows it is inappropriate to expect that `g++` is present. As such, it is a bug that this library will not build without `g++` on Windows. Note that other programs compile just fine, as rustup now contains the linker when you install this target. It isn't clear to me if this is a spirv-cross bug or an iced but, but, either way, the people here who are depending on spirv-cross likely will know, hence I am making the bug report here.

Additionally, I would like to note that when cross-compiling from Linux to this same target, although a .exe is created, this .exe won't run on Windows because it wants access to libstdc++-6.dll, but, when I pull a copy of this DLL from GCC-TDM (a random Windows GCC port, since the file doesn't exist in the files that Rustup downloads), the program crashes with cryptic hex error messages.

**Comment by hecrj** [comment]
I believe this is related to [`spirv_cross`](https://github.com/grovesNL/spirv_cross), which is using [`cc`](https://github.com/alexcrichton/cc-rs). You can check out its [compile time requirements](https://github.com/alexcrichton/cc-rs#compile-time-requirements).

**Comment by john01dav** [comment]
Thank you for the quick response! Unfortunately, when I fix the spirv_cross issue, by adding TDM-GCC's g++ to the path, although I get an exe that runs, it creates a blank window. I have [a simple "hello world" gui as described in the documentation](https://docs.rs/iced/0.1.1/iced/trait.Application.html), and it works fine on Linux so the code is probably correct.

**Comment by kerskuchen** [comment]
Maybe https://github.com/gfx-rs/wgpu/issues/464 helps?

Especially the 

```
cargo update -p cc --precise 1.0.50
```

from  https://github.com/gfx-rs/wgpu/issues/464#issuecomment-623800438 worked for me on Windows MSVC. I dunno if it works for your case with GCC though :/

**Comment by john01dav** [comment]
Unfortunately that didn't fix the issue @kerskuchen . Thanks for the attempt though :) With the old version of cc, the window is still blank.

**Comment by mattbradbury** [comment]
> Unfortunately that didn't fix the issue @kerskuchen . Thanks for the attempt though :) With the old version of cc, the window is still blank.

Can you get any of the examples to work?  I'm having a problem with the tour example giving me a white window, but everything else works.  I think I've tracked it down to the "Image" feature, but still working through it.

**Comment by hecrj** [comment]
@john01dav Do the examples in `master` work for you? We have recently updated `wgpu` and removed OpenGL and DX11 as backend choices, so we may get an actual error.

**Comment by john01dav** [comment]
@mattbradbury @hecrj The examples in master don't work. [Here](https://www.youtube.com/watch?v=XVIM0fr8vuM)'s a video to show exactly what happens. To reproduce, download the VM from [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) and run in VirtualBox on a Linux host. I suspect that this is an issue of poor OpenGl support in VirtualBox, but, as iced is to be used for more than just video games, this is the sort of thing that should still work without good OpenGl (or DirectX, etc.) support.

**Comment by john01dav** [comment]
I just tried on Windows 10 on real hardware with Intel HD Graphics 3000. It
fails exactly how it did in the video of the VM. This graphics adapter only
supports Opengl 2.x, so what I said about lackluster graphics support still
applies.

**Comment by hecrj** [comment]
@john01dav OpenGL is currently not supported, as mentioned in both the [main readme][1], [`iced_wgpu`'s readme][2], #257, #194, #182, #174, and #72.

I am closing this issue, as the original problem seems to have been resolved.

[1]: https://github.com/hecrj/iced/blob/master/README.md
[2]: https://github.com/hecrj/iced/blob/master/wgpu/README.md
