### ISSUE TITLE
question：how can I close the console window?

### ISSUE THREAD

**Issue by CrazyPandas** [hecrj/iced#360]
It will open a console window when I run the iced app, how can I close it?

**Comment by FabianLars** [comment]
Try adding `#![windows_subsystem = "windows"]` at the top (line 1) of your main.rs/entry file.

**Comment by CrazyPandas** [comment]
> Try adding `#![windows_subsystem = "windows"]` at the top (line 1) of your main.rs/entry file.

It's working. 

Thanks
