### ISSUE TITLE
Tour's Slider: keyboard accessibility

### ISSUE THREAD

**Issue by forresto** [hecrj/iced#366]
Trying the [web demo](https://iced.rs/), when an `input type=range` slider has focus, I expect to be able to use the arrow keys to change the value.

https://github.com/hecrj/iced/blob/ead4186870d1b46015986f702dd63382498060fc/examples/tour/src/main.rs#L394-L403

This `step=0.01` could be part of the issue:

https://github.com/hecrj/iced/blob/ead4186870d1b46015986f702dd63382498060fc/web/src/widget/slider.rs#L117-L121

Is the state of the demo enforcing the integer-rounding? So, arrow-right makes the value 50.01, but then the state rounds it back to 50?

---

Edit: most everything else is keyboard-accessible, so we should celebrate that! 🌮 🎉

**Comment by hecrj** [comment]
> Is the state of the demo enforcing the integer-rounding? So, arrow-right makes the value 50.01, but then the state rounds it back to 50?

Yes, you are correct. We should make `step` a first-class attribute of the `Slider` widget.
