### ISSUE TITLE
Thread pool executor usage in iced_wgpu::window::Compositor

### ISSUE THREAD

**Issue by myfreeweb** [hecrj/iced#368]
Currently, wgpu compositor creation uses the futures thread pool executor:

https://github.com/hecrj/iced/blob/ab0ee1a8d09a717cbcd04d0a2d711ce53fe0e172/wgpu/src/window/compositor.rs#L22

This works inside tokio, but not inside glib:

```
thread 'main' panicked at 'cannot execute `LocalPool` executor from within another executor: EnterError', /home/greg/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:78:18
stack backtrace:
  […]
  15: futures_executor::local_pool::run_executor
             at /home/greg/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:78
  16: futures_executor::local_pool::block_on
             at /home/greg/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  17: <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::new
             at /home/greg/.local/share/cargo/git/checkouts/iced-9e73d2fbe1fce35a/ab0ee1a/wgpu/src/window/compositor.rs:22
 ```

I have changed my local copy of the code to use [async-trait](https://docs.rs/async-trait) to make `new` async and it works :)

What do you think about e.g. adding a `new_async` method and keeping `new` as a `futures::executor::block_on(Self::new_async)` type thing for backwards compatibility / simplicity?

Or.. not doing backwards compatibility for a rather low level API, and dropping the dependency on `futures-executor` (/ `executor` feature in `futures`)?

(P.S. I know that I could delve into raw wgpu usage like in the integration example, but that's too much code to copy, I want to use the `iced_wgpu::window::compositor::Compositor`)

**Comment by hecrj** [comment]
What is the use case here? Why are you calling `Compositor::new` inside a `glib` executor?

Also, isn't this an issue with `futures` / `glib`? It's a leaky abstraction, exposing the implementation details of a function.

**Comment by myfreeweb** [comment]
> Why are you calling Compositor::new inside a glib executor?

I'm building an async program using glib as the runtime. I don't want to segregate window creation into a special pre-async part.

> Also, isn't this an issue with futures / glib?

Would be nice if glib supported this I guess, but as far as I can tell, support for nesting executors like this is not mandatory.

> exposing the implementation details of a function

Well, `Compositor::new` currently exposes the requirement for not being in an async context (unless the context supports this) by hiding the async inside…

Hiding any `async` in a public synchronous function in a library in general feels wrong to me :/

**Comment by hecrj** [comment]
> I don't want to segregate window creation into a special pre-async part.

Why not? Is your window creation async-based?

> Well, Compositor::new currently exposes the requirement for not being in an async context (unless the context supports this) by hiding the async inside…

But it shouldn't! The fact that the function uses a context to await some futures should be an implementation detail that doesn't leak. All you should need to know is that `Compositor::new` _may_ block, like all of the other `Compositor` trait methods.

> Hiding any async in a public synchronous function in a library in general feels wrong to me :/

I can implement an async `new` method for the `Compositor` struct in `iced_wgpu`, as it's a special case. Keep in mind that the other methods can still block (specially `draw`), so if you use them inside a future, then you should consider using `spawn_blocking`.

**Comment by myfreeweb** [comment]
> The fact that the function uses a context to await some futures should be an implementation detail that doesn't leak.

I'm not sure that's actually possible. The presence or absence of an async context is invisible to a regular sync function, but it matters for functions like `block_on` — as I understand it, you're only supposed to use *your runtime's* `block_on`, but tokio and async-std support `futures::executor` somehow.

You can't really encapsulate other libraries' global (well, [thread-local](https://github.com/rust-lang/futures-rs/blob/354ec3773b224944386805bd045116d256eebb5b/futures-executor/src/enter.rs#L4)) state.

> I can implement an async new method for the Compositor struct in iced_wgpu

Yes, please, that would be great.

> Why not? Is your window creation async-based?

I just don't want to! :P I like the `async main()` thing!

**Comment by hecrj** [comment]
> as I understand it, you're only supposed to use your runtime's block_on, but tokio and async-std support futures::executor somehow

I don't think this is stated anywhere in the `Future` contract, which mostly specifies that it should not block. Therefore, this is currently up to the implementation of each executor.

I am just pointing out that `glib` / `futures` panicking when something decides to block on a future inside its context is leaking global state and destroying API boundaries. I am aware this is an ecosystem issue, but we should not take it for granted, specially when this is Rust we are talking about.

> I just don't want to! :P I like the async main() thing!

Sure, that's fine if you are actually dealing with async! But `wgpu` isn't async yet! It will block in many of its operations and, as far as I know, you should never block inside an async context.

By any chance, are you running `Compositor::new` inside a `spawn_blocking`? This could actually be the cause of the issue.

**Comment by hecrj** [comment]
I have opened #369, which implements an async `Compositor::request` method alongside  `Compositor::create_backend`.

Let me know if it works for you, and keep in mind `Compositor::draw` may block until the next frame!

**Comment by myfreeweb** [comment]
> are you running Compositor::new inside a spawn_blocking?

glib is single-threaded, there is no `spawn_blocking`.

> Compositor::draw may block until the next frame!

There was a bug in wgpu 0.4 that caused it to use Vulkan's FIFO mode even when Mailbox mode was specified (by iced). In wgpu 0.5, everything works correctly, the present is non-blocking :)

> Let me know if it works for you

Yep, works great, thanks!

**Comment by hecrj** [comment]
> glib is single-threaded, there is no spawn_blocking.

I believe whether you choose to run your futures on a single-threaded executor or not shouldn't matter. They should still never block. Concurrency is not parallelism.

In this case, you may need to spawn a thread for blocking operations. 

> In wgpu 0.5, everything works correctly, the present is non-blocking :)

Per the docs, it may block:

> The presentation engine waits for the next vertical blanking period to update the current image, but frames __may__ be submitted without delay.

For instance, `draw` blocks on my Linux machine. I can tell by enabling the `debug` view and looking at the render time.
