### ISSUE TITLE
Make sure consumers always use Settings::default

### ISSUE THREAD

**Issue by myfreeweb** [hecrj/iced#372]
Would be nice to protect `Settings` structs using this pattern: https://stackoverflow.com/a/39295611

```rust
pub struct Settings<Flags> {
    …
    #[doc(hidden)]
    pub _please_extend_default: PhantomData<()>,
}
```

**Comment by hecrj** [comment]
What's the motive? Hiding breaking changes? Breaking changes are not always bad.

Currently, users can choose to either rely on `Settings::default` or provide every field manually. If we introduce an additional setting, I believe the latter should be notified when upgrading.

Forcing every user to extend `Settings::default` cripples us as library authors to properly notify changes to our users. A new setting can be a breaking change for some applications.
