### ISSUE TITLE
Cancelling a Command

### ISSUE THREAD

**Issue by andrewmh20** [hecrj/iced#382]
Are there any thoughts on a way to cancel a Command after a Command::perform is issued?

A use case would be if the user can click a button to start some long-running task that we want to run through a Command, and then press another button to cancel it. 

We could just pass the appropriate messages internally to ignore the result--but this is not ideal if the task being run takes up many resources, or continues forever, when we never need the reuslt.

**Comment by hecrj** [comment]
I believe you should be able to use [event subscriptions](https://docs.rs/iced_futures/0.1.2/iced_futures/subscription/index.html).

**Comment by andrewmh20** [comment]
Thanks! Looked into that for a while, but I don't think it applies for this specific use case. That being said, now I think it's not a limitation of Iced. Specifically what I described would require being able to stop some synchronously running code in the middle of execution, which there's no general way to do in Rust (nor _good_ way anywhere perhaps)
