### ISSUE TITLE
Cursor Manipulation

### ISSUE THREAD

**Issue by bansheerubber** [hecrj/iced#388]
Hello! I'm new to Rust and I've decided to use this library for my first project. I'm trying to make a tab auto-complete for a text input. When you press tab, the text inside the input is updated. What I'm wondering is if it is possible to manipulate the cursor so it snaps to the end of the text input when you press tab. Right now, when I update the text input's value when tab is pressed the cursor's position remains unchanged, and as far as I can tell I there is no way make it snap to the end (are the cursor's move_to commands private? is there a way to get around this?).

Also not exactly sure how issues work, this is my first time opening one on an open source project. I noticed there's other questions in here with the question label, so I hope I'm not screwing this up too bad. If I am, I'm sorry!

Loving the library! Thank you for doing a great job maintaining it!

**Comment by hecrj** [comment]
> are the cursor's move_to commands private? is there a way to get around this?

Yes, I tend to make everything private by default unless I have a clear use case in mind. There is no way to currently move the cursor of a `TextInput` programmatically.

However, I believe we should be able to add a `move_cursor_to_end` to `text_input::State` easily.

> Also not exactly sure how issues work, this is my first time opening one on an open source project. I noticed there's other questions in here with the question label, so I hope I'm not screwing this up too bad. If I am, I'm sorry!

No worries! I do not personally have any rules for issues, as long as they are on topic. They are just another channel of communication. In any case, feature requests are completely valid issues!

**Comment by bansheerubber** [comment]
Thank you for the response! I'll try taking a crack at move_cursor_to_end since it doesn't seem too complicated.
