### ISSUE TITLE
Setting initial window size

### ISSUE THREAD

**Issue by gr211** [hecrj/iced#389]
I am building a MFA-type application.

How does one go about setting the initial height and width of the application window ? It should be something trivial to do I'd imagine and yet, no luck. I looked at all the examples and they all start with the very same window dimensions.

I can change the width and height of the widgets themselves. Just not the window (other than using the mouse of course)

Am I being blind here ?

I am running on Linux (arch linux) if that makes a difference for this problem.

Great lib otherwise, still learning how to use it.

Thanks

**Comment by hecrj** [comment]
You should be able to use the [`window` field in `Settings`](https://docs.rs/iced/0.1.1/iced/settings/struct.Settings.html#structfield.window) when calling [`Application::run`](https://docs.rs/iced/0.1.1/iced/trait.Application.html#method.run).

**Comment by gr211** [comment]
Thanks a lot @hecrj . I was pulling my hair on such a trivial goal ;-)

In case anyone else is also wondering:
```
use iced::{Settings, window};

let settings = Settings {
        window: window::Settings {
            size: (300,500),
            resizable: true,
            decorations: true,
        },
        ..Default::default()
    };
```

**Comment by ardijanr** [comment]
@gr211  Thanks, for asking this and showing the solution :)

**Comment by andreyluiz** [comment]
Another easy way of doing it:

```rust
fn main() -> iced::Result {
    iced::application("My app", MyApp::update, MyApp::view)
        .window_size(iced::Size::new(300.0, 400.0))
        .run()
}
```
