### ISSUE TITLE
How can i drop the console for my gui exe

### ISSUE THREAD

**Issue by Silentdoer** [hecrj/iced#393]
Hi, I use the Counter example build and run successful, but it will open a console window, how can i drop it with some code or build option? my os is windows 10.

**Comment by Songtronix** [comment]
Use the windows subsystem attribute introduced in Rust 1.18 https://blog.rust-lang.org/2017/06/08/Rust-1.18.html
```
#![windows_subsystem = "windows"]
```

**Comment by Silentdoer** [comment]
> 
> 
> Use the windows subsystem attribute introduced in Rust 1.18 https://blog.rust-lang.org/2017/06/08/Rust-1.18.html
> 
> ```
> #![windows_subsystem = "windows"]
> ```

thanks very much!
