### ISSUE TITLE
Arc end_angle should be renamed to span_angle

### ISSUE THREAD

**Issue by BillyDM** [hecrj/iced#400]
After scratching my head for a while, I found out that the `end_angle` field in iced::widget::canvas::path::arc::Arc is not the angle where the end of the arc lies. It is actually the span of the arc.

In other words, the end of the arc lies at `start_angle + end_angle`. The field `end_angle` should be renamed to something like `span_angle` to prevent confusion.

https://docs.rs/iced/0.1.1/iced/widget/canvas/path/struct.Arc.html

**Comment by Vanille-N** [comment]
If I may, I believe it's as simple as
```diff
// graphics/src/widget/canvas/path/builder.rs
@@ -84,7 +84,7 @@ impl Builder
- sweep_angle: math::Angle::radians(arc.end_angle),
+ sweep_angle: math::Angle::radians(arc.end_angle - arc.start_angle),
```

I've checked that all other uses of `end_angle` (2 in total) are correct:
```rust
// graphics/src/widget/canvas/path/builder.rs
impl From<Arc> for Elliptical {
    fn from(arc: Arc) -> Elliptical {
        Elliptical {
            // fields omitted
            end_angle: arc.end_angle,   // line 41
        }
    }
}
```
and miraculously, the one other place where `end_angle` is used also needs no change (which perhaps explains why it went unnoticed)
```rust
// graphics/src/widget/canvas/path/builder.rs
#[inline]
pub fn circle(&mut self, center: Point, radius: f32) {
    self.arc(Arc {
        center,
        radius,
        start_angle: 0.0,
        end_angle: 2.0 * std::f32::consts::PI   // line 157
    });
}
```

Seeing that this is labeled `good first issue`, I assume it's okay for a beginner like me to open a pull request ?

**Comment by hecrj** [comment]
@Vanille-N Sounds good! By all means, feel free to open a PR.
