### ISSUE TITLE
Can not display Chinese character

### ISSUE THREAD

**Issue by quanwenbo** [hecrj/iced#403]
`use iced::{Element, Sandbox, Settings, Text};

pub fn main() {
    Hello::run(Settings::default())
}

struct Hello;

impl Sandbox for Hello {
    type Message = ();

    fn new() -> Hello {
        Hello
    }

    fn title(&self) -> String {
        String::from("A cool application")
    }

    fn update(&mut self, _message: Self::Message) {
        // This application has no interactions
    }

    fn view(&mut self) -> Element<Self::Message> {
        Text::new("Hello,无法显示中文 world!").into()
    }
}`

I tried this , but there were no chinese  character displayed on it. just  empty blocks.

**Comment by hecrj** [comment]
See #33, #208, #213, and #227.

**Comment by aisq2008** [comment]
let setting = Settings {
        window: window::Settings  {
            size:(800,600),
            resizable: true,
            decorations: true,
        },
        flags:(),
        default_font:Some(include_bytes!("../fonts/fang_song.ttf")),  //设置中文的.ttf字体可以支持中文
        antialiasing:true
    };

    Counter::run(setting);

   可以从C:\Windows\Fonts 中找宋体的ttf字体设置
