### ISSUE TITLE
How to integrate input events with existing engine, and use iced as ui library?

### ISSUE THREAD

**Issue by DzmitryFil** [hecrj/iced#408]
I looked at the integration example, and from what i gather all winit events are simply queued to iced, and later processed in a batch. What i would like to do however, is handle event with iced if it can (mouse over ui, text input, etc), and if user input is not handled by iced ui elements, send it to controls of my engine (in the same frame). How can this be done?

Nice work on the library, web/native combination is especially impressive.

**Comment by kaimast** [comment]
Could this be exposed to the `Program` trait? It seems that right now `program::State` just discards the vector of `event::Status`s.
