### ISSUE TITLE
`iced_wgpu` version mismatch with crates.io

### ISSUE THREAD

**Issue by telastrus** [hecrj/iced#410]
The `iced_wgpu` crate on crates.io doesn't seem to be updating correctly, as it's still dependent on wgpu 0.4. Looking at `iced/wgpu/Cargo.toml` reveals that it still has its version set to 0.2.2, whereas crates.io has a 0.2.3 version.

**Comment by hecrj** [comment]
The version was bumped in `0.1` as a result of a backport fix.
