### ISSUE TITLE
how to handle multi byte characters ?

### ISSUE THREAD

**Issue by misogihagi** [hecrj/iced#416]
my code like this
```
                .push(
                    Button::new(&mut self.reset_button, Text::new("ＲＥＳＥＴ"))
                        .on_press(Message::Reset),
                )

```
but the result showed this
![000](https://user-images.githubusercontent.com/47350059/85238529-7bcfc080-b469-11ea-820f-81deaab5e5c4.jpg)

iced supports multi byte characters?

**Comment by hecrj** [comment]
See #33.
