### ISSUE TITLE
Resize is slow/not smooth enough

### ISSUE THREAD

**Issue by 0xd34d10cc** [hecrj/iced#417]
The frame times are jumping up to 100 ms on my machine (windows 10, GTX 1060) when window is getting resized, which leads to a huge jumps in size:
![image](https://user-images.githubusercontent.com/26774038/85307516-8907a200-b49f-11ea-882d-3b4e249f7cb5.png)
This seems like wgpu backend problem, because it is reproducible even with minimal [hello-triangle](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello-triangle) example.

**Comment by hecrj** [comment]
I gather you are running the examples in `release` mode?

> This seems like wgpu backend problem, because it is reproducible even with minimal hello-triangle example.

In that case, you should probably open an issue in the `wgpu` repository.

**Comment by 0xd34d10cc** [comment]
Turns out it was some kind of driver issue which was resolved by update.
