### ISSUE TITLE
Iced fails to draw 101 black line

### ISSUE THREAD

**Issue by Voker57** [hecrj/iced#420]
This hacked "custom widget example" showcases the problem: https://github.com/Voker57/101-black-line.

Somehow, having 100+ Path primitives overloads the engine and it no longer draws anything. With 100 primitives there will be a diagonal black line visible. With 101, there is nothing.

**Comment by hecrj** [comment]
Good catch. We are not properly recreating the uniforms `BindGroup` after resizing their buffer. I have opened #421, which should fix the issue.

However, I'd advise you to use the same `Frame` to draw all the lines instead of creating a lot of small `Mesh` primitives.

**Comment by Voker57** [comment]
I'm doing it because Frame can't draw images, which are included in my actual program.
