### ISSUE TITLE
iced_graphics does not expose defaults::Text

### ISSUE THREAD

**Issue by DominosCinnaStix** [hecrj/iced#429]
Iced graphics currently does not expose the `defaults::Text` struct which is needed for default text colors when creating custom widgets similar to Containers. 

I wasn’t sure how to expose it to avoid conflicting with the `Text` widget or if there’s a better way to have contextual defaults for these type of custom widgets so I didn’t PR it

**Comment by hecrj** [comment]
Good catch! Fixing...
