### ISSUE TITLE
iced_wgpu should not pin gfx-memory to 0.1.1

### ISSUE THREAD

**Issue by lachlansneff** [hecrj/iced#438]
The iced-wgpu crate should not pin the gfx-memory dependency to 0.1.1. The issue of performance degradation is because 0.1.1 doesn't actually deallocate memory.

**Comment by hecrj** [comment]
I am aware of the memory leaks present in `gfx-memory 0.1.1`. However, the new `0.1.3` version seems to have important performance regressions.

I explained my reasoning to @cwfitzgerald on Discord a couple of weeks ago and there seem to be improvements coming that should help us:

![image](https://user-images.githubusercontent.com/518289/86856885-93d84e80-c0bd-11ea-996b-1fb65a6c6451.png)

**Comment by lachlansneff** [comment]
With that in mind, perhaps the iced-wgpu crate should be updated to use wgpu-rs master. I'm not sure when wgpu-rs 0.6 will get published. @kvark would know.

The queue.write_buffer/queue.write_texture would likely fix many of these perf issues.

**Comment by kvark** [comment]
If iced has a similar workflow, they can switch to wgpu-rs master for until wgpu-0.6 is released. There is a milestone - https://github.com/gfx-rs/wgpu/milestone/5, although issues in there are small and fat. We are actively approaching that point, thanks to the effort of @cwfitzgerald and @GabrielMajeri .
