### ISSUE TITLE
Container border not being shown (master)

### ISSUE THREAD

**Issue by mtkennerly** [hecrj/iced#452]
I ran into an issue where the border for a `Container` isn't shown. It works on v0.1.1, but not on master (4030326a352c365a282980aa2a37d549f4b659ae).

Gist: https://gist.github.com/mtkennerly/4d5732c9ab11cb59a7be670f8d0c2330

Demo (first on 0.1.1, then on master):

![iced-container-border](https://user-images.githubusercontent.com/4934192/87840714-18ba2980-c86f-11ea-9b53-ca008fab157f.gif)

Environment:

* OS: Windows 10
* Rust: 1.44.1
* Toolchain: stable-x86_64-pc-windows-msvc

**Comment by hecrj** [comment]
Good catch. I introduced this bug in #442. It should be fixed in `master`.

**Comment by mtkennerly** [comment]
That was fast :D Can confirm, all looks good now.
