### ISSUE TITLE
Canvas: Rectangles with negative width/height get drawn, but break Rectangle.contains() function.

### ISSUE THREAD

**Issue by arctic-alpaca** [hecrj/iced#459]
Hello,

it is possible to create and draw `Rectangle` with negative width and height. This actually spared me some `Point` shifting. But as far I can tell, this breaks the `Rectangle.contains()` method since it assumes the `Rectangle` is created with only positve values in `Size`.
What is the intended behavior in this case? `Rectangle.contains()` working with negative width/height or `Rectangle` not allowing negative input?

**Comment by hecrj** [comment]
I don't think a negative length makes sense. Therefore, the current behavior seems to be the intended one.

**Comment by arctic-alpaca** [comment]
It doesn't make any logical sense, but can help avoid having to calculate the top_left `Point`. In my case, I'm drawing multiple  `Rectangle` from an axis. `Rectangle` with positive `Size` results in `Rectangle` below the axis, negative `Size` results in `Rectangle` above the axis. Same for `Rectangle` to the left and right of an axis.

Since this isn't intended behavior, could this be avoided by removing the possibility for negative `Size`?
If there isn't any reason to allow `Size` with a negative `width` or `height`, adding checks to avoid values smaller than zero could avoid confusion with functionality like `Rectangle.contains()` not working as expected.

**Comment by hecrj** [comment]
>  In my case, I'm drawing multiple Rectangle from an axis. Rectangle with positive Size results in Rectangle below the axis, negative Size results in Rectangle above the axis. Same for Rectangle to the left and right of an axis.

In this case, I would create my own `Rectangle` type.

> Rectangle.contains() not working as expected

I am not sure `Rectangle::contains` is "not working as expected". As I said, a negative length is non-sensical to begin with.

> Since this isn't intended behavior, could this be avoided by removing the possibility for negative Size?

We could add some debug assertions here and there, but this seems like a slippery slope.

These types are very simple. I am not sure "using negative values is allowed" is a reasonable conclusion given the `Size` and `Rectangle` definitions.

**Comment by arctic-alpaca** [comment]
> We could add some debug assertions here and there, but this seems like a slippery slope.

Could you elaborate, why this would be a slippery slope? I'm not sure what you mean by this.

> I think we should eventually hide the constructors of Rectangle and Size (i.e. make them read-only) in the iced root crate.

I wasn't aware those types were supposed to be for mostly internal purposes. I think I understand why you don't want to add unnecessary checks to them.

**Comment by hecrj** [comment]
> Could you elaborate, why this would be a slippery slope? I'm not sure what you mean by this.

Basically, it is not clear where we would add the checks. The fields are completely public because, as I said, they are meant to be very simple types that offer no guarantees.

**Comment by arctic-alpaca** [comment]
Makes sense, thank you very much!
