### ISSUE TITLE
Tooltip widget

### ISSUE THREAD

**Issue by yusdacra** [hecrj/iced#460]
Now that we can use `Overlay`s, how would one add a "tooltip widget"? As far as I understand to display an `Overlay` a widget needs to implement the `overlay()` function, but that means if I want to display a tooltip when I hover, say, a radio button I wouldn't be able to use iced's implementation, because I would need to implement the function myself (which I can't, since the trait is already implemented).

So I guess a way would be to wrap the iced radio button in a custom widget and implement the `overlay()` function so that it displays a tooltip when the radio button is hovered? Could also be made generic by making a `Tooltip` widget that takes any widget as `content`, and shows a tooltip over that `content` widget when it's being hovered? Would love to see something like this in.

**Comment by hecrj** [comment]
Fixed by #465.
