### ISSUE TITLE
Allow TitleBar controls to be shown always, instead of just on mouseover.

### ISSUE THREAD

**Issue by mobile-bungalow** [hecrj/iced#461]
As it stands TitleBar controls are only shown on mouse over. This is great for circumstances where the buttons, labels, or pick lists would clutter UI if constantly present. However for many use cases, including my own, it is important for these elements to be static and discoverable. 

I propose adding an `always_show_controls` method to TitleBar. This method should prevent the default behavior and always render the TitleBar with it's controls regardless of pointer state.

I have a test implementation [on my fork.](https://github.com/mobile-bungalow/iced/commit/7977e970ca3db7740c175db2269e47b2c8b93b1f)

**Comment by hecrj** [comment]
Sounds good! Feel free to open a PR with your changes :+1:
