### ISSUE TITLE
How do i enable performance metrics?

### ISSUE THREAD

**Issue by casperstorm** [hecrj/iced#471]
In the [features](https://docs.rs/iced/0.1.1/iced/#features) section you have: [Debug overlay with performance metrics](https://gfycat.com/incredibledarlingbee-rust-gui). But how do I enable this in my app? I tried `F12` etc, but I might be missing something else?

**Comment by Songtronix** [comment]
https://github.com/hecrj/iced/blob/master/Cargo.toml#L32

**Comment by hecrj** [comment]
As @Songtronix mentioned, you need to enable the `debug` feature in your `Cargo.toml`.

**Comment by casperstorm** [comment]
Thank you both.
