### ISSUE TITLE
Implement `From<Color>` for `Option<Background>` 

### ISSUE THREAD

**Issue by bennetthardwick** [hecrj/iced#473]
A small change that would make implementing styles for elements with background colours a bit easier. It would match the `From<T>` for `Option<T>` impl that you can already use for fields that are `Option<Color>` (like `text_color`).

Before:
```rust
Style {
    background_color: Some(Color::BLACK.into()),
    text_color: Color::WHITE.into(),
    ..Default::default()
}
```
After:
```rust
Style {
    background_color: Color::BLACK.into(),
    text_color: Color::WHITE.into(),
    ..Default::default()
}
```

**Comment by Kaiden42** [comment]
Has anyone tackled this issue already? :)

**Comment by hecrj** [comment]
@Kaiden42 Nope. Feel free to grab it! :D
