### ISSUE TITLE
TitleBar and Content missing in pane_grid

### ISSUE THREAD

**Issue by Rababermaber** [hecrj/iced#474]
Hi, when I try to run the iced example pane_grid in my own project, with iced [0.1.1] as
a dependecy I can not compile due to the following errors

```
Compiling iced_wgpu v0.2.3
error[E0432]: unresolved imports `iced_native::pane_grid::Configuration`, `iced_native::pane_grid::Node`
...
error[E0412]: cannot find type `Content` in module `iced_native::pane_grid`
...
error[E0412]: cannot find type `TitleBar` in module `iced_native::pane_grid`
```

however if i use the git as a dependency it works just fine

**Comment by Songtronix** [comment]
master is way ahead of the crates.io release and as such exposes more features.
