### ISSUE TITLE
error in the documentation of ProgressBar

### ISSUE THREAD

**Issue by lovasoa** [hecrj/iced#480]
This is what the [documentation for iced::widget::progress_bar](https://docs.rs/iced/0.1.1/iced/widget/progress_bar/index.html) looks like on docs.rs :

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/552629/90259365-2a7cf580-de4a-11ea-8290-d3336d60023b.png">

It says:
> Allow your users to perform actions by pressing a button.
> A Button has some local State.

I think there was an unfortunate copy and paste...

**Comment by Songtronix** [comment]
Has been fixed in master afaik.

**Comment by hecrj** [comment]
Thanks for the heads up! This was fixed in #301.
