### ISSUE TITLE
Buttons sometimes stuck in their highlighted state

### ISSUE THREAD

**Issue by casperstorm** [hecrj/iced#490]
From here: https://github.com/casperstorm/ajour/issues/35

> It's sometimes possible to move the mouse away from the application, and have the state of a button get "stuck" in the moused over appearance.
>
> Ways to reproduce:
Mouse over [a] button, and then quickly move the pointer up. Or mouse over a button and move mouse to the right.
>
> Since it does not always happen, I think it is caused by the application only registering mouse positions inside the app.

Anything you have seen before, or am i doing something wrong in my application?

**Comment by hecrj** [comment]
Thanks for reporting!

We are not updating the cursor position when it leaves the window, which is indeed a bug. I also noticed our `conversion` logic was missing the `CursorEntered` and `CursorLeft` variants, which prevented the application from redrawing after these events.

I just opened #496, which should fix the issue. Let me know!

**Comment by casperstorm** [comment]
Awesome, @hecrj - thanks for the quick response and execution.
