### ISSUE TITLE
PickList styling example?

### ISSUE THREAD

**Issue by casperstorm** [hecrj/iced#501]
Hi again,
Sorry for creating a lot of issues lately 🙃.
I was wondering if we could add a styling example of `PickList` to the [iced/examples/styling](https://github.com/hecrj/iced/tree/master/examples/styling) or if someone could help me out a little, as I have some problems with this widget compared to the others.

Thanks a lot.

**Comment by hecrj** [comment]
> Sorry for creating a lot of issues lately upside_down_face.

No worries!

The `game_of_life` example features a `PickList` with some custom styling:

https://github.com/hecrj/iced/blob/fb015a85d22a7c4632bd251127a89259bfd0c346/examples/game_of_life/src/main.rs#L846-L856

The actual styling is defined here:

https://github.com/hecrj/iced/blob/fb015a85d22a7c4632bd251127a89259bfd0c346/examples/game_of_life/src/style.rs#L142-L188

**Comment by casperstorm** [comment]
Oh! Missed that. Thought i went through most of the examples to look. Thanks a lot again.
I'll close this issue again then.
