### ISSUE TITLE
Examples fail to run on newer versions of Cargo

### ISSUE THREAD

**Issue by cryptoquick** [hecrj/iced#502]
I'm splitting this out from #447, because I'm not sure if it's a separate issue.

This is regarding to the comment by @and5995 in this thread: https://github.com/hecrj/iced/issues/447#issuecomment-677934268

I think they've either discovered a different issue than that issue, or Windows doesn't have a decent way to explain what's happening like Linux does. I ran into the same issue they're having, also in Linux, which is what I'm running.

```
cargo run --example tour
error: no example target named `tour`
```

This may be a recent behavior of Cargo:

```
cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)

uname -a
Linux hellion 5.8.3-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 21 Aug 2020 16:54:22 +0000 x86_64 GNU/Linux
```

I was able to fix it by rearranging examples, though. I don't think there's any better way to do it that also allows us to run `cargo run --example tour` from the root of the project, as any newcomer might do.

I could submit a PR for fixing this, but I would have to remove all the examples/* directories and combine all the README.md in all of them into the root of the examples directory. Not ideal, and it's a substantial reorganization of the existing code, but it will help newcomers, and I think it's broken either way, at least, in newer versions of cargo, otherwise.

**Comment by cryptoquick** [comment]
Also, this is what tokio does for examples, for example:

https://github.com/tokio-rs/tokio/blob/master/examples/Cargo.toml

**Comment by hecrj** [comment]
Every example is a self-contained subcrate.

As the [examples `README`](https://github.com/hecrj/iced/tree/fb015a85d22a7c4632bd251127a89259bfd0c346/examples) points out, you should run them using the `--package` flag.

**Comment by cryptoquick** [comment]
Oh! Thanks, nevermind then! :+1:
