### ISSUE TITLE
Set global font size

### ISSUE THREAD

**Issue by lerouxrgd** [hecrj/iced#503]
Is it possible to set font size globally ? (For all buttons, radios, etc)

**Comment by Songtronix** [comment]
Yes, https://github.com/Songtronix/Airshipper/blob/master/client/src/gui/mod.rs#L261

**Comment by hecrj** [comment]
You should be able to use the `default_text_size` field in `Settings`:

https://github.com/hecrj/iced/blob/ff15ebc54778dee2a7262469c8a2bcd5abecd4d1/src/settings.rs#L25-L28

**Comment by lerouxrgd** [comment]
Thank you !
