### ISSUE TITLE
Radio look weird when scaled down

### ISSUE THREAD

**Issue by lerouxrgd** [hecrj/iced#504]
Changing the `Radio`'s size in `styling` demo as follows:

```rust
Radio::new(
     *theme,
     &format!("{:?}", theme),
     Some(self.theme),
     Message::ThemeChanged,
 )
 .size(20) // trying to scale down Radio
 .style(self.theme)
```

Gives this:

![image](https://user-images.githubusercontent.com/6103291/92156578-80c9cc80-ee29-11ea-95a5-59cf737c53ba.png)

Is it possible to scale down `Radio` while keeping a circle shape ?

**Comment by hecrj** [comment]
Thanks for the report!

This is a bug. I have opened #513, which should fix it. Let me know!

**Comment by lerouxrgd** [comment]
Yes everything is fine now, thank you for the fix!
