### ISSUE TITLE
I'm wondering the whole flow of the update, subscription and view methods

### ISSUE THREAD

**Issue by wyhhh** [hecrj/iced#509]
**I'm really like this lib.**

In my observation, When the app startups, the subscription will run once unconditionally.

And the view methods will be aways calling. if there some events occurred, as a button pressed, the update will receive the message and do some logic, then the subscription method will follow-up and if the new message sent out, the update method will run again. Like the stopwatch example, run the loop (starting button pressed)"update gets and changes internal state, and then the subscription run unconditionally follows it and sends a message, etc."

So I'm wondering if the loop "update runs - subscription follows - view updates" and start new turn is true?

Thank you!

**Comment by hecrj** [comment]
We have a related discussion in #222 where I shared some of my thoughts. I recommend you to take a look at it. Of course, feel free to join it!
