### ISSUE TITLE
Change initial window position

### ISSUE THREAD

**Issue by wyhhh** [hecrj/iced#515]
I use `std::process::Command` for start-up a new app, but the location of that had overlap part of the old one.

Thanks!

**Comment by hecrj** [comment]
It's not possible yet! There is some related work in #176.

**Comment by wyhhh** [comment]
Thank you!

**Comment by TimUntersberger** [comment]
The `WindowBuilder` now has a `with_outer_position` function.

Source: https://github.com/rust-windowing/winit/pull/1866

**Comment by TimUntersberger** [comment]
I am currently trying to implement this, but I am really confused on how/where I would have to implement this.

I read somewhere that iced uses winit under the hood, but then why is there a separate iced_winit crate? Is this correct?
