### ISSUE TITLE
Horizontal + vertical padding support

### ISSUE THREAD

**Issue by raphtlw** [hecrj/iced#519]
This library is awesome, will there ever be a horizontal/vertical padding support instead of just the normal padding?

**Comment by hecrj** [comment]
Thanks!

Yes, but I'd like to gather a bit more details about the most common use cases for non-uniform padding. Maybe, instead of introducing additional methods in existing widgets, we can come up with better abstractions to tackle them directly!

**Comment by raphtlw** [comment]
I'd like to use the horizontal padding on buttons, cuz they look a little weird with the default 2 axis padding applied, just my input on this :)
