### ISSUE TITLE
Could I capture the extern events through some current support?

### ISSUE THREAD

**Issue by wyhhh** [hecrj/iced#522]
As the title.

**Comment by hecrj** [comment]
What do you mean by "extern events"?

**Comment by wyhhh** [comment]
emm... Just like some keystrokes(such as `ctrl + shift + o` to wake my app) in whatever other windows and that can call my app.

**Comment by hecrj** [comment]
For security reasons, I don't think it's possible to consistently listen to keyboard events when a window is not focused in a cross-platform way (Wayland being the main issue here, see https://github.com/rust-windowing/winit/issues/193#issuecomment-304815903).
