### ISSUE TITLE
Toggler Widget

### ISSUE THREAD

**Issue by Kaiden42** [hecrj/iced#528]
I've played around with implementing my own widgets and came up with a working draft of a Toggler widget.

![Bildschirmfoto vom 2020-09-15 15-51-46](https://user-images.githubusercontent.com/26521388/93220067-5272b800-f76c-11ea-8733-f8bb117f9e68.png)

Would you be interested in adding this to Iced?

The background and foreground colors of the Toggler can be fully customized, as you can see in the picture. However, it is currently not renderer-agnostic and I haven't implemented a support for Iced-web yet.

**Comment by hecrj** [comment]
Yes! I think this could be a great addition to the built-in widgets. Feel free to open a PR!

The API should be very similar to a `Checkbox`, probably only differing in the styling. You should be able to use its implementation as a guide to make it renderer-agnostic.

If you want me to, I could also bring it to the finish line myself (once I clear the backlog... :sweat_smile:).
