### ISSUE TITLE
Failed to build on Windows 10

### ISSUE THREAD

**Issue by H-Logan** [hecrj/iced#529]
Project fails to build after adding `iced = "0.1.1"` to `Cargo.toml`
```
error[E0658]: `if` is not allowed in a `const fn`
   --> C:\Users\hunterl\.cargo\registry\src\github.com-1ecc6299db9ec823\error-code-2.0.1\src\lib.rs:141:13
    |
141 | /             if self.code == 10035 {
142 | |                 return true;
143 | |             }
    | |_____________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `error-code`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Kaiden42** [comment]
Are you using the latest stable release (1.46.0) of Rust? The `if` statement in a const function is only allowed since 1.46.0

https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html

**Comment by H-Logan** [comment]
> Are you using the latest stable release (1.46.0) of Rust? The `if` statement in a const function is only allowed since 1.46.0
> 
> https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html

That was the issue, thanks!
