### ISSUE TITLE
Views not updating

### ISSUE THREAD

**Issue by raphtlw** [hecrj/iced#532]
I just created my first iced application, but my view doesn't update when I hit the "root" button and the "next" button.

[source code](https://github.com/raphtlw/symbit/tree/rust-experimental)

**Comment by hecrj** [comment]
You seem to be [cloning the steps and assinging them to a `View` variant](https://github.com/raphtlw/symbit/blob/49eeb23768c80a1e4abac6b7490e29dac5b7450b/src/main.rs#L77), these cloned steps are then [used in the `view` logic](https://github.com/raphtlw/symbit/blob/49eeb23768c80a1e4abac6b7490e29dac5b7450b/src/main.rs#L143).

However, [you call `advance` on the original steps](https://github.com/raphtlw/symbit/blob/49eeb23768c80a1e4abac6b7490e29dac5b7450b/src/main.rs#L95), which are not used anywhere in your `view` logic.

**Comment by raphtlw** [comment]
Ah, I see it now. I'm still a noob at this haha, thanks for helping me out!
