### ISSUE TITLE
Error: GraphicsAdapterNotFound

### ISSUE THREAD

**Issue by GopherJ** [hecrj/iced#534]
Hi, I would like to try this project but got this error while running an example

I'm on linux mint 19.3 cinamon

**Comment by hecrj** [comment]
`iced` needs Vulkan support to work by default. Is Vulkan available in your system?

You can also try to enable the `glow` feature to use the OpenGL backend in some of the examples. See #427 and #454.

**Comment by GopherJ** [comment]
@hecrj it worked like a charm, thanks for your awesome work

**Comment by PeterlitsZo** [comment]
Could you please tell me how to know if the Vulkan is available? If the way can works on WSL 2, it is helpful for me.
