### ISSUE TITLE
Question : how to set a top most window ? thanks

### ISSUE THREAD

**Issue by qq389146213** [hecrj/iced#539]

**Comment by twitchyliquid64** [comment]
I assume you are using iced_winit, which is a wrapper around winit. Winit has `with_always_on_top`, so perhaps theres a way to set that when building the window?

https://docs.rs/winit/0.22.2/winit/window/struct.WindowBuilder.html#method.with_always_on_top

**Comment by twitchyliquid64** [comment]
So it looks like theres a bunch of crap that gets used when initializing winit, but `with_always_on_top` is not one of them: https://github.com/hecrj/iced/blob/master/winit/src/settings.rs#L77

It should be a simple change however to add it in along side the others. Might be a good PR?
