### ISSUE TITLE
iced master version under CLion+Rust got "cannot find declaration to go to"

### ISSUE THREAD

**Issue by xiuno** [hecrj/iced#561]
iced 0.1 is ok!
![image](https://user-images.githubusercontent.com/3362277/95705027-41db3200-0c85-11eb-893d-3e53458bce23.png)

iced master is bad!
![image](https://user-images.githubusercontent.com/3362277/95705087-69ca9580-0c85-11eb-9abf-a9507179ea43.png)

My Env:
Darwin MacbookPro.local 18.7.0
rustc 1.47.0 (18bf6b4f0 2020-10-07)
CLion 2020.2.4
Rust Plugin: 0.3.132.3395-202 (2020/10/10)

**Comment by twitchyliquid64** [comment]
Does it build?

Whats the build error?

Im having no issues building master on my end.

**Comment by xiuno** [comment]
No problem with compilation.

**Comment by xiuno** [comment]
The final version of CLion+Rust Plugin has solved this problem.

https://intellij-rust.github.io/2020/10/19/changelog-133.html
