### ISSUE TITLE
Windows Subsystem Linux

### ISSUE THREAD

**Issue by justinmoon** [hecrj/iced#564]
Windows Subsystem Linux 2 allows you to [install an X Server to run Linux GUI apps](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242) (!!!)

I've had good luck with most apps, but it's not working with Iced:

```
$ cargo run --package counter
...
     Running `target/debug/counter`
Error: GraphicsAdapterNotFound
```

**Comment by NathanSWard** [comment]
Make sure you use the `glow` feature for iced, as WSL2 uses OpenGL.
For example when creating a iced application, in you `Cargo.toml` file you should have
```
iced = { git = "https://github.com/hecrj/iced", branch = "master", features = ["glow", "tokio"] }
```

**Comment by justinmoon** [comment]
Thanks @NathanSWard. 

This works, but only after unchecking the `Native OpenGL` option in VcxSrv X Server configuration.
