### ISSUE TITLE
Buttons always have padding

### ISSUE THREAD

**Issue by fenhl** [hecrj/iced#574]
I'm making a layout that includes buttons which contain images that are supposed to be displayed seamlessly next to each other. Since wrapping the images in buttons, there are now gaps between the images, even after applying `button::Style::default()` to the buttons. There should be a way to remove these gaps.

**Comment by Eucladia** [comment]
`Button`s have a default padding of 5 units. You can set this to 0 via the `Button`'s `padding` method.

**Comment by fenhl** [comment]
Thanks, that works. I guess I was just looking at the wrong crate's docs.
