### ISSUE TITLE
High frequency timer subscription freezes on Windows

### ISSUE THREAD

**Issue by celsobonutti** [hecrj/iced#577]
First of all: thank you for your great work, this library is amazing!

I'm having some problems with my application on Windows, though: I'm using it (and its canvas) as the front-end for my Chip8 emulator.  It works fine both in Linux and WSL inside Windows but, when I try to use [this subscription](https://github.com/celsobonutti/xipe-oito/blob/bf86e599099db2a9b174be6e9f98fcc70fe3af48/emerson/src/application.rs#L158) on Windows, it just freezes after some seconds. I thought it could be the lack of optimizations in my code but, replacing my execution with a simple `println!` proved that it was freezing anyway, not being a performance issue.

**Comment by hecrj** [comment]
I think this may be related to #512.

**Comment by celsobonutti** [comment]
I think it probably is. I tried `async-std` and now it doesn't freeze, but still runs pretty slowly. 

I want to help but don't have a lot of ideas on how, do you think that's something fixable on the `iced` side? If so, what do you think is a good entry point to start contributing to this fix?

**Comment by celsobonutti** [comment]
I just came back to the project, and bumping my version to 0.2.0 + going back to `tokio` solved the issue. Thank you!
