### ISSUE TITLE
PaneGrid on_key_press fn Doesn't work

### ISSUE THREAD

**Issue by umaYnit** [hecrj/iced#585]
i am running the example [pane_grid](https://github.com/hecrj/iced/tree/master/examples/pane_grid), but it does not happened any thing when i press the keyboard. and i use `println!("{:?}", event);` in fn `handle_hotkey`, it also has no output.

my system is Win10 1909(18363.1139), 
and the rust version is rustc 1.49.0-nightly (b1af43bc6 2020-10-10)

**Comment by hecrj** [comment]
You need to press the [`modifier_keys`](https://iced-docs.now.sh/iced_native/widget/pane_grid/struct.PaneGrid.html#method.modifier_keys) to trigger a hotkey.

The default modifier key is `Ctrl`.

**Comment by umaYnit** [comment]
it's ok, thanks.
