### ISSUE TITLE
Windows icon

### ISSUE THREAD

**Issue by fenhl** [hecrj/iced#587]
How do I change the taskbar/titlebar icon for an iced app on Windows? I tried setting the icon using the [winres](https://docs.rs/winres) crate, but the icon didn't change.

**Comment by hecrj** [comment]
You need to set the `icon` in [`window::Setings`](https://iced-docs.now.sh/iced/window/struct.Settings.html#structfield.icon).

**Comment by fenhl** [comment]
Ah, so this is not possible yet in the current release?

**Comment by fenhl** [comment]
Closing this since this feature is released now.
