### ISSUE TITLE
Graphs example

### ISSUE THREAD

**Issue by CallistoM** [hecrj/iced#588]
Is there any example that shows how to build graphs like shown in cryptowatch? I looked at the progress bar example but that seems to be horizontal only.

**Comment by twitchyliquid64** [comment]
I don't think the widgets used in cryptowatch are open source. This was mentioned in the iced chat however: https://github.com/hibi221b/plotters_backend_iced_app

**Comment by hecrj** [comment]
The charts shown in Cryptowatch Desktop are built on top of [the `Canvas` widget](https://iced-docs.now.sh/iced/widget/canvas/struct.Canvas.html).

I believe [the `game_of_life` example](https://github.com/hecrj/iced/tree/master/examples/game_of_life) showcases very well how this widget can be used to draw interactive geometry.

**Comment by CallistoM** [comment]
Thanks, I will look at the game_of_life example.

**Comment by milesfrain** [comment]
https://github.com/Joylei/plotters-iced is another plotting example from the list in https://github.com/iced-rs/awesome-iced#integrations

Figured I'd drop the link here, because I found this issue thread before the above list.

**Comment by wlwatkins** [comment]
Are there planes to get highly interactive plots as available in egui? I'm looking for heatmaps (with high number of "pixels") and x/Y plots with high interactivity, like one would find in labview.
