### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by shirshak55** [hecrj/iced#593]
Just wanted to test but its giving error for stopwatch example

```
error[E0432]: unresolved import `iced::time`
 --> src\main.rs:2:23
  |
2 |     button, executor, time, Align, Application, Button, Column, Command,
  |                       ^^^^ no `time` in the root

error[E0412]: cannot find type `Result` in crate `iced`
 --> src\main.rs:8:24
  |
8 | pub fn main() -> iced::Result {
  |                        ^^^^^^ not found in `iced`
```

i tried to search docs too but I also didn't found time and result ? I don't know what I am doing wrong here.

**Comment by manokara** [comment]
In order to use `iced::time` you need to enable one of the async support features: `tokio` or `async-std`. But the `iced::Result` one is weird, as it was added [this commit](https://github.com/hecrj/iced/commit/c1f79b40cf704cafc807250b177fc7d3444fe54f) along with making `main()` return it.

**Comment by shirshak55** [comment]
@manokara i did add tokio in features part.

**Comment by manokara** [comment]
Hmm, but the stopwatch example's Cargo.toml already has it. Just did a fresh clone of the repo and ran the stopwatch example with no errors. Are you sure you are using the latest version from GitHub? Or did you perhaps copy the stopwatch code and ran it with the crates.io version, which is very outdated?

**Comment by shirshak55** [comment]
@manokara yes I just copied the example and pulled the crate from crates.io :(

**Comment by manokara** [comment]
Oh, so that was it. It's good to compare the date of the last change on GitHub and the one on crates.io to avoid something like that happening again. Even a single change may introduce a complete new way of doing something, and in the case of iced, the github version is where all the magic is happening right now.

@shirshak55 Please close the issue if everything was solved :+1:

**Comment by shirshak55** [comment]
Sure thanks :)
