### ISSUE TITLE
Unable to use closures that capture from environment

### ISSUE THREAD

**Issue by Ssaely** [hecrj/iced#594]
After this [commit](https://github.com/hecrj/iced/commit/dd1b1cac0ae76655bd81d20e4b245f5afc1bde61) you can no longer pass in closures that use `move` in subscriptions.

The error
```
expected fn pointer `fn(std::time::Instant) -> app::Message`
found closure `[closure@file.rs:72:39: 72:62 x:_]`
```

**Comment by hecrj** [comment]
Yes, that's intentional. What is your use case?

You can use [`Subscription::with`](https://iced-docs.now.sh/iced_futures/subscription/struct.Subscription.html#method.with) to pass data into a subscription context.

**Comment by Ssaely** [comment]
Ah, I missed that on the docs, thank you!  My use case was to dynamically pass data into subscriptions which was why I originally used `move`, but `Subscription::with` will work.

**Comment by hecrj** [comment]
What kind of dynamic data? Could you instead generate that data in `update` after the `Subscription` fires?
