### ISSUE TITLE
About the event closure of Checkbox

### ISSUE THREAD

**Issue by wyhhh** [hecrj/iced#609]
```rust
    pub fn new<F>(is_checked: bool, label: impl Into<String>, f: F) -> Self
    where
        F: 'static + Fn(bool) -> Message,
    {
        Checkbox {
            is_checked,
            on_toggle: Box::new(f),
            label: label.into(),
            width: Length::Shrink,
            size: <Renderer as self::Renderer>::DEFAULT_SIZE,
            spacing: Renderer::DEFAULT_SPACING,
            text_size: None,
            font: Renderer::Font::default(),
            style: Renderer::Style::default(),
        }
    }
```
I copy from the iced code, the type of the `F` above is `Fn(bool) -> Message`, but if I want to use a captured value's `self fn`, 
I need to write `move |_| x.clone.into_something()` so there actually do one more clone method. 
Whether it can do some change?

**Comment by hecrj** [comment]
I am not sure I understand the issue here. Is it the `clone` call? Could you elaborate a bit? Maybe you could share a specific example that showcases the problem?

**Comment by wyhhh** [comment]
Oh yes, is `clone()` call.
The idea is that the `Fn()` closure just can supply `&self` signature, so I want to send a ownership like `pathbuf` that I need to do `move |bool| pathbuf.clone().into_box_path()`, here captured  the ownership of `pathbuf`(which needs `'static` lifetime so I must move it ) and then *clone() one more time*, if was `FnOnce()` that I can just `move |bool| pathbuf.into_box_path()`.
Maybe `FnOnce()` just can call once? So that isn't a good choice. I don't know,  thanks anyway.

**Comment by twitchyliquid64** [comment]
If you move the data underlying the checkbox though, it will no longer be available to the checkbox, so the checkbox could no longer function properly? Not sure I understand how moving the data underlying the UI is feasible.


In general, Iced does the 'closure-to-map-event-to-messages' thing a lot: text inputs, sliders, etc all have this approach:

```rust
pub fn new_widget_thingy<F>(some_state: state_type, f: F) -> Self
    where
        F: 'static + Fn(event_type) -> Message,
```

The closure you provide is the 'glue' between the user interaction and its data, and the message that gets emitted to your specific application.

In practice, try to make all your `Message` types 'cheap' and clone-able. If the underlying data is not cheap to clone, consider using some indirection that is: (for example, making an enum who's variants represent the different states, or using an `Arc<>`)
