### ISSUE TITLE
Alt-Tab should not cause next widget to be focused like pressing Tab without Alt

### ISSUE THREAD

**Issue by Boscop** [hecrj/iced#612]
Alt-Tab should not cause the next widget to be focused (like pressing Tab without Alt).
But currently it does.

Also, Shift+Tab should focus the previous widget, but currently it doesn't.

**Comment by hecrj** [comment]
Closing as a duplicate of #489.

> Alt-Tab should not cause the next widget to be focused (like pressing Tab without Alt).
But currently it does.

Could you specify where? `iced` does not currently implement any kind of focus switching.

**Comment by Boscop** [comment]
> Could you specify where?

I tested crypto watch desktop on Linux, and when I Alt+Tabbed away from it, it still interpreted the Tab key press and focused the next input field.
