### ISSUE TITLE
Text_input double-click selection issue 

### ISSUE THREAD

**Issue by adamwern** [hecrj/iced#616]
When I double or triple click on text in `text_input` it first selects a whole word (or whole line for triple click) then reselects from the beginning up to the current cursor position. I can see the correct selection quickly flash for a frame or so.

The bug is present in all input boxes I've tried, like `examples/todos`.
Tested with both mouse and trackpad.
Platform: macos / wgpu
Branch: master

Video of the issue:
[TextInput Bug.mov.zip](https://github.com/hecrj/iced/files/5545686/TextInput.Bug.mov.zip)

**Comment by hecrj** [comment]
Thanks for the report!

I have just opened #620, which should fix the issue.
