### ISSUE TITLE
Big border radius produces funky shape instead of maximally rounded sides

### ISSUE THREAD

**Issue by myfreeweb** [hecrj/iced#624]
In CSS, a very large `border-radius` value produces rounded sides but straight top and bottom edges:

![Screenshot_2020-11-21 JS Bin](https://user-images.githubusercontent.com/208340/99860803-37298c00-2ba5-11eb-8dda-c61a71951f36.png)

In iced, it's uhhh whatever this is :)

![Screen_2020-11-21-02:58:16](https://user-images.githubusercontent.com/208340/99860962-bcad3c00-2ba5-11eb-9af9-cbcf2b582f05.png)

And if the radius is too big, the background is not drawn at all.

**Comment by hecrj** [comment]
This commit https://github.com/hecrj/iced/pull/628/commits/1916755b6b3f84329c3e3f3e9a4e1b6d2b4e45a4 in #628 should fix the issue. Let me know!

**Comment by myfreeweb** [comment]
Yes, it does, thanks
