### ISSUE TITLE
Include PresentMode in wgpu::settings::Settings?

### ISSUE THREAD

**Issue by rtfeldman** [hecrj/iced#625]
I'd like to use [`PresentMode::Immediate`](https://docs.rs/wgpu/0.6.0/wgpu/enum.PresentMode.html#variant.Immediate) for low-latency text rendering, but currently `wgpu::window::compositor::Compositor` [is set](https://github.com/hecrj/iced/blob/ea1a7248d257c7c9e4a1f3989e68b58a6bc0c4ff/wgpu/src/window/compositor.rs#L116) to always use [`wgpu::PresentMode::Mailbox`](https://docs.rs/wgpu/0.6.0/wgpu/enum.PresentMode.html#variant.Mailbox).

Would it be possible to make present mode configurable, by including a `PresentMode` field in [`Settings`](https://github.com/hecrj/iced/blob/ea1a7248d257c7c9e4a1f3989e68b58a6bc0c4ff/wgpu/src/settings.rs#L8)? That would mean that instead of present mode being fixed at `Mailbox` inside the `create_swap_chain` implementation, it could instead become `self.settings.present_mode` and therefore configurable to use any of the available present modes?

**Comment by hecrj** [comment]
Yes, sounds reasonable.

It's important to note that widgets have no way to ask for redraws directly yet. Instead, `iced` redraws after every batch of events in the event loop. As a consequence, disabling v-sync will most likely cause an important increase in the amount of unnecessary redraws when interacting with the application.

**Comment by hecrj** [comment]
I have opened #629. Let me know if that suits your needs!

Once we can avoid redrawing unnecessarily, maybe we could allow users of the main crate to configure a `vsync` field in the main [`Settings`](https://github.com/hecrj/iced/blob/ea1a7248d257c7c9e4a1f3989e68b58a6bc0c4ff/src/settings.rs#L6), similar to `antialiasing`.

**Comment by rtfeldman** [comment]
Oh wow, awesome! That's exactly what I was hoping for - thank you so much! 😃
