### ISSUE TITLE
Regression: Clock example

### ISSUE THREAD

**Issue by thegatsbylofiexperience** [hecrj/iced#626]
Hi,

I have tried building the clock example on master and on version 0.1.1.

The clock in master has a regression. It is mirrored in the x axis and the hands of the clock run anticlockwise.

I did a git bisect and this appears to be the first commit that causes the issue:

6f52eb4d3a99565a6261eca3263fa8a5e2c3f63f is the first bad commit

Hope that helps and thanks for your time.

**Comment by thegatsbylofiexperience** [comment]
Seems like it is the dependency lyon v0.16 that is causing the regression. (graphics/Cargo.toml)

I tested reverting to 0.15 on master removes the issue,

Thanks

**Comment by hecrj** [comment]
Thanks for catching this! #627 should fix the issue.

**Comment by thegatsbylofiexperience** [comment]
No sweat mate! What open source is for :) Sorry I couldn't be of more help. My first experience with the Iced code base  :/
