### ISSUE TITLE
Close Event

### ISSUE THREAD

**Issue by Mateholiker** [hecrj/iced#640]
Is there a way to get a close event? In most programs for example a text editor the user gets a "do you want to save the unsaved changes" message with the option to cancel the program exit. I want to do something similar.

**Comment by tarkah** [comment]
For now, I think you'd need to manage your own winit event loop so you can handle the `winit::event::WindowEvent::CloseRequested` event. Iced has an integration example of doing so here:

https://github.com/hecrj/iced/tree/master/examples/integration

It'd be nice if in the future, we could specify something like an `Application::close_ready` method that returned a `bool` which can be referenced behind the scenes in the winit loop, and it will only close when that returns `true`. And then have the `winit::event::WindowEvent::CloseRequested` event exposed on the native subscription, so we can handle that message and then appropriately allow `true` to be returned once we the application is safe to get closed

**Comment by alex13sh** [comment]
For this case you can use Drop for your app struct

**Comment by yusdacra** [comment]
> For now, I think you'd need to manage your own winit event loop so you can handle the `winit::event::WindowEvent::CloseRequested` event. Iced has an integration example of doing so here:
> 
> https://github.com/hecrj/iced/tree/master/examples/integration
> 
> It'd be nice if in the future, we could specify something like an `Application::close_ready` method that returned a `bool` which can be referenced behind the scenes in the winit loop, and it will only close when that returns `true`. And then have the `winit::event::WindowEvent::CloseRequested` event exposed on the native subscription, so we can handle that message and then appropriately allow `true` to be returned once we the application is safe to get closed

I think exposing winit events (and others, could even be widgets requesting a redraw because they are animated) using the `subscription` method would be neat. We would pass it to the method as an argument and the user could just use `map` on it to map them to their `Message` and handle them.

**Comment by hecrj** [comment]
This seems to be a duplicate of #170. Let's keep the discussion going there!
