### ISSUE TITLE
How to minimal window and resize window

### ISSUE THREAD

**Issue by cossonleo** [hecrj/iced#644]
How to minimal window and resize window

**Comment by agraven** [comment]
If you want to change the size of your application when you launch it, you can do so by changing the `window` property on the [`Settings`](https://docs.rs/iced/0.2.0/iced/settings/struct.Settings.html) struct you pass to [`Application::run`](https://docs.rs/iced/0.2.0/iced/trait.Application.html#method.run) (or `Sandbox`, if that's what you prefer). 

If you want to change it while your application is running, you have to use the `Applcation` trait, and implement the [`mode`](https://docs.rs/iced/0.2.0/iced/trait.Application.html#method.mode) function, which is expected to take a reference to your application state as argument, and return the `Mode` you want your application to have.

**Comment by TimUntersberger** [comment]
@agraven sorry but how can you resize a window using the `mode` function? You can only change between windowed and fullscreen.
