### ISSUE TITLE
Scrollable scrollbar events need to resolve before self.content

### ISSUE THREAD

**Issue by tarkah** [hecrj/iced#649]
If a widget nested inside scrollable captures `Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left))` and returns `Status::Captured`, the scrollable gets locked on `self.state.is_scroller_grabbed() -> true` since we return before evaluating https://github.com/hecrj/iced/blob/d16b9cf7cd98a3d65ea5408ac9b72298cb267e85/native/src/widget/scrollable.rs#L236-L290 

Since we only want to interact with the scrollbar when over it, not the scrollables content, we should process it's events before it's content. The other non-scrollbar scrollable events should still be processed after, however.

Would another solution be to limit the width of self.content bounds to not include the area where the scrollbar lives?

**Comment by hecrj** [comment]
The bug you are describing should only be possible if a widget unconditionally captures a mouse button release. I am not sure this is reasonable.

In other words, for the scrollbar to get stuck, the child widget should ignore mouse presses (so the scrollbar can be grabbed) and then capture mouse releases after that.

Could you provide a bit more details about the kind of widget that must implement this kind of behavior?

**Comment by tarkah** [comment]
We created a widget that's basically an extension of container where the entire thing is clickable. We have expandable rows in our program, and we wanted to make the entire row clickable. These rows are inside the scrollable. So we capture the left mouse button release as the click event, but not the mouse button press. 

Our current workaround is to return Status::Ignored from the child widget after the mouse click release event, but that doesn't seem accurate.

**Comment by hecrj** [comment]
I see. I'm not sure it's reasonable for a widget to capture release events without capturing the pressed ones first.

In any case, I believe we should always handle the mouse release events in the `Scrollable` to avoid these kinds of bugs with "unreasonable" or faulty widget implementations.

**Comment by tarkah** [comment]
After playing around more, we did in fact have a faulty implementation. Thanks for helping clear things up.

We changed our widget to trigger on `ButtonPressed`. Initially the scroll bar didn't work since we were returning `Status::Captured` after processing this event in our nested widget. Our work-around was to just send back `Status::Ignored`. 

I realized our mistake. Even though we check our layout bounds before processing the button click message, we returned the `Status::Captured` regardless of if the cursor was in bounds or not. So adding that in our bounds check block fixed things right up.

Here's where we messed up...

### Before

```rust
if let Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) = event {
    if let Some(on_press) = &self.on_press {
        let bounds = layout.bounds();

        if bounds.contains(cursor_position) {
            messages.push(on_press(event));
        }

        return event::Status::Captured;
    }
}
```

### After

```rust
if let Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) = event {
    if let Some(on_press) = &self.on_press {
        let bounds = layout.bounds();

        if bounds.contains(cursor_position) {
            messages.push(on_press(event));

            return event::Status::Captured;
        }
    }
}
```
