### ISSUE TITLE
`TextInput` captures all `keyboard::KeyPressed` events while focused, breaking subscription-based hotkeys

### ISSUE THREAD

**Issue by twitchyliquid64** [hecrj/iced#651]
I'm using `subscription::events_with()` to implement hotkey functionality. This works well, except when a text input in focused. I've tracked it down to

https://github.com/hecrj/iced/blob/d16b9cf7cd98a3d65ea5408ac9b72298cb267e85/native/src/widget/text_input.rs#L370-L373

`<snipped>`

https://github.com/hecrj/iced/blob/d16b9cf7cd98a3d65ea5408ac9b72298cb267e85/native/src/widget/text_input.rs#L547-L551

From what I can gather, widgets should return `event::Status::Ignored` for events that don't concern them, so other parts of the UI can react. `text_input` doesnt seem to do that.

**Comment by hecrj** [comment]
`winit` will notify us both of a key press event and a character received event. In order to avoid collisions with any subscription-defined hotkeys, we simply capture every key press for now.

Even if we captured keys that only produce characters, there are also combinations of keys that may be pressed to input text (e.g. modifier keys, accent keys to produce `á`). These should also probably be captured.

It's also important to note that `subscription::events_with` lets you handle a key press even if it was captured. `event::Status` is part of the function signature.

**Comment by twitchyliquid64** [comment]
> It's also important to note that subscription::events_with lets you handle a key press even if it was captured. event::Status is part of the function signature:

Oh mah gawd i totally missed that :fearful: :smile: :gun: 

> As always, I'd like to know which particular use cases you have!

In my case, I have a search bar and results pane. I would like to be able to use the keyboard + tab + shift-tab to easily navigate results (i find it more intuitive), but having the input capture all the keys (certainly the keyboard and tab keys) makes that harder.

Specifically, navigate results as in:

 * Pressing Tab from the search bar moves focus to the first result
 * Pressing Tab/Shift-Tab/Up/Down navigates results
 * Shift tab from the beginning of results focuses the search bar
 * Tab from the end of results focuses the search bar

![image](https://user-images.githubusercontent.com/6328589/101290205-95658a00-37b5-11eb-9465-804ef3b887b4.png)

Having each widget only 'capture' key presses relevant to it is important: That way, the search results widget only needs to handle navigation logic for itself and only if its focused, and that way any tab presses that are not captured get routed to the `events_with` subscription for global handling. This approach keeps logic relevant to each widget 'in' each widget, and that way tab handling logic at the `Application` level only needs to handle a tiny number of cases.

> Even if we captured keys that only produce characters, there are also combinations of keys that may be pressed to input text (e.g. modifier keys, accent keys to produce characters like á, etc.). These should also probably be captured.

Sounds good. I can update the linked PR to either:

 * Exhaustively identify all keys which might be part of any valid character
 * Allowlist (do not capture) certain keys we know not to be part of text input. Probably Tab + Up + Down. This would be the minimum change to solve my issue.

**Comment by twitchyliquid64** [comment]
> Even if we captured keys that only produce characters, there are also combinations of keys that may be pressed to input text (e.g. modifier keys, accent keys to produce characters like á, etc.). These should also probably be captured.

I went digging for a canonical reference of virtual key codes which contribute to generate input characters. Unfortunately I couldn't find one, so I don't think it will be possible for me to update the PR to exhaustively capture just those keys :/

Would you be open to instead me just allowlisting keys from capture that are definitely not part of character input? Specifically Tab, F1-12, Up, Down. Not perfect, but slightly closer.
