### ISSUE TITLE
Can I display Chinese characters and emoji at the same time ?

### ISSUE THREAD

**Issue by Erxl** [hecrj/iced#660]

**Comment by Erxl** [comment]
Just like browsers

**Comment by twitchyliquid64** [comment]
I dont think so - you need to pick a font (or leave at default) on a per-widget basis.

What browsers are doing in the background is keeping track of which fonts implement which grapheme, and using the highest-priority font that implements that grapheme. Iced, at least for the moment, only measures/draws using a single font at a time. So while you can change the fonts on a per-widget basis, you cant use use glyphs from multiple fonts in the same `Text` (or similar) widget.

**Comment by hecrj** [comment]
Duplicate of #33.
