### ISSUE TITLE
Why messages over callbacks?

### ISSUE THREAD

**Issue by jgarvin** [hecrj/iced#662]
I never used Elm, so I'm just going by my experience using iced, but it feels like iced is asking me to go through extra hoops to write callbacks. I have been working through the tour example, trying to modify it to resemble the GUI I want. Say I want some code to run when the user presses a button. In other GUI frameworks you would pass a callback to the button when constructing the button. In the tour example I have to go through extra song and dance to get the same effect -- I need to define a message type, then I need to add a constructor corresponding to that particular button, then I need to add a new pattern match inside my update method, *then* I get to write the code I actually originally wanted to write. I assume there are some advantages to doing it this way but as a newbie it's not clear to me. Why is this preferred?

**Comment by twitchyliquid64** [comment]
Iced is based off [Elm](https://guide.elm-lang.org/architecture/#the-basic-pattern) - most evident in it structuring things into messages, views, and state. It sounds like you are used to an event driven API, or a retained mode API like in GTK. This is one way of doing things, but not the only way.

I can't speak for Iced' author, but personally ive found the more verbose state + view + message approach to scale better than using a callbacks API that hides the message passing. Ive found composing messages and state objects to be more understandable and readable as the project gets larger, compared to yeeting gobject callbacks everywhere as is the case with GTK. But thats just my opinion.

Another reason the callbacks approach might not be ideal is Rust lifetimes. A lot of GUI frameworks implement a retained-mode API with garbage collection of unused objects, which lets them do whatever they like with callbacks and objects without having to worry about lifetimes. Iced has no such overhead, but has to be clever about the types and API as a result. How would you prove to Rust that all references you use in your callback will be alive for as long as the callback is callable?

**Comment by cryptoquick** [comment]
Echoing all of @twitchyliquid64 's points, Iced's Elm style actually works quite well once enough patterns are learned. I came from mostly React UI, and I learned quite quickly, components were mot the way to go.

I can't speak to how optimal the ZCAs are, nor its approach to type-correctness, but judging by what I've seen so far, with basically zero macro usage, Iced is one of the best and full-featured Rust-idiomatic UI frameworks around.

Just try to roll with it. You'll struggle for about a month, try this and that, but eventually you'll get there. It's a worthwhile approach, even if it's still early days.

**Comment by jgarvin** [comment]
Thanks all for the answers, now that I have a little bit more experience with it I would also add that you don't actually have to do all the steps I listed every time. Technically if you want you can use the same message type for everything but vary values inside, it's just most idiomatic for the message to be an enumeration at the top level. But if there are two very similar actions, it may be clearer to make them alternative data inside the same variant.

**Comment by videni** [comment]
@jgarvin have you ever tried Xielm? here is an example, https://github.com/linebender/xilem/blob/main/xilem/examples/to_do_mvc.rs, apparently, it doesn't have the boilerplate codes as Iced does. I have to say I don't like the Elm approach,  too much pain, recently I built a complex home page with Iced,  here is the [link]( https://github.com/pdf-rs/pdf_render/pull/26)  that contains some thoughts about Iced,  please correct me if am wrong.

**Comment by hecrj** [comment]
@videni Pain is not always a bad sign. I don't see any meaningful arguments made here other than "I don't like it".

**Comment by videni** [comment]
@hecrj , Sorry for the negative feelings; I am just very interested in knowing if there is a better way to structure application logic without those boilerplate works.
