### ISSUE TITLE
Implement Hash & Eq for iced_native::event::Event

### ISSUE THREAD

**Issue by bytebuddha** [hecrj/iced#671]
Hey, great library! I'm wondering if it would be possible to implement `Hash` & `Eq` for iced_native::event::Event. I'm trying to use events as the keys to a HashMap. 

Is this possible?

Would you accept a PR with this change?

**Comment by hecrj** [comment]
Yes! I believe both traits sound reasonable for `Event`.

> I'm trying to use events as the keys to a HashMap.

I am curious about the underlying reason. What do you want to achieve?

**Comment by bytebuddha** [comment]
> I am curious about the underlying reason. What do you want to achieve?

My ultimate goal is to be able to have global keybindings and the ability to bind to certain window events like resize events.
Each string in the config file looks like "control alt p", "shift f1", "resize", etc.. This is mapped to an event and stored in a hashmap with a list of actions to run, when i receive a event from the UI i check this hashmap for a corresponding event and run the actions.

**Comment by bytebuddha** [comment]
I think i found a better way around this. I created an `EventDescriptor` enum that matches the Event enums exactly without any of the data / numbers.

Since the f32's in Event don't implement Hash it cant simply be derived, It's much easier to make a second enum that represents the event.
