### ISSUE TITLE
Can't get buttons to center?

### ISSUE THREAD

**Issue by jgarvin** [hecrj/iced#675]
I'm having trouble understanding how all of the different alignment options interact:

`center_x`
`align_items(iced::Align::Center)`
`width(Length::Fill)`

Some of these you set on columns, and some of them you set on `Container`. I'm not sure what the difference between a container and a row or column is (rows and columns sound like containers to me?). To try and get some buttons to center at the top of the screen I have tried applying many combinations of these to every element of the hierarchy, but I still always end up with the buttons on the left hand side of the screen.

* In general if I want some aspect of the GUI to be centered horizontally within the top level window:, what do I need to do? It doesn't seem sufficient to use any one of these methods by themselves. Nor does it seem sufficient to try to tell every node in the hierarchy on the way down to center and fill.

* When should I be wrapping something in a Container before pushing vs just pushing directly?

Relevant snippet:

```
fn topbar_button<'a>(state: &'a mut button::State, text: &str, page: Page) -> Button<'a, Message> {
    Button::new(
        state,
        Text::new(text).horizontal_alignment(HorizontalAlignment::Center),
    )
    .padding(12)
    .min_width(100)
    .on_press(Message::SetActivePage(page))
    .style(style::Button::Topbar)
}
```

```
impl Sandbox for App {

    // .... snip

    fn view(&mut self) -> Element<Message> {
        let topbar: Element<_> = Row::new()
            .spacing(20)
            .padding(20)
            .push(topbar_button(&mut self.intro_button, "A", Page::A))
            .push(topbar_button(
                &mut self.people_button,
                "B",
                Page::B,
            ))
            .push(topbar_button(
                &mut self.features_button,
                "C",
                Page::C,
            ))
            .push(topbar_button(&mut self.homes_button, "D", Page::D))
            .width(Length::Fill)
            .align_items(iced::Align::Center)
            .into();

        let outer_frame = Column::new()
            .spacing(20)
            .padding(20)
            .align_items(iced::Align::Center)
            .width(Length::Fill)
            .push(topbar)
            .push(Self::view_active_page(&mut self.pages, &self.model));

        let scrollable = Scrollable::new(&mut self.scroll)
            .push(Container::new(outer_frame).width(Length::Fill).center_x());

        scrollable.into()
    }

```

**Comment by hecrj** [comment]
`align_items` defines the alignment on the cross axis of a `Row` or `Column`. In other words, vertical alignment for `Row` and horizontal alignment for `Column`. This is normally useful when you have multiple elements with different lengths in the cross axis.

`Container::center_x` horizontally centers the contents inside the bounds of the container. The `center_y` method works analogously.

It's important to note that if the contents of the `Container` want to fill all the available space, then they will and no alignment will occur. This is what is happening in your snippet. Both the `Column` and `Row` want to fill the available horizontal space.

You could try removing the `width(Length::Fill)` from `topbar` and then decorating it:

```rust
let centered_topbar = Container::new(topbar).width(Length::Fill).center_x();
```

**Comment by jgarvin** [comment]
I see I was too aggressive with using fill. Thanks for the explanation 👍
