### ISSUE TITLE
Tokio 1.0 support pls?

### ISSUE THREAD

**Issue by hlavaatch** [hecrj/iced#679]
Support for Tokio 1.0 should be relatively easy, bump tokio to 1.0 in futures and add tokio-stream 0.1.0 dependency next to it. Maybe make it a feature like the old tokio, over 1.0 lifetime time Stream will get standardized into std and tokio-stream will not be needed anymore

**Comment by yusdacra** [comment]
I have #672 open which addresses this.

**Comment by hlavaatch** [comment]
Ok, no need for this then
