### ISSUE TITLE
Little stupid question about todos example

### ISSUE THREAD

**Issue by Zenthae** [hecrj/iced#682]
it's probably a stupid question, but where is the data saved from the todos example ? i looked in the code and it's talking about a `todos.json` but i wasn't able to find it

**Comment by Zenthae** [comment]
nvm, found it, it's in `AppData`

**Comment by hecrj** [comment]
We use `directories-next` to create a path to the application data directory in a cross-platform way. See the `SavedState::path` method:

https://github.com/hecrj/iced/blob/f8aef03456ecc185098b6305a8cd0e22f5297d06/examples/todos/src/main.rs#L500-L512
