### ISSUE TITLE
Scrolling an image::Viewer inside a Scrollable sends scroll events to both

### ISSUE THREAD

**Issue by agraven** [hecrj/iced#691]
Scrolling on an `image::Viewer` inside a `Scrollable` both zooms the viewer and scrolls the scrollable at the same time. It makes viewers inside scrollables very frustrating to use

**Comment by Eucladia** [comment]
It seems like there was oversight in the image viewer widget and none of the events that the widget handles marks the events as captured <https://github.com/hecrj/iced/blob/master/native/src/widget/image/viewer.rs#L166-L255>.

It should be a trivial fix by returning `event::Status::Captured` in the respective events

**Comment by hecrj** [comment]
Good catch!

I just opened #694 which I believe should fix the issue. Let me know!
