### ISSUE TITLE
Image Viewer should be able to run without handle

### ISSUE THREAD

**Issue by semtexzv** [hecrj/iced#693]
Currently, there is no way to implement lazy loading of images. The Viewer widget should be creatable without an image available.

**Comment by hecrj** [comment]
What would be a use case for this? What do you mean by lazy loading of images? For instance, the `pokedex` example downloads a sprite before displaying it in an `image::Viewer`.

**Comment by semtexzv** [comment]
Yes, in the end I've figured out what I need. 

I'm coming at this from the android side, so there are expectations about widgets, which have persistent state. 

Issue can be closed.
