### ISSUE TITLE
Winit Error when running Example on Ubuntu 19.04

### ISSUE THREAD

**Issue by cetra3** [hecrj/iced#70]
Getting the following error when trying to run `cargo run --example tour` on my Ubuntu 19.04 lappy.

```
[2019-11-25T23:31:50Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
```

**Comment by hecrj** [comment]
Thanks for the report!

I found https://github.com/rust-windowing/winit/issues/748 describing the same issue.

It seems the cause may be that your environment does not support Vulkan. I am working on an alternative for rendering that should fix some of these issues. I hope I can share something soon!

**Comment by cetra3** [comment]
Ah right, I'm surprised since I'm using the proprietary nvidia drivers.  I assume there is a few more packages I would have to install.  I'll have a play around and see if I can get it to work

**Comment by cetra3** [comment]
Ok, looks like it's a nvidia [Optimus silly issue](https://devtalk.nvidia.com/default/topic/1058585/linux/on-optimus-system-vulkan-tries-to-use-integrated-intel-graphics-and-fails-with-a-blank-black-window/).  It tries to load the intel driver for some reason.

For posterity here are the steps I took to diagnose:

* Installed vulkan-tools with `sudo apt install vulkan-tools`
* Ran `vkcube` - noticed it turned out black
* Removed the file at `/usr/share/vulkan/icd.d/intel_icd.x86_64.json`
* Ran `vkcube` again - noticed it worked.

Now the tour works too!

**Comment by swiesend** [comment]
I had this problem together with:
```cargo
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[2021-09-07T11:45:27Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at 'Next frame: Timeout', /home/sebastian/develop/rust/iced/wgpu/src/window/compositor.rs:126:52
```
