### ISSUE TITLE
Support context/popup menus and menu bars

### ISSUE THREAD

**Issue by ColinTimBarndt** [hecrj/iced#704]
As the title already states, it would be nice if iced natively supported context menus, at least for desktop systems. I am currently working on a windows implementation with winapi as an external crate, but I am stuck with how to receive api messages for the window when it is handled by iced. This is my first time working with winapi, so I can't promise anything yet. It would be a very nice addition to have this feature though.

The menu implementation could make use of the messagaging system by letting the developer specify a message that should be dispatched when a menu item was clicked. It could be either added to a dom element (context/popup menu) or to the window itself (menu bar).

**Comment by madsmtm** [comment]
Semi duplicate of #114
