### ISSUE TITLE
freetype-sys  servo-freetype-sys

### ISSUE THREAD

**Issue by edu-live** [hecrj/iced#707]
error: failed to run custom build command for `freetype-sys v0.13.1`
failed to run custom build command for `servo-freetype-sys

failed to run custom build command for `servo-fontconfig-sys v5.1.0`

**Comment by hecrj** [comment]
What are you trying to build? `master` or crates.io version?

**Comment by edu-live** [comment]
LinuxMint
Rust Stable
iced master version

**Comment by edu-live** [comment]
solved.
apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev libfontconfig1-dev
