### ISSUE TITLE
I can't figure out buttons

### ISSUE THREAD

**Issue by 13r0ck** [hecrj/iced#712]
I am a healthy mix of new to Rust and Iced, and I am struggling hard...

I have a struct
```
struct foo {
    vec: Vec<bar>
}
```

I am trying to make n buttons in a row, one for each struct (`bar`) in `foo.vec`.
I have been reading the docs, and looking at the examples particularly [todos](https://github.com/hecrj/iced/tree/master/examples/todos). I have gotten as far as
`Button::new(something, Text::new(bar.name))`
I for the life of me cannot figure out what exactly the `something` is.

I have seen `button::State::new()` but not sure how to get that to work.

Thanks for the help!!!!!

**Comment by 13r0ck** [comment]
I've progressed a bit, the last thing I am confused on is
```
                let tasks: Element<_> = if filtered_tasks.count() > 0 {
                    tasks
                        .iter_mut()
                        .enumerate()
                        .filter(|(_, task)| filter.matches(task))
                        .fold(Column::new().spacing(20), |column, (i, task)| {
                            column.push(task.view().map(move |message| {
                                Message::TaskMessage(i, message)
                            }))
                        })
                        .into()
```
This starts at line 170 in the `todos` example.
I get that this is `push`ed to a `Column` and then again `push`ed into a `Scrollable` to be displayed. Though how does this then become the (i believe) `Row` that is displayed.

I think I need to do something similar, but with buttons.

Thanks!

**Comment by Kaiden42** [comment]
> I have seen button::State::new() but not sure how to get that to work.

That's the button's state. Iced is inspired by Elm, therefore it is split up into the application's state and the view. The view basically don't store any relevant data. Every data is stored in the application's state. Many input widgets like the scrollable, textinput or button have a state. For each button you need a seperate state. I recommend you to store the states of the buttons along with the other data in the vector.

Like this for example:
```Rust
struct foo {
    vec: Vec<(bar, button::State)>
}
```

> I've progressed a bit, the last thing I am confused on is

Yes, that's a little bit confusing for a beginner, so let's break this down.

```Rust
tasks
    .iter_mut()
    .enumerate()
```

This is creating a mutable iterator over the tasks along with the enumerated index. This creates an iterator over a tuple like this: (index, task). The `filter` is just for filtering, we can ignore it for now.

The `fold` is the interesting part here. I don't know if you are familiar with Java for example. The Stream API there has a similar functionality like the Iterators in Rust. The `fold` function is called there `reduce`. Different name, same functionality. The function `fold` is folding the iterator into a result. It takes two argumens the start value and a function. The start value here is a new `Column`. The function takes the result from the previous iteraton (or the start value for the first) and the next element and folds it into the new result.

```Rust
task.view().map(move |message| {
    Message::TaskMessage(i, message)
}
```

A lot of information is hidden here. In the todos example the `Task` struct has it's [own `view` function](https://github.com/hecrj/iced/blob/master/examples/todos/src/main.rs#L283) for creating everything that is needed. For the beginning, you don't need to split up the logic into different parts, but if your application gets more complex I would recommend doing it like the example.

For now, let's just create a simple column containing only the buttons:
```Rust
self.vec.iter_mut().enumerate()
    .fold(Column::new(), |column, (i, (bar, state))| {
        column.push(
            Button::new(state, Text::new(format!("this is button: {}", i)))
                .on_press(Message::ButtonPressed(i))
        )
    })
```

You need to know which button of all the buttons in this column was pressed. Therefore you pass along the index to the message, the button sends when pressed.

But what about this weird `map` in the example? If your application gets larger, you may want to have a different message type for each part of your application. The `map` in the example just _wraps_ the message of the task with a message from the application. Maybe this example [here](https://github.com/Kaiden42/iced_aw/tree/main/examples/web) makes this more clearer to you.

I hope I could clear up some of your ambiguities.

**Comment by 13r0ck** [comment]
@Kaiden42 Thank you very much!
Thank you for teaching me Rust and Iced :)
Your explanation was clear enough that I was also able to use it to build a 2d grid of buttons! 
I hope you have a wonderful week! Thanks again!!!

**Comment by Kaiden42** [comment]
> Your explanation was clear enough that I was also able to use it to build a 2d grid of buttons!

That's great! I am glad I could help.
I wish you a wonderful week too!
