### ISSUE TITLE
I try to execute command in child component

### ISSUE THREAD

**Issue by dancespiele** [hecrj/iced#714]
I try to execute a Command for async function in Iced but look that it only works in parent component, in another component implement looks like doesn't work https://github.com/dancespiele/okspiel/blob/master/src/connect/connect_node.rs#L98

In that case how can I handle an asynchronize action in a child component?

**Comment by hecrj** [comment]
You need to route the `Command` returned by `ConnectNode::update` all the way to your `Application::update`, and return it there.

In other words, [you are dropping the `Command` here](https://github.com/dancespiele/okspiel/blob/fa7c8e3f656ca48d65547aef37a7acc4f2a0acf5/src/main.rs#L45). Instead, you should write something like this:

```rust
    fn update(&mut self, message: Self::Message) -> Command<Self::Message> {
        match message {
            Message::ConnectMessage(connect_node_msg) => {
                self.connect_node.update(connect_node_msg).map(Message::ConnectMessage)
            }
        }
    }
```

**Comment by dancespiele** [comment]
@hecrj I changed that https://github.com/dancespiele/okspiel/blob/master/src/main.rs#L47 however the async function https://github.com/dancespiele/okspiel/blob/master/src/connect/connect_node.rs#L231 is not executed according with the debugging when the button action is triggered

**Comment by hecrj** [comment]
That's still not completely correct. You are discarding the `Command` produced by `ConnectNode::update` and returning `Command::none` instead.

You need to remove the `Command::none` line and the semicolon after the `match` expression. You will end up with the function I wrote above.

**Comment by dancespiele** [comment]
yes thanks I didn't realize before.
