### ISSUE TITLE
Base binary project with Iced as a depedency not compiling on Ubuntu 20.01 X11

### ISSUE THREAD

**Issue by mscofield0** [hecrj/iced#716]
The build fails with the following message:
`error: failed to run custom build command for "x11 v2.18.2"`

**Comment by rnd-ash** [comment]
You are missing some dev dependencies

install the following with apt first:
* libgtk-3-dev
* libx11-dev
* build-essential

**Comment by mscofield0** [comment]
Thanks @rnd-ash, I didn't have `libgtk-3-dev`.
