### ISSUE TITLE
How to subscribe to key combinations

### ISSUE THREAD

**Issue by samyak-jain** [hecrj/iced#718]
I can see that the recommended way to listen to keystrokes is to use subscriptions. However, I can't see any docs/examples on how to subscribe to Key Combinations. Is this possible to do?

My use case is, I want to focus on the next text box when pressing Tab and focus on the previous text box when pressing Shift + Tab. I got the former working but struggling with the latter. 

Just to be clear, I don't want it to work when pressing Shift and then pressing Tab. I only want it to work when pressing Shift + Tab in quick succession like the way most applications behave. So just keeping track of the last event won't work.

**Comment by hecrj** [comment]
The `keyboard::Event::KeyPressed` has a `modifiers` field that you can leverage. For instance:

```rust
use iced::keyboard;
use iced::Subscription;
use iced_native::event::{self, Event};
use iced_native::subscription;

pub enum Message {
    FocusPrevious,
    FocusNext,
}

fn subscription() -> Subscription<Message> {
    subscription::events_with(|event, status| match (event, status) {
        (Event::Keyboard(keyboard_event), event::Status::Ignored) => {
            match keyboard_event {
                keyboard::Event::KeyPressed {
                    key_code: keyboard::KeyCode::Tab,
                    modifiers,
                } => Some(if modifiers.shift {
                    Message::FocusPrevious
                } else {
                    Message::FocusNext
                }),
                _ => None,
            }
        }
        _ => None,
    })
}
```

**Comment by samyak-jain** [comment]
Let me know if I'm misunderstanding what you are doing. But to me it looks like your code would FocusPrevious simply by pressing shift? I would only want it to do that when I do Shift + Tab. 
When I'm logging events in my code, every time 2 events are logged when I press Shift + Tab. The first event has modifier as shift but keycode is not Tab. The second event has keycode as Tab but there is no modifier. 
To use them together I would need to keep track of 2 events at a time and also the duration between each event since I don't want it to focus if Tab is pressed 10 seconds after Shift. This would quickly get very hairy with even slightly more complex combinations.

**Comment by hecrj** [comment]
The code I wrote should produce a `FocusPrevious` when the `Tab` key is pressed and the Shift modifier is also pressed.

**Comment by samyak-jain** [comment]
Ah. Makes sense. This fixes my issue. Thanks!

**Comment by parker-research** [comment]
It seems that this approach no longer works exactly. Is there an update for 0.13+?

Edit: The [modal guide](https://github.com/iced-rs/iced/blob/master/examples/modal/src/main.rs) helped a lot.

**Comment by pml68** [comment]
You grab an `on_key_press` `Subscription` and you filter for e.g. `modifiers.command()`
