### ISSUE TITLE
Nested buttons

### ISSUE THREAD

**Issue by ruza-net** [hecrj/iced#724]
Is it possible to nest buttons in such a way that the inner buttons are still clickable?

For example, can I do something analogous to this:
```rust
Button::new(
    ...,
    Row::new()
        .push(
            Button::new(..., Text::new("Foo"))
                .on_press(Msg::Foo)
        )
        .push(Text::new("Bar")),
)
.on_press(Msg::Bar)
```

... and get this behaviour: when the user clicks button with label "Foo", `Msg::Foo` is emitted, but when he clicks anywhere outside "Foo" and inside "Bar", `Msg::Bar` is emitted?

Note that hovering still seems to work (when I hover "Foo", both "Foo" and "Bar" change style to hovered).

**Comment by cossonleo** [comment]
master already  implemented

**Comment by ruza-net** [comment]
I see, thanks!
