### ISSUE TITLE
Text doesn't render until first input event

### ISSUE THREAD

**Issue by ceranco** [hecrj/iced#73]
Hi,
When running the sample counter application, it seems that the text only shows after the first input event:
![bug](https://user-images.githubusercontent.com/22302978/69607486-0401fa80-102e-11ea-8fab-41979c14f33f.gif)

As you can see, the text only appears after the first time I move the mouse. I can also confirm that pressing a key on the keyboard has the same effect.

As an aside, I've been following Iced for quite some time and am really impressed with how far it has progressed, thanks for such an awesome library 😄

**Comment by hecrj** [comment]
Thanks for the report and the kind words!

I cannot seem to reproduce it on my system. Could you try to run one of the examples in [`wgpu_glyph`] and see if the same issue happens there?

Also, adding [`env_logger`] and runing it with `RUST_LOG=warn` may give us some hints of what is happening. I suspect the glyph cache may not be getting initialized until the second redraw.

[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
[`env_logger`]: https://docs.rs/env_logger/0.7.1/env_logger/

**Comment by ceranco** [comment]
I forgot to say that the problem happen on a Windows 10 machine with Intel integrated graphics,
and the code can be seen here: https://github.com/ceranco/hello-iced.

I ran the `hello` example of **wgpu** and the same issue didn't happen there.

Running with `RUST_LOG=warn` show anything, but with `RUST_LOG=info` shows the following:

> [2019-11-27T07:13:50Z INFO  winit::platform_impl::platform::window] Guessed window DPI factor: 1
> [2019-11-27T07:13:50Z INFO  gfx_backend_dx11] DXGI version: Dxgi1_5
> [2019-11-27T07:13:50Z INFO  gfx_backend_dx11] AdapterInfo {
>         name: "Intel(R) HD Graphics 530",
>         vendor: 32902,
>         device: 6418,
>         device_type: DiscreteGpu,
>     }
> [2019-11-27T07:13:50Z INFO  gfx_backend_dx11] AdapterInfo {
>         name: "Microsoft Basic Render Driver",
>         vendor: 5140,
>         device: 140,
>         device_type: VirtualGpu,
>     }
> [2019-11-27T07:13:50Z INFO  wgpu_native::instance] Adapter Vulkan AdapterInfo { name: "Intel(R) HD Graphics 530", vendor: 32902, device: 6418, device_type: IntegratedGpu }
> [2019-11-27T07:13:50Z INFO  wgpu_native::device] creating swap chain SwapChainDescriptor { usage: OUTPUT_ATTACHMENT, format: Bgra8UnormSrgb, width: 400, height: 400, present_mode: Vsync }

and with `RUST_LOG=debug`:

> [2019-11-27T07:16:01Z INFO  winit::platform_impl::platform::window] Guessed window DPI factor: 1
> [2019-11-27T07:16:01Z INFO  gfx_backend_dx11] DXGI version: Dxgi1_5
> [2019-11-27T07:16:01Z INFO  gfx_backend_dx11] AdapterInfo {
>         name: "Intel(R) HD Graphics 530",
>         vendor: 32902,
>         device: 6418,
>         device_type: DiscreteGpu,
>     }
> [2019-11-27T07:16:01Z INFO  gfx_backend_dx11] AdapterInfo {
>         name: "Microsoft Basic Render Driver",
>         vendor: 5140,
>         device: 140,
>         device_type: VirtualGpu,
>     }
> [2019-11-27T07:16:01Z INFO  wgpu_native::instance] Adapter Vulkan AdapterInfo { name: "Intel(R) HD Graphics 530", vendor: 32902, device: 6418, device_type: IntegratedGpu }
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_descriptor_set_layout [DescriptorSetLayoutBinding { binding: 0, descriptor_type: UNIFORM_BUFFER, descriptor_count: 1, stage_flags: VERTEX, p_immutable_samplers: 0x0 }, DescriptorSetLayoutBinding { binding: 1, descriptor_type: SAMPLER, descriptor_count: 1, stage_flags: FRAGMENT, p_immutable_samplers: 0x0 }, DescriptorSetLayoutBinding { binding: 2, descriptor_type: SAMPLED_IMAGE, descriptor_count: 1, stage_flags: FRAGMENT, p_immutable_samplers: 0x0 }]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_pipeline_layout [0x1c05bafde28]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_graphics_pipeline GraphicsPipelineDesc { shaders: GraphicsShaderSet { vertex: EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7bb28 }, specialization: Specialization { constants: [], data: [] } }, hull: None, domain: None, geometry: None, fragment: Some(EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7bd28 }, specialization: Specialization { constants: [], data: [] } }) }, rasterizer: Rasterizer { polygon_mode: Fill, cull_face: NONE, front_face: Clockwise, depth_clamping: false, depth_bias: None, conservative: false }, vertex_buffers: [VertexBufferDesc { binding: 0, stride: 52, rate: Instance(1) }], attributes: [AttributeDesc { location: 0, binding: 0, element: Element { format: Rgb32Sfloat, offset: 0 } }, AttributeDesc { location: 1, binding: 0, element: Element { format: Rg32Sfloat, offset: 12 } }, AttributeDesc { location: 2, binding: 0, element: Element { format: Rg32Sfloat, offset: 20 } }, AttributeDesc { location: 3, binding: 0, element: Element { format: Rg32Sfloat, offset: 28 } }, AttributeDesc { location: 4, binding: 0, element: Element { format: Rgba32Sfloat, offset: 36 } }], input_assembler: InputAssemblerDesc { primitive: TriangleStrip, with_adjacency: false, restart_index: None }, blender: BlendDesc { logic_op: None, targets: [ColorBlendDesc { mask: RED | GREEN | BLUE | ALPHA | COLOR | ALL, blend: Some(BlendState { color: Add { src: SrcAlpha, dst: OneMinusSrcAlpha }, alpha: Add { src: One, dst: OneMinusSrcAlpha } }) }] }, depth_stencil: DepthStencilDesc { depth: None, depth_bounds: false, stencil: None }, multisampling: None, baked_states: BakedStates { viewport: None, scissor: None, blend_color: None, depth_bounds: None }, layout: PipelineLayout { raw: 0x1c05ba9c918 }, subpass: Subpass { index: 0, main_pass: RenderPass { raw: 0x1c05bac6008, clear_attachments_mask: 0 } }, flags: (empty), parent: None }
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_descriptor_set_layout [DescriptorSetLayoutBinding { binding: 0, descriptor_type: UNIFORM_BUFFER, descriptor_count: 1, stage_flags: VERTEX, p_immutable_samplers: 0x0 }]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_pipeline_layout [0x1c05dcfde38]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_graphics_pipeline GraphicsPipelineDesc { shaders: GraphicsShaderSet { vertex: EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7c9a8 }, specialization: Specialization { constants: [], data: [] } }, hull: None, domain: None, geometry: None, fragment: Some(EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7cba8 }, specialization: Specialization { constants: [], data: [] } }) }, rasterizer: Rasterizer { polygon_mode: Fill, cull_face: NONE, front_face: Clockwise, depth_clamping: false, depth_bias: None, conservative: false }, vertex_buffers: [VertexBufferDesc { binding: 0, stride: 8, rate: Vertex }, VertexBufferDesc { binding: 1, stride: 36, rate: Instance(1) }], attributes: [AttributeDesc { location: 0, binding: 0, element: Element { format: Rg32Sfloat, offset: 0 } }, AttributeDesc { location: 1, binding: 1, element: Element { format: Rg32Sfloat, offset: 0 } }, AttributeDesc { location: 2, binding: 1, element: Element { format: Rg32Sfloat, offset: 8 } }, AttributeDesc { location: 3, binding: 1, element: Element { format: Rgba32Sfloat, offset: 16 } }, AttributeDesc { location: 4, binding: 1, element: Element { format: R32Sfloat, offset: 32 } }], input_assembler: InputAssemblerDesc { primitive: TriangleList, with_adjacency: false, restart_index: None }, blender: BlendDesc { logic_op: None, targets: [ColorBlendDesc { mask: RED | GREEN | BLUE | ALPHA | COLOR | ALL, blend: Some(BlendState { color: Add { src: SrcAlpha, dst: OneMinusSrcAlpha }, alpha: Add { src: One, dst: OneMinusSrcAlpha } }) }] }, depth_stencil: DepthStencilDesc { depth: None, depth_bounds: false, stencil: None }, multisampling: None, baked_states: BakedStates { viewport: None, scissor: None, blend_color: None, depth_bounds: None }, layout: PipelineLayout { raw: 0x1c05bac64d8 }, subpass: Subpass { index: 0, main_pass: RenderPass { raw: 0x1c05bac6008, clear_attachments_mask: 0 } }, flags: (empty), parent: None }
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_descriptor_set_layout [DescriptorSetLayoutBinding { binding: 0, descriptor_type: UNIFORM_BUFFER, descriptor_count: 1, stage_flags: VERTEX, p_immutable_samplers: 0x0 }, DescriptorSetLayoutBinding { binding: 1, descriptor_type: SAMPLER, descriptor_count: 1, stage_flags: FRAGMENT, p_immutable_samplers: 0x0 }]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_descriptor_set_layout [DescriptorSetLayoutBinding { binding: 0, descriptor_type: SAMPLED_IMAGE, descriptor_count: 1, stage_flags: FRAGMENT, p_immutable_samplers: 0x0 }]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_pipeline_layout [0x1c05bb10de8, 0x1c05bb0bf78]
> [2019-11-27T07:16:01Z DEBUG gfx_backend_vulkan::device] create_graphics_pipeline GraphicsPipelineDesc { shaders: GraphicsShaderSet { vertex: EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7b528 }, specialization: Specialization { constants: [], data: [] } }, hull: None, domain: None, geometry: None, fragment: Some(EntryPoint { entry: "main", module: ShaderModule { raw: 0x1c05ba7af28 }, specialization: Specialization { constants: [], data: [] } }) }, rasterizer: Rasterizer { polygon_mode: Fill, cull_face: NONE, front_face: Clockwise, depth_clamping: false, depth_bias: None, conservative: false }, vertex_buffers: [VertexBufferDesc { binding: 0, stride: 8, rate: Vertex }, VertexBufferDesc { binding: 1, stride: 16, rate: Instance(1) }], attributes: [AttributeDesc { location: 0, binding: 0, element: Element { format: Rg32Sfloat, offset: 0 } }, AttributeDesc { location: 1, binding: 1, element: Element { format: Rg32Sfloat, offset: 0 } }, AttributeDesc { location: 2, binding: 1, element: Element { format: Rg32Sfloat, offset: 8 } }], input_assembler: InputAssemblerDesc { primitive: TriangleList, with_adjacency: false, restart_index: None }, blender: BlendDesc { logic_op: None, targets: [ColorBlendDesc { mask: RED | GREEN | BLUE | ALPHA | COLOR | ALL, blend: Some(BlendState { color: Add { src: SrcAlpha, dst: OneMinusSrcAlpha }, alpha: Add { src: One, dst: OneMinusSrcAlpha } }) }] }, depth_stencil: DepthStencilDesc { depth: None, depth_bounds: false, stencil: None }, multisampling: None, baked_states: BakedStates { viewport: None, scissor: None, blend_color: None, depth_bounds: None }, layout: PipelineLayout { raw: 0x1c05bb25628 }, subpass: Subpass { index: 0, main_pass: RenderPass { raw: 0x1c05bac6008, clear_attachments_mask: 0 } }, flags: (empty), parent: None }
> [2019-11-27T07:16:01Z INFO  wgpu_native::device] creating swap chain SwapChainDescriptor { usage: OUTPUT_ATTACHMENT, format: Bgra8UnormSrgb, width: 400, height: 400, present_mode: Vsync }
> [2019-11-27T07:16:01Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:02Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing
> [2019-11-27T07:16:03Z DEBUG iced_wgpu::renderer] Drawing

**Comment by ceranco** [comment]
This seems to have been fixed with the latest version of `master` 😄
