### ISSUE TITLE
There are many structs you cannot see documentation for on docs.rs

### ISSUE THREAD

**Issue by Ploppz** [hecrj/iced#732]
For example https://docs.rs/iced/0.2.0/iced/type.Element.html
Docs provide no information at all about this important type.
Not sure why it is so and what it takes to fix it.

**Comment by samyak-jain** [comment]
Looks like a duplicate of this issue https://github.com/hecrj/iced/issues/340

You can find the actual element docs here: https://docs.rs/iced_native/0.3.0/iced_native/struct.Element.html
