### ISSUE TITLE
Scrollbar rendered behind the scrollable content

### ISSUE THREAD

**Issue by Kaiden42** [hecrj/iced#765]
I've recently updated to the latest head of the master branch and noticed some change in the rendering of the scrollbar.
It looks like it is now rendered behind the content of the scrollable.

Something between [before](https://github.com/hecrj/iced/commit/12c0c18d662d2b817b559b94c71d18e122c76990) and [now](https://github.com/hecrj/iced/commit/a74974a8e4d8afc72c33434a22df74c3582b78a8) changed this behavior. Anyone else noticed this?

Before: 
![scrollbar_before](https://user-images.githubusercontent.com/26521388/110143946-1691e480-7dd8-11eb-8ca8-a71ac087ab63.png)

Now:
![scrollbar_now](https://user-images.githubusercontent.com/26521388/110143968-1bef2f00-7dd8-11eb-9c30-9650cfa24d0e.png)

**Comment by hecrj** [comment]
The new logic reuses the old layer when after a `Clip` primitive is processed. It looks like we may need to issue a new `Clip` primitive just for the scrollbar.
