### ISSUE TITLE
How can you resize the application at runtime?

### ISSUE THREAD

**Issue by TimUntersberger** [hecrj/iced#767]
I am trying to grow/shrink the window whenever the content changes. Is this currently possible? Also I tried to look through the source code to fix #756, but I can't find where you are actually rendering anything? Any pointers?

**Comment by grv07** [comment]
I think [this](https://docs.rs/iced/0.2.0/iced/trait.Application.html#method.scale_factor) will help you :).

**Comment by TimUntersberger** [comment]
Example for clarification:

I want to be able to change the window size from `(500, 100)` to `(500, 200)` when some state changes.
