### ISSUE TITLE
Suggestions needed for integrating 3D render

### ISSUE THREAD

**Issue by KHN190** [hecrj/iced#778]
I wrote a 3D renderer based on the same version of wgpu, and I need to render it to an iced window.

The 3D renderer now renders to a winit window:

```rust
pub struct Renderer {
    pub size: winit::dpi::PhysicalSize<u32>,
    device: wgpu::Device,
    queue: wgpu::Queue,
    swap_chain: wgpu::SwapChain,
    render_pipeline: wgpu::RenderPipeline, // textured pipeline for mesh
    uniforms: Uniforms,
    scene: Scene,
    depth_texture: DepthTexture,
}

impl Renderer {
    pub fn new(
        device: wgpu::Device,
        queue: wgpu::Queue, 
        size: winit::dpi::PhysicalSize<u32>,
        swap_chain: wgpu::SwapChain,
    ) -> Result<Self> {
    /* render stuff */
}
```

The current render target is from wgpu swap_chain:

```rust
// in renderer, it outputs to winit window
let render_target = &self.swap_chain.get_current_frame()?.output.view;
```

If I want to make it renders to iced, I have 2 solutions:

1. reuse iced low level `device` + `queue` + `swap_chain`, so I can directly output to iced render target
2. create my own gpu device, render to an image in memory, copy the buffer to iced widget, maybe need a hack from winit side

Am I doing it right? By searching iced graphics & wgpu docs, I didn't see things I need. What is intended to integrate with iced frontend?

**Comment by rademonster** [comment]
How did you end up doing this?

**Comment by KHN190** [comment]
@rademonster Basically the same as examples/integration.rs showed. I moved the pipeline shared states to a global struct, so my 3D render engine and Iced share them. You can find my solution [here](https://github.com/LuciEngine/Lucien/blob/master/app/src/application.rs#L68), of course, the example also helps.
