### ISSUE TITLE
Image from memory doesn't display

### ISSUE THREAD

**Issue by KHN190** [hecrj/iced#779]
In [this pull](https://github.com/hecrj/iced/pull/90) it creates an `iced::Image` from memory. I have the image as:

```rust
let raw = block_on(renderer.as_rgba()).unwrap();
let img = iced::image::Handle::from_memory(raw.to_vec());

raw.save("cube.png").unwrap(); // successful

let im = iced::Image::new(img)
    .width(Length::Units(size[0] as u16))
    .height(Length::Units(size[1] as u16));
```

Container code is:

```rust
let content = Column::new()
    .padding(20)
    .spacing(20)
    .max_width(500)
    .align_items(Align::Start)
    .push(im)
    .push(Text::new("Render image using 3D renderer."));
```

The text displays just well, but the image is blank (white).

Even some hack doesn't make it work:

```rust
let mut hack = raw.to_vec();
for i in 0..hack.len() {
    hack[i] = (i as u8) % 255;
}
let img = iced::image::Handle::from_memory(hack);
```

it only displays if load directly from a file:

```rust
let im = Image::new("cube.png");
```

There might be a bug in `from_memory`?

**Comment by KHN190** [comment]
Though the Pokemon example makes use of [viewer](https://github.com/hecrj/iced/blob/master/native/src/widget/image/viewer.rs), it doesn't appear in `iced_native` as an external crate. The example uses a local path to load the module.

**Comment by KHN190** [comment]
Further investigation using a new project shows the PR was not integrated into v0.2.0, [the example script](https://github.com/hecrj/iced/tree/master/examples/pokedex) doesn't compile with `iced = { version = "0.2.*", features = ["image", "debug", "tokio_old"] }` due to change in `update` function and `viewer` module missing. For my case it should be solved using dev branch from GitHub, but it would be great if it can reflect in a recent iced version.

**Comment by 13r0ck** [comment]
Hecrj has said that he wants to increase the frequency of releases, but 0.3 will likely still be a while. My Iced project just runs on the master branch anyway, and breaking changes are quite rare.
