### ISSUE TITLE
When is new release planned?

### ISSUE THREAD

**Issue by casperstorm** [hecrj/iced#805]
Hi @hecrj,

As always, thanks for Iced. We have run into a issue where Apple M1 can't build our project [Ajour](https://github.com/ajour/ajour) because of winit 0.23.0 in your latest [0.2.0](https://github.com/hecrj/iced/releases/tag/0.2.0) - I see master is targeting 0.24.0 but since we are dependent on being able to ship to [crates.io](https://crates.io/crates/ajour) we can't use a git ref as version.

Do you have any plans for when you will be doing the next release?

Best,
Casper

**Comment by hecrj** [comment]
I just keep pushing it back all the time 😅

I wanted to merge some great PRs that have been open for a while. But I think it may be worth it to just wrap up a release already and then release again in a couple weeks, if necessary.

I believe it should mostly be a matter of coming up with the `CHANGELOG` for `0.3.0`. I'll get to it soon.

**Comment by casperstorm** [comment]
Thanks for the response, @hecrj.
