### ISSUE TITLE
Unexpected z-order of text in Primitive::Clip

### ISSUE THREAD

**Issue by PolyMeilex** [hecrj/iced#807]
After this commit: https://github.com/hecrj/iced/commit/5e2743361bf0a2e10c0e14638a9b2818c9e5e364
I'm unable to put text on top of `Primitive::Clip`
### Example
As an example I modified `iced_graphics` build in button renderer, so that `Primitive::Quad` is wrapped in `Primitive::Clip` like so [commit](https://github.com/PolyMeilex/iced/commit/33a44cf8c7b9952133185224fc9964a66fc15562)

Before commit `5e27433` it used to look like this:
![img](https://i.imgur.com/NaemROt.png)
Now it looks like this:
![img](https://i.imgur.com/3XJHGY7.png)

No matter what I try, I can't find a way to display text on top of the background, like it used to be. Did I miss something? Is this intended behavior?

**Comment by hecrj** [comment]
A `Clip` primitive will create a new rendering layer. If you want text primitives to be rendered on top of the primitives of this layer, you will need to add them as contents of the `Clip` primitive.

**Comment by PolyMeilex** [comment]
Works like a charm, thank you!
