### ISSUE TITLE
Increased CPU usage when interacting with other non-iced windows

### ISSUE THREAD

**Issue by Shootertrex** [hecrj/iced#81]
When running the examples from the repo (master branch hash 811d8b9) compiled to release, I noticed that the CPU usage for that process increase to 5-10% while interacting with other windows. Examples are moving my mouse along my dock, moving my mouse along files in my file browser, and resizing a different window. All of those actions become choppy and slow as well. When the iced example is closed, those actions return to normal. The idle CPU usage of the iced process is very low otherwise.

I'm not quite sure how the iced process is being affected by doing these unrelated things.

System information:
Manjaro Linux, kernel 5.3.12
KDE Plasma 5.17.3
Rust 1.39

If there's further information I can provide, let me know.

**Comment by hecrj** [comment]
Yes, we are currently processing all the events and redrawing even if the window is not focused or the mouse is out of bounds.

This should be an easy fix. Thank you for report!

**Comment by hecrj** [comment]
I have implemented a (partial) fix in #84.

**Comment by Shootertrex** [comment]
Thank you for the quick turn around time! I just tested out that branch, and things are working smoothly.
