### ISSUE TITLE
No instructions how to turn on performance overlay

### ISSUE THREAD

**Issue by arthrp** [hecrj/iced#811]
Readme mentions a handy feature of performance overlay. However the [link](https://gfycat.com/incredibledarlingbee) just points to the gif and there're no instructions how to actually turn it on.

**Comment by Songtronix** [comment]
https://github.com/hecrj/iced/blob/master/Cargo.toml#L36

**Comment by hecrj** [comment]
It's in the documentation:

https://github.com/hecrj/iced/blob/6b4bf34bf94eed091eb89efa1bbb14e6bc68883e/src/application.rs#L20-L21
