### ISSUE TITLE
error: failed to select a version for `wasm-bindgen`

### ISSUE THREAD

**Issue by scrubjay55** [hecrj/iced#812]
i am trying to make a fetch. 
i have these as dependencies:
```
[dependencies]
iced = { version ="0.3", features = ["async-std", "debug"] }

wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"]  }
js-sys = "0.3.5"
wasm-bindgen-futures = "0.4.23"
serde = { version = "1.0.80", features = ["derive"] }
serde_derive = "^1.0.59"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
]
```

but I keep getting this error when i run `cargo update`:

```
> cargo update
    Updating crates.io index
error: failed to select a version for `wasm-bindgen`.
    ... required by package `wgpu v0.7.0`
    ... which is depended on by `iced_wgpu v0.4.0`
    ... which is depended on by `iced v0.3.0`
    ... which is depended on by `gui v0.1.0 (..)`
versions that meet the requirements `=0.2.69` are: 0.2.69

all possible versions conflict with previously selected packages.

  previously selected package `wasm-bindgen v0.2.73`
    ... which is depended on by `js-sys v0.3.50`
    ... which is depended on by `wasm-bindgen-futures v0.4.23`
    ... which is depended on by `gui v0.1.0 (..)`

failed to select a version for `wasm-bindgen` which could resolve this conflict
```

from i what i decipher from this, iced_wgpu depends on v0.2.69 of wasm-bindgen. but in order for me to make a fetch i need the `futures_0_3` feature from `wasm-bindgen-futures` which is available in wasm-bindgen v0.2.73.

**Comment by taiki-e** [comment]
This is because [wgpu pins the wasm-bindgen version to 0.2.69](https://crates.io/crates/wgpu/0.7.1/dependencies).
Try the master branch of wgpu:
```toml
[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "41f44da" }
```

**Comment by scrubjay55** [comment]
Is there any other way to make a asynchronous http request though that doesn't depend on these?

**Comment by 13r0ck** [comment]
Just checking the basics, would a [Command](https://docs.rs/iced/0.3.0/iced/struct.Command.html) or [Subscription](https://docs.rs/iced/0.3.0/iced/type.Subscription.html) solve your problem?

**Comment by scrubjay55** [comment]
I dont think they do. The issue is not only about the request being asynchronous. Afaik I need these crates to make a fetch from inside webassembly. Anyways, I guess I will just wait for them not to pin the older versions of wasm-bindgen.
