### ISSUE TITLE
Avoid debug in messages

### ISSUE THREAD

**Issue by Yuri6037** [hecrj/iced#814]
In some application it's not possible to debug messages because the message type may wrap external messages which are not debuggable.

Currently one must create a useless type of message to abstract this and implement a fake useless debug for it.

Could you consider removing dependency over Debug or make it optional?

**Comment by 13r0ck** [comment]
Can you [impl Debug manually](https://doc.rust-lang.org/std/fmt/trait.Debug.html) for your type, and just set a default value for the types that are not "debug-able"?

**Comment by Yuri6037** [comment]
That's what I'm doing implementing a empty function which panics in case you call it.

That is however amazingly annoying, as this means that I can't use types from my API as I need to use custom types which does the exact same but have an annoying panicing function.

Can't you just get rid of this requirement? It's just an absolute pain.

**Comment by hecrj** [comment]
I don't see how a `Message`, which is meant to consist only of pure data representing a real application event, could not implement `Debug` properly.

Generally, `Debug` should be implemented everywhere. Why would a type not be able to implement it?

**Comment by Yuri6037** [comment]
Let me give you 2 reasons:
1- It's not automatically implemented
2- It does not make sense to require Debug for internal message that are obviously not intended to be printed

**Comment by hecrj** [comment]
`Debug` is easily derivable most of the time.

Messages are intended to be printed and are meant to be THE source of truth for debugging pruposes. In fact, we have a `debug` feature that prints them on screen.

**Comment by Yuri6037** [comment]
Well I never intended to print any of my internal messages.

**Comment by hecrj** [comment]
`iced` only knows about the outermost `Message` at the `Application` level. I'm not sure why you think you need to implement `Debug` for all of your internal messages.

**Comment by Yuri6037** [comment]
If I link one of my message enum or struct as an argument of one of my master message, I get the exact same error that requires implementing Debug and that is the annoying part. Iced requires EVERY single possible types related in some way to the Message type to implement Debug, which forces me to either use a hack with a handle generator or implement a useless Debug intended to throw panic.

I can already tell you that I use both methods, the hack and the panic.

If you need more information about my architecture, here:
- Consider 2 threads: M and W where M stands for master/main and W stands for worker
- Consider 2 async channels: CM, CW
- CM and CW uses internal messages for comunication which are not intended to be printed

Thread M
- M initializes W
- M initializes the GUI using `impl Application`
- The GUI provides a subscription to comunicate with W
- The GUI subscription keeps awaiting on the read endpoint of CW and wraps returned messages into an Application root Message
- The GUI asks user for input and sends information through CM
- M waits for GUI to shut down
- M joins W and waits for W to finish
- M terminates the program with an exit code returned by W

Thread W
- Computes state
- Sends a message through CW to confirm the new state
- Waits for further instruction from CM
- Continue with more processing
- Eventually W finishes and sends a last message through CW to confirm finish state or error state

**Comment by hecrj** [comment]
Any reason you can't write a custom `Debug` implementation for the master `Message`? If you don't care about it, you can simply leave it empty and forget about it.

**Comment by Yuri6037** [comment]
```
Any reason you can't write a custom Debug implementation for the master Message? If you don't care about it, you can simply leave it empty and forget about it.
```

Well who talks about the master Message. Of course I can #derive debug it that's not the part I was talking about. I'm talking about internal messages. Ex: thread exchange messages.

```
How did you arrive to this conclusion?
```

Because when I do otherwise it keeps throwing compile errors.

**Comment by hecrj** [comment]
You can write your `Message` like:

```rust
pub enum Message {
    Internal(InternalMessage),
}

impl std::fmt::Debug for Message {
    // ...
}

enum InternalMessage {
    // ...
}
```

Here, `InternalMessage` doesn't need to implement `Debug` at all.

**Comment by Yuri6037** [comment]
You mean the derive macro is defective?

**Comment by hecrj** [comment]
The derive macro is not defective. It's just that it can only be used when all the internal types are debuggable. You are meant to use a custom implementation if that is not the case.
