### ISSUE TITLE
Access to raw window handle (windows)

### ISSUE THREAD

**Issue by tarkah** [hecrj/iced#822]
It'd be great if we could access the raw window handle of the underlying winit window within the Application.

We've successfully implemented a system tray for windows alongside our iced application (yay 0.3 w/ `should_exit` and `exit_on_close_request`, we can now do "close to tray"... would be nice if we could hook into Minimize as well). 

However, we had to jump through some hoops on Windows using [EnumWindows](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumwindows) to get the iced underlying window handle so we could perform hide / show [ShowWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow) for "closing to system tray" functionality.

Maybe this can be broadcast as a [window event](https://docs.rs/iced_native/0.4.0/iced_native/window/enum.Event.html)? That'd allow us to easily communicate it back to our tray thread.

**Comment by hecrj** [comment]
I'd say we should avoid exposing the internals of the library.

We should try to tackle use cases directly instead. What would it take to satisfy your minimize use case? Can you elaborate a bit on what you need?

**Comment by tarkah** [comment]
We successfully implemented "close to system tray" with the `should_exit`, `exit_on_close_request`,  `window::Event::CloseRequested` & #825 changes. However, it'd be nice to make it "minimize to system tray".

So maybe the same options but for minimize?

**Comment by Trojanking123** [comment]
> 

i am new to iced,  i want to know how did the `close to system tray` implemented by iced.  After your pr, we could hidden the window, but i  still dont know how to mak a `tray`. thx.

**Comment by tarkah** [comment]
@Trojanking123 Implementing tray support is not something provided by winit or iced. There is no great prebuilt solution in the Rust community that I found when I last checked.

In Ajour, I implemented it ourselves for only Windows using the win32 API. You can checkout https://github.com/ajour/ajour to see how we implemented and integrated with Iced.

**Comment by Trojanking123** [comment]
thx, I will try it.
