### ISSUE TITLE
How to set the proportions?

### ISSUE THREAD

**Issue by Flone-dnb** [hecrj/iced#837]
I could not find it myself, is there a way to set the per element proportions in containers?
For example, I have this code:
```
let top = Row::new()
        .align_items(Align::Center)
        .padding(10)
        .push(Text::new("Text 1").color(Color::WHITE))
        .push(Text::new("Text 2").color(Color::WHITE));
```
I want "Text 1" to fill 20% of the row and "Text 2" to fill 80% of the row. How can I do that?

**Comment by 13r0ck** [comment]
`.width(Length::FillPortion(x))` where x is the ratio.

**Comment by Flone-dnb** [comment]
Thanks!
