### ISSUE TITLE
PickList triangle icon overlaps text

### ISSUE THREAD

**Issue by Ploppz** [hecrj/iced#879]
![19 Thursday-slop0209](https://user-images.githubusercontent.com/4773287/118150158-880e9480-b412-11eb-87e7-13ace04bd760.png)

![19 Thursday-slop0212](https://user-images.githubusercontent.com/4773287/118150154-8775fe00-b412-11eb-8404-e5ee2489025a.png)

I don't know if it has to do with the font, which is NerdFont (Agave). In the case of two words, it seems like it's too late to break into two lines:
![19 Thursday-slop0742](https://user-images.githubusercontent.com/4773287/118150636-0f5c0800-b413-11eb-93db-a75e1cf6fc53.png)
![19 Thursday-slop0734](https://user-images.githubusercontent.com/4773287/118150638-0f5c0800-b413-11eb-8667-e701b9aaed6e.png)

**Comment by 13r0ck** [comment]
You can just increase the width of the picklist

**Comment by Ploppz** [comment]
Yes but it seems like a bug to me because there is a mechanism in place to break into multiple lines if it overflows, but it kicks in too "late" (in terms of width).

**Comment by Ploppz** [comment]
Besides, if I want to use `Length::Shrink` it will consistently overlap
