### ISSUE TITLE
WGPU 0.9 breaks Image rendering [AMD Integrated]

### ISSUE THREAD

**Issue by Songtronix** [hecrj/iced#933]
![grafik](https://user-images.githubusercontent.com/18618951/123539978-c5b64b00-d73c-11eb-90fe-4439c2f22b24.png)

Confirmed that since commit c70f90f3206f7f5176831b7896d8acc147dd2c53 this behaviour occurs and beforehand everything works as expected. Don't know if this is wgpu or iced related.

## System

OS: Windows 10
CPU: Ryzen 5 4500U
GPU: Radeon Graphics (Integrated)

## Logs
[logs.txt](https://github.com/hecrj/iced/files/6721363/logs.txt)

## Fix

Fixed by #1000

**Comment by PolyMeilex** [comment]
I had similar problem in [Neothesia](https://github.com/PolyMeilex/Neothesia) (on AMD cards), but after #1000 it works as expected

**Comment by Songtronix** [comment]
Confirmed that master still contains this issue and that #1000 fixes it 👍

**Comment by PolyMeilex** [comment]
Thank you for checking, so it was probably the same issue that my project encountered.
