### ISSUE TITLE
Is it possible to create resizable "panel / column"?

### ISSUE THREAD

**Issue by barvirm** [hecrj/iced#938]
Here is an example: https://kcmr.github.io/resizable-panels/components/resizable-panels/demo/
I don't need resizable content inside.

**Comment by Kaiden42** [comment]
You could use the PaneGrid in Iced for this. However, I found the PaneGrid a bit too much, moreover it adds too much overhead as it wants to own the status of the content of the panels themselves. Accordingly, I just recently developed my own [Split](https://github.com/iced-rs/iced_aw/tree/main/examples/split) widget. You can find it in the [iced_aw](https://github.com/iced-rs/iced_aw) repositiory.

**Comment by barvirm** [comment]
@Kaiden42 Thank you so much! This is exactly what I was looking for.

**Comment by Kaiden42** [comment]
There are still some small bugs, but the PR is on it's way.
