### ISSUE TITLE
graphic requirements..?

### ISSUE THREAD

**Issue by ffred** [hecrj/iced#955]
Hi,
tried the examples at home and it works great. now trying it on another - older & simpler - computer (Win8.1 + Intel HD4400 graphic card) and it doesn't work :

``Error: GraphicsAdapterNotFound
error: process didn't exit successfully: `C:\Data\Dev\rust\iced\target\debug\counter.exe` (exit code: 1)``

the Intel HD4400 graphic card is DirectX 11.1 only and don't support Vulkan.... :-(
on [wgpu webpage](https://github.com/gfx-rs/wgpu) it seems to only support DX12 & Vulkan on Windows, but iced webpage say "Vulkan, Metal, DX11, and DX12" support.

so can I make it work also on this computer or not ?
thanks..

**Comment by derezzedex** [comment]
Previously `wgpu` used `gfx-hal` as it's hardware abstraction layer, so it supported DX11, but now with version `0.9` it has moved to a new hardware abstraction layer `wgpu-hal` (see [the family reunion](https://gfx-rs.github.io/2021/07/16/release-0.9-future.html)) which has incomplete support for DX11.

But in your case, you have a graphics card capable of OpenGL 3.3+ so you should be able to use the `glow` renderer by using the `--features glow` to select it when compiling (see [renderers](https://github.com/hecrj/iced/blob/master/ECOSYSTEM.md#renderers) on the `ECOSYSTEM.md`).

I think we should probably remove the claim of DX11 support now that we have upgraded to `wgpu 0.9`.

**Comment by ffred** [comment]
thanks, will try that tomorrow..

**Comment by dhardy** [comment]
WGPU now has "okay" support for OpenGL directly, so shouldn't that work too? For KAS I had to use `--feature wgpu/cross` to let the shaders work (and this support has already been removed from master so won't be in the next WGPU version).

**Comment by ffred** [comment]
ok, just tried rapidly with two examples. it's working.. :-)
with : ```cargo run --package counter --features glow```

thanks..
