### ISSUE TITLE
No Text, no Buttons

### ISSUE THREAD

**Issue by 4parsleythelion** [hecrj/iced#96]
I'm running on Windows 10 (1909), building with Visual Studio Code and the Rust version x86_64-pc-windows-msvc 1.39 and the counter example compiles fine with no issues. When the window comes up the title is there and the window works as I would expect. other then there is no text or button in the window?

Obviously I'm doing something wrong, any ideas?

Thanks,

Ashley

**Comment by hecrj** [comment]
It may be a text rendering issue, as the `counter` example only renders text.

If you run the `tour` example, can you at least see the blue background of the `Next` button?

**Comment by 4parsleythelion** [comment]
Hello Hector,

You are correct the Tour example displays a blue button, and no other text at all.

Ashley

**Comment by 4parsleythelion** [comment]
Hector,

The Radio buttons. buttons, and sliders "appear" to work, and the window changes the title in consort with the progress just no text or images.

Ashley

**Comment by hecrj** [comment]
Could you share your hardware specifications? It seems to be a problem with textures (text cache and images) or texture sampling.

Also, I'd appreciate if you could test the examples in the [`wgpu` repository](https://github.com/gfx-rs/wgpu-rs) and report if you can see textures there.

**Comment by 4parsleythelion** [comment]
Windows 10 Pro 64 Bit AMD A9-9425 Radeon R5, 5 Compute Cores 2C+3G, 8GB Ram AMD Redeon R5 Graphics, 1 TB SSD.

Hector none of the examples in the "wgpu" repository will compile, all have massive amounts of errors.

**Comment by 4parsleythelion** [comment]
Hector,

I downloaded the source and now the wgpu-rs examples work, and the describe one ouputs: AdapterInfo { name: "AMD Radeon(TM) R5 Graphics", vendor: 4098, device: 39140, device_type: DiscreteGpu }

Cube and hello-triangle work also.

**Comment by hecrj** [comment]
@4parsleythelion I gather the `cube` example is displaying the Mandelbrot texture perfectly?

I'd say the next step to diagnose the problem would be to try the [`wgpu_glyph`](https://github.com/hecrj/wgpu_glyph) examples, which is what we use to render text.

**Comment by 4parsleythelion** [comment]
Hi Hector,

Sorry for the delay, but, I'm sorry to say the wgpu_glyph complied correctly and a window is displayed but no text, just a grey background.

Sorry to be the bearer of bad news.

Ashley

**Comment by hecrj** [comment]
@4parsleythelion Thanks for testing and reporting back!

We are tracking this issue in https://github.com/hecrj/wgpu_glyph/issues/28 Hopefully we can figure out what the issue is.

Are your graphics drivers up-to-date?
