### ISSUE TITLE
Build failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by ukashasohail** [hecrj/iced#97]
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()'

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by hecrj** [comment]
Hey, thanks for reporting!

Could you provide a bit more details? The full build backtrace would be helpful to at least know what is causing the issue.
