### ISSUE TITLE
Strange Window frame on Gnome Wayland

### ISSUE THREAD

**Issue by floatingrain** [hecrj/iced#984]
![2021年08月09日上午 08时32分28秒](https://user-images.githubusercontent.com/22867565/128650503-88196e2f-204f-4932-a461-8913da45bcd6.png)
See the window style between iced-clock and VSCode, there window frame styles are different. I'm using Gnome on Wayland, all programs build with iced show strange window frame like this, which is not native desktop environment window, and it looks like a KDE window. But in Gnome on X11, they shows native window style. I think it is a logic mistake while iced shows windows on Wayland.

**Comment by floatingrain** [comment]
@hecrj

**Comment by hecrj** [comment]
Do [the `winit` examples](https://github.com/rust-windowing/winit/tree/master/examples) display the same issue? In that case, we should create an issue there.

I found https://github.com/rust-windowing/winit/issues/1967, which seems related.

**Comment by ilyazzz** [comment]
Gnome on Wayland doesn't support server side decorations and expect applications to implement it themselves. What you see is the fallback window frame of winit, you can also see it when you run applications like alacritty on gnome wayland.

**Comment by kaimast** [comment]
I don't think title bars will ever look fully native on GNOME unless you want to go down the route of parsing the GTK theme.

However, I think a solution to this is to let the application draw a custom header- or titlebar if desired. So the titlebar at least matches the theme of the application. I filed a bug a while ago for this @759.

**Comment by floatingrain** [comment]
However, the default decoration of winit cannot produce shadow effects around windows. If I want to make hierarchical shadows between windows, what should I do?

**Comment by PolyMeilex** [comment]
> However, the default decoration of winit cannot produce shadow effects around windows. If I want to make hierarchical shadows between windows, what should I do?
> In addition, as a comparison, JetBrains' compose for desktop can achieve the effect of Gnome's native window. I don't know if they use X rendering forcibly.

Do they even suport wayland? If it's running under X then gnome is drawing it's decorations as a fallback.

**Comment by floatingrain** [comment]
> > In addition, as a comparison, JetBrains' compose for desktop can achieve the effect of Gnome's native window. I don't know if they use X rendering forcibly.
> 
> Do they even suport wayland? If it's running under X then gnome is drawing it's decorations as a fallback.
> 
> EDIT: You can easily check that with xeyes

I checked, they use X.
