### ISSUE TITLE
Windows (GNU ABI) builds show up as white canvas only and require extra DLLs

### ISSUE THREAD

**Issue by ChriFo** [hecrj/iced#987]
When building an example (at least [tour](https://github.com/hecrj/iced/tree/master/examples/tour) and [progress_bar](https://github.com/hecrj/iced/tree/master/examples/progress_bar)) with help of [cross](https://github.com/rust-embedded/cross) for **x86_64-pc-windows-gnu** and **i686-pc-windows-gnu** the app looks in Windows 10 running in VMware Fusion like this:

<img width="1027" alt="white" src="https://user-images.githubusercontent.com/7130686/128706829-ce52a7af-3dcc-4d69-bf6a-b1f36e30f6bf.png">

When I build the examples for **x86_64-apple-darwin** they work on my macOS 11.5 as expected.

The produced **exe** need some extra DLLs (`libstdc++-6.dll` + `libgcc_s_seh-1.dll` for x86_64 or `libgcc_s_dw2-1.dll` for i686). 
I think this comes from a dependency but  which one do I have to build by my self to have a fully static build?

Thank you for any help or advice.

**Comment by ChriFo** [comment]
I used the `master` branch. But according to this [discussion](https://github.com/hecrj/iced/discussions/976#discussioncomment-1089749) using the current latest release (0.3.0) the mentioned examples worked as expected.

**Comment by ChriFo** [comment]
With a customized cross image for `i686-pc-windows-gnu`
```Dockerfile
FROM rustembedded/cross:i686-pc-windows-gnu

ENV PATH="/usr/lib/gcc/i686-w64-mingw32/7.5-win32:$PATH"

ENV CFLAGS="-static-libgcc -static-libstdc++" \
    CXXFLAGS="$CFLAGS"

ENV CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER=i686-w64-mingw32-g++ \
    CARGO_TARGET_I686_PC_WINDOWS_GNU_RUNNER=wine \
    CC="i686-w64-mingw32-gcc -static" \
    CXX="i686-w64-mingw32-g++ -static"
```
and with that `build.rs`
```rust
use std::env::var;

fn main() {
    let target = var("TARGET").unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    if target.contains("windows") {
        println!("cargo:rerun-if-env-changed=WINAPI_NO_BUNDLED_LIBRARIES");
        println!("cargo:rerun-if-env-changed=WINAPI_STATIC_NOBUNDLE");

        println!("cargo:rustc-link-lib=static=gcc");
        println!("cargo:rustc-link-lib=static=stdc++");
    }
}
```
I was able to build a `exe` which runs without any extra DLL.

# :tada:

**Comment by 0x192** [comment]
@ChriFo 

I am in the same situation all iced exemples windows build ask for extra DLLs. But unfortunately I can't statically link stdc++ and gcc :
```
= note: /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libstdc++.a(compatibility-condvar.o):/build/mingw-w64-gcc/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include/x86_64-w64-mingw32/bits/gthr-default.h:733: undefined reference to `__imp_pthread_mutex_init'
          /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libstdc++.a(compatibility-condvar.o):/build/mingw-w64-gcc/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include/x86_64-w64-mingw32/bits/gthr-default.h:740: undefined reference to `__imp_pthread_mutex_destroy'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

Did you do anything special? Using cross didn't help either...

@hecrj 
Do know which dependency/(ies) could need **stdc++**?

**Comment by ChriFo** [comment]
No, nothing special but using the cross image for **i686**-pc-windows-gnu with the exact `build.rs` shown above.
